### ISSUE TITLE
[v3] consider using position only and keyword only arguments

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#1019]
As a side note we might consider using position only and keyword only arguments in Zarr 3 to avoid these issues around renaming arguments.

_Originally posted by @jakirkham in https://github.com/zarr-developers/zarr-python/issues/1018#issuecomment-1116879414_

**Comment by jhamman** [comment]
@jakirkham and @joshmoore - would either of you care to expand on this issue to make it more actionable?

**Comment by joshmoore** [comment]
My limited memory, @jhamman, is that for signatures with very long lists of arguments, maintaining the ordering of those lists becomes a burden and therefore one can make use of keyword only arguments -- https://peps.python.org/pep-3102/ -- to simplify things.

**Comment by jhamman** [comment]
My first attempt at recreating the top level API for v3 definitely highlighted that this would be useful. I could use some input on #1884 deciding how best to introduce this.
