### ISSUE TITLE
Why is path required for opening Zarr v3 groups?

### ISSUE THREAD

**Issue by shoyer** [zarr-developers/zarr-python#1039]
With Zarr v2, I can open a group by passing either a valid Zarr store or with a path specified as a string, i.e., like `zarr.open_group(store_or_path)`. As I understand it, paths get normalized into store objects, e.g., to a local filesystem or via fsspec.

With Zarr v3, as currently implemented, the `path` argument is apparently now required, per https://github.com/pydata/xarray/pull/6475. This feels like a small step backwards in terms of usability. I'm wondering if I'm missing some broader context here? Maybe some examples of how users would canonically create a group, add an array and then access the data in the new v3 API would be helpful.

**Comment by joshmoore** [comment]
The short version is that previously all (meta)data needed to open a group was at one location but now there is root metadata and the metadata tree is separated from the data tree. The result is that it's much more like opening a Zip file: "open foo.zip and then load /some/file"

cc: @grlee77 for a more complete backstory.

@jbms has proposed notation of some form to simplify the usage. Taking the zip example, `foo.zip#/some/file` or `foo.zip//some/file`.

**Comment by grlee77** [comment]
quick update: I have a PR nearly done for root array/group support in v3. I just need to take a look again later today at one failing test case.
