### ISSUE TITLE
Update build status badge

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#1041]
Since the move from Travis, the build status has been showing "unknown":

![](https://files.slack.com/files-pri/T3TSSEJHE-F03HNG48G5P/screen_shot_2022-05-27_at_15.31.19.png)

An update is needed, but a choice of which workflow (or all) is to be shown must be made.

see: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

**Comment by Alt-Shivam** [comment]
I'm interested in this issue.
will generate a PR soon.

**Comment by Alt-Shivam** [comment]
Hey @joshmoore 
As I can see, Travis CI is giving the same "unknown" status for many repos
So now, we've 3 alternatives to go with
- Circle CI
- GitLab
- or we can go with GH actions, like this
![image](https://user-images.githubusercontent.com/81817735/170854810-0f917619-86e4-4cb3-ac41-5f7e9a1e9c63.png)

**Comment by joshmoore** [comment]
It should definitely be the gh action ones. And sure, this looks like a good way to start. :+1:
