### ISSUE TITLE
Chunks in one file

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [zarr-developers/zarr-python#1048]
Dear all,

Could you tell me if there is a way to concatenate chunk files into one file, or a storage option which supports just one file per array with all chunks inside?

Best regards,
Aliaksei

* Value of ``zarr.__version__``: 2.10.3
* Value of ``numcodecs.__version__``: 0.9.1
* Version of Python interpreter: 3.9.0
* Operating system (Linux/Windows/Mac): Windows 11
* How Zarr was installed (e.g., "using pip into virtual environment", or "using conda"): using pip into virtual environment

**Comment by jakirkham** [comment]
In addition to zip other options include:

* [`SQLiteStore`]( https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.SQLiteStore )
* [`LMDBStore`]( https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.LMDBStore ) (requires `lmdb`)

One could use other single file formats as long as one can come up with a way to access them via [the `MutableMapping` API]( https://docs.python.org/3.8/library/collections.abc.html#collections-abstract-base-classes ).
