### ISSUE TITLE
Saving to plaintext?

### ISSUE THREAD

**Issue by mike-lawrence** [zarr-developers/zarr-python#1062]
When debugging projects using zarr, it would be convenient to be able to use my OS's file explorer to preview the content of datasets as plaintext of some sort (ex. csv). None of the storage formats achieve this, right?

**Comment by clbarnes** [comment]
Do you mean storing (or browsing) individual chunks as CSV? If you wanted to keep the dimensionality of the data in the chunks, CSV would only work for 1 and 2 dimensional data (but JSON could go the rest of the way). A text file with a list of numbers would closer to the binary format. I think the problem you'd have is that for all the structural formats Zarr supports, the internal chunks are largely the same binary format - to see how to intercept the encoding/decoding of chunks, I'd look at the N5Store, as the binary chunk format is slightly different for that.

If you just wanted to check the values in a particular chunk on the file system, you could use a script like

```python
#!/usr/bin/env python3
"""
chunk_values.py

Show values in a zarr chunk with no compression, as 1D array.
"""
import sys
from pathlib import Path
import json
import numpy as np

chunk_path = Path(sys.argv[1])

# search upwards for the array metadata, in case this is a NestedDirectoryStore
parent = chunk_path.parent
while not (parent / ".zarray").is_file():
    parent = parent.parent

meta = json.loads((parent / ".zarray").read_text())
assert meta.get("compressor") is None, "Data is compressed and therefore too complicated for this script"
dtype = np.dtype(meta["dtype"])
arr = np.frombuffer(chunk_path.read_bytes())
for item in arr:
    print(arr)
```

which you'd then use like `chunk_values.py path/to/container.zarr/path/to/array/0.0.0`

**Comment by joshmoore** [comment]
Thanks for the suggestion, @clbarnes. I'm going to close this in favor of the discussion though: https://github.com/zarr-developers/zarr-python/discussions/1063
