### ISSUE TITLE
Make bug tracker more accessible for newcomers

### ISSUE THREAD

**Issue by Saransh-cpp** [zarr-developers/zarr-python#1077]
The issue/bug tracker right now has no labels, and most of the issues don't start with a keyword (example - "BUG: This is not working" or "DOC: Missing docs for this"). Therefore, newcomers have a hard time navigating through the issues, which discourages them from contributing.

Ideally, the issue template should be updated (the current one does not use the new `YAML` format), and more issue templates should be added, for example, feature request, CI improvement, etc.

The issue can be labelled by an automated workflow based on the template from which it was created, or keywords can be added to the template titles. IMO they should be labeled by an automatic workflow, so that a newcomer can quickly search through the labels!

**Comment by joshmoore** [comment]
cc: @MSanKeys963 (on his return from ⛰️)

Thanks for the suggestions, @Saransh-cpp. We're definitely in a period of cleanup. If there are any issues that you have suggestions for labels/prefixes, feel free to let us know. (For GSoC, e.g., I spent some time updating [help-wanted](https://github.com/zarr-developers/zarr-python/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22))

Alternatively, if you want to open a PR for the YAML config or anything to help us along, it'd be very welcome.

All the best,
~J.

**Comment by Saransh-cpp** [comment]
Thanks for the quick reply, @joshmoore! I'll definitely take up some work here!

**Comment by h20200051** [comment]
@joshmoore @Saransh-cpp I would like to work in this issue.Kindly assign me

**Comment by MSanKeys963** [comment]
I think this has already been completed @h20200051. Apologies if you were misguided.

Let me know if you want to work on another issue, and I'm happy to help you.
Closing this now.

**Comment by h20200051** [comment]
Respected sir,
I would like to work under the issue of expose chunk and or slice
imformation (byte offse) and size to tje api and make it available to the
user #1113.Kindly assign me this

Github id:h20200051
