### ISSUE TITLE
Validate dummy data

### ISSUE THREAD

**Issue by TheChymera** [zarr-developers/zarr-python#1082]
I am trying to put together a dummy ZARR file (ideally as small as possible, i.e. structured but empty) in order to provide a minimal exaple to test `.zarr` support for the BIDS data validator (more info on that here: https://github.com/bids-standard/bids-examples/pull/315 ).

I have found this website, and tried to upload my example data on my server, to see whether it's valid ZARR: http://resources.chymera.eu/data/sub-01_ses-01_sample-A_SPIM.ome.zarr

But the website returns `NetworkError when attempting to fetch resource.` for https://ome.github.io/ome-ngff-validator/?source=https://resources.chymera.eu/data/sub-01_ses-01_sample-A_SPIM.ome.zarr

Any idea what I can do, or do you perhaps have some very minimal dummy data examples? There seem to be some examples under `./fixture/` as part of this repository, which I assume are defined as valid, but (1) most of them seem rather larger than necessary for a single minimal example, (2) there exists a `./fixture/.zattrs` file — does this mean that fixture is just *one* example?

**Comment by joshmoore** [comment]
As @satra mentioned in https://github.com/bids-standard/bids-examples/pull/315#issuecomment-1184871664, your Zarr fileset is missing the metadata files that are necessary to decipher the data. Can you share how you created it and how you uploaded it?

**Comment by joshmoore** [comment]
Closing in favor of #1246 under the umbrella of "where should test data live?" But if there are any other questions, please let us know.
