### ISSUE TITLE
Add copy button to docs

### ISSUE THREAD

**Issue by pavithraes** [zarr-developers/zarr-python#1084]
It'll be nice to be able to copy code snippets directly from the docs, [sphinx-copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/index.html) is a lightweight tool that can be used for this.

(Personally, I'd really appreciate this. I help support the Dask community, which involves copying code from the Zarr docs quite often.)

**Comment by tasansal** [comment]
made a pr #1124 @joshmoore

**Comment by joshmoore** [comment]
Thanks, @tasansal!
