### ISSUE TITLE
n5 format output by zarr not compatible with other programs

### ISSUE THREAD

**Issue by GenevieveBuckley** [zarr-developers/zarr-python#1092]
### Zarr version

2.11.1

### Numcodecs version

0.9.1

### Python Version

3.9

### Operating System

Windows

### Installation

Installed using conda-forge

### Description

As described in [this issue](https://github.com/saalfeldlab/paintera/issues/457) the .n5 format output by zarr produces errors when users try to load it into other software requiring n5 input: 

Error message:
```
A valid N5 container is a directory that contains a file attributes.json with a key "n5"
```

This is happening because the data chunks are being written straight into the top level directory (the one with the `.n5` suffix), eg:
```
test.n5/
  - attributes.json
  - 0/
  - 1/
  - 2/
  - ...
```

To fix it, we can write the chunks into a subfolder (perhaps with the default dataset name "raw", with a keyword argument for the user to control). So instead it'd look like this:
```
test.n5/
  - attributes.json  # a new file, with the only contents  like this `{"n5": "2.5.0"}`
  - raw/
    - .attributes.json  # this is the same atributes.json that was previously written into the topmost directory level
    - 0/
    - 1/
    - 2/
    - ...
```

I've chosen the bug template to describe this issue since I feel that interoperability with other programs accepting `.n5` files is pretty important, and is what makes this function so useful in the first place.

### Steps to reproduce

1. Create some dummy data, and save it to N5 using zarr, following the instructions at https://zarr.readthedocs.io/en/stable/api/n5.html

```python
import dask.array as da
import zarr

# Create some dummy data
data_shape = (1000, 1000)
data_chunks = (100, 100)
dummy_data = da.random.randint(0, 255, data_shape, chunks=data_chunks)

# Save as N5 using the zarr library
store = zarr.N5Store('test.n5')
z = zarr.zeros(data_shape, chunks=data_chunks, store=store, overwrite=True)
z[:] = dummy_data
```

2. Attempt to load the data in to the [Paintera software](https://github.com/saalfeldlab/paintera), and observe the error message.

```
conda install -c conda-forge paintera
```

* From the menu, select: `File` > `Open` >  `Raw/Label Source`
* In the dialog box that pops up, select `Find` > `Find Folder`; and then select the `test.n5` file generated using zarr.
* From the `Dataset` dropdown, select whichever dataset is shown
* Then click "Ok" on the file open dialog.

Observe the error message:
```
A valid N5 container is a directory that contains a file attributes.json with a key "n5"
```

**Comment by GenevieveBuckley** [comment]
I'd be willing to work on this, if there is general agreement from the maintainers that this would be a useful thing to have

**Comment by joshmoore** [comment]
Thanks for this, @GenevieveBuckley! It would definitely be good to keep compatibility and perhaps to encode whatever the current disconnect is in https://github.com/zarr-developers/zarr_implementations so it doesn't happen again.

cc: @d-v-b who typically takes care of the `n5.py` module.

**Comment by d-v-b** [comment]
Zarr's implementation of n5 is at variance with the n5 spec -- when writing an array to the root node, we need to insert the `n5` metadata attribute in `{store}/attributes.json`. Right now I think that attribute is only written to the `attributes.json` for groups, so we should fix this. I can whip up a PR shortly unless you want to spearhead it @GenevieveBuckley 

For this to work today, you can specify the `path` argument in `zarr.zeroes` (or any other array creation routine that takes `path` as an argument). E.g., in your example, do
```python
z = zarr.zeros(data_shape, path='raw', chunks=data_chunks, store=store, overwrite=True)
```
This will make an array at `{store}/raw/`, and `{store}/attributes.json` will contain the required `n5` attribute that paintera is complaining about.

**Comment by GenevieveBuckley** [comment]
I might have some time for this tomorrow or Friday. I'll aim to give it a go. 

If you don't hear anything from me by next week, that means I didn't find the time, and then you are welcome to go ahead yourself.
