### ISSUE TITLE
Updated pypa publish action

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#1148]
From the GHA:

> [upload_pypi: # >> PyPA publish to PyPI GHA: UNSUPPORTED GITHUB ACTION VERSION <<#L1](https://github.com/zarr-developers/zarr-python/commit/61af678bd86ce62f9d1b3c4f922e28bc60e47f7e#annotation_4739710302)
> You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.

**Comment by jakirkham** [comment]
Wonder if there is a way to link to latest

**Comment by joshmoore** [comment]
May just need "main"

**Comment by jakirkham** [comment]
Yeah think that is what is being called `unstable/v1` (appears to be their default branch anyway)

**Comment by Saransh-cpp** [comment]
There is a way to get the latest stable release, in fact, `dependabot` will do this for us 😉 -

https://github.com/zarr-developers/zarr-python/blob/daad2fa86a32c3ed10871f6ba191ed3356b29e91/.github/dependabot.yml#L8-L11

We need to pin all the actions to a particular version, and then `dependabot` will update them weekly. I will create a PR for this!

**Comment by jakirkham** [comment]
This is fantastic! Thank you 😄
