### ISSUE TITLE
V3 Consolidated Metadata

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#1161]
follow on to: https://github.com/zarr-developers/zarr-python/pull/1142
background reading: https://github.com/zarr-developers/zarr-specs/issues/136

I would like to propose that we remove the machinery for consolidated metadata in the current V3 implementation in favor of an upcoming specification. This would include:

 - dropping `zarr._storage.v3.ConsolidatedMetadataStoreV3`
 - disallow version=v3 in `zarr.convenience.consolidated_metadata`

**Comment by jhamman** [comment]
Noting that @TomAugspurger has been making solid progress here. See also https://github.com/zarr-developers/zarr-specs/pull/309
