### ISSUE TITLE
Add a link to the installation section on the tutorial page.

### ISSUE THREAD

**Issue by DON-BRAN** [zarr-developers/zarr-python#1167]
The installation section is found [here](https://zarr.readthedocs.io/en/stable/index.html#installation) and is not directly accessible from the [tutorial page](https://zarr.readthedocs.io/en/stable/tutorial.html). Trying to run the samples fail with an error because of no Zarr installation. 

```
>>> import zarr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'zarr'
>>> 
```

**Comment by joshmoore** [comment]
Thanks, @DON-BRAN. Maybe it would even be a good idea to move it into its own file so that it shows up in the left-hand navigation menu.

**Comment by joshmoore** [comment]
I wasn't sure. If it's _always_ visible on the side, then maybe that's enough. What do you think?

**Comment by DON-BRAN** [comment]
> I wasn't sure. If it's _always_ visible on the side, then maybe that's enough. What do you think?

You're right,
If it's always visible by the side, then that's enough.
