### ISSUE TITLE
Update _Forking_the_repository_ section on the contributing page

### ISSUE THREAD

**Issue by DON-BRAN** [zarr-developers/zarr-python#1169]
The code snippet in [_Forking_the_repository_](https://zarr.readthedocs.io/en/stable/contributing.html#forking-the-repository) section on the [contributing page](https://zarr.readthedocs.io/en/stable/contributing.html#)

```
$ git clone git@github.com:your-user-name/zarr.git
$ cd zarr
$ git remote add upstream git@github.com:zarr-developers/zarr-python.git
```

should be 

```
$ git clone git@github.com:your-user-name/zarr-python.git
$ cd zarr-python
$ git remote add upstream git@github.com:zarr-developers/zarr-python.git
```

**Comment by joshmoore** [comment]
Thanks, @DON-BRAN. I remember there being a PR recently that changed this, but I'm not sure which one it is. Feel free to open another if you'd like.

**Comment by joshmoore** [comment]
Thanks. :)
