### ISSUE TITLE
documentation failed to build locally

### ISSUE THREAD

**Issue by DON-BRAN** [zarr-developers/zarr-python#1172]
Using the command 

```
$ tox -e docs
```

throws error 

```
Running Sphinx v5.2.3

Warning, treated as error:
Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
```

setting `language = "en"` in `conf.py` solves the issue.

Will it be alright to set the default language code to "en" for the [zarr documentation](https://zarr.readthedocs.io/en/latest/contributing.html#documentation)?

**Comment by joshmoore** [comment]
I'd think so, @DON-BRAN. I've never seen this before, but maybe something has changed in more recent Sphinx versions.

**Comment by DON-BRAN** [comment]
> I'd think so, @DON-BRAN. I've never seen this before, but maybe something has changed in more recent Sphinx versions.

@joshmoore will it be helpful to provide more logs for further investigation on this behavior?

**Comment by joshmoore** [comment]
I don't think so. If manually setting to `en` works, then that makes sense.

see: https://github.com/sphinx-doc/sphinx/issues/10474

**Comment by DON-BRAN** [comment]
> I don't think so. If manually setting to `en` works, then that makes sense.
> 
> see: [sphinx-doc/sphinx#10474](https://github.com/sphinx-doc/sphinx/issues/10474)

I will update the conf.py to have `language = "en"`

**Comment by GbotemiB** [comment]
@DON-BRAN did setting the language = 'en' resolved the issue?

**Comment by DON-BRAN** [comment]
> @DON-BRAN did setting the language = 'en' resolved the issue?

yes @GbotemiB it did
