### ISSUE TITLE
Update README.md link to _installation documentation_. 

### ISSUE THREAD

**Issue by DON-BRAN** [zarr-developers/zarr-python#1176]
[README.md](https://github.com/zarr-developers/zarr-python#readme) installation documentation points to https://zarr.readthedocs.io/en/stable/#installation. 
I was wondering if it needed to point to the updated documentation at https://zarr.readthedocs.io/en/latest/installation.html.

Also the other links on the [README.md](https://github.com/zarr-developers/zarr-python#readme) page point to the _stable_branch_ link on _readthedocs_.
I was thinking it would be good to have them point to _latest_branch_ rather

**Comment by DON-BRAN** [comment]
> Yes, definitely, and if you can find any other mentions of `#installation` those as well.

@joshmoore will it be alright to change the other links pointing to the stable branch to point to the latest branch. For example
https://zarr.readthedocs.io/en/stable/tutorial.html#creating-an-array to https://zarr.readthedocs.io/en/latest/tutorial.html#creating-an-array

**Comment by joshmoore** [comment]
Keep everything on 'stable'. As soon as we release your previous changes it'll get updated.
