### ISSUE TITLE
Duplicate label spec_v2 in /docs/spec/v3.rst and /docs/spec/v2.rst

### ISSUE THREAD

**Issue by DON-BRAN** [zarr-developers/zarr-python#1181]
Command
```
tox -e docs
```
ends in an error.
 
I think the label in /docs/spec/v3.rst should be 
```
.. _spec_v3:
```
and not 
```
.. _spec_v2:
```

**Comment by joshmoore** [comment]
good catch! https://github.com/zarr-developers/zarr-python/pull/1173/files#diff-be95f06c66dc4e83649730460a2a021b632924a9b39ded2296e1e2eed9de5bb3R1
