### ISSUE TITLE
Pytest Error when running TestSuite due to MsgPack

### ISSUE THREAD

**Issue by GbotemiB** [zarr-developers/zarr-python#1187]
I think the instruction to install msgpack should be included in the installation docs when trying to install zarr from source code for development purpose.

**Comment by joshmoore** [comment]
Thanks, @GbotemiB. It certainly seems so! However, I do wonder if that's only an issue on Windows, and if so, if we can do something to make it not the case.

**Comment by GbotemiB** [comment]
It is actually an issue in linux systems as msgpack is not pre installed
