### ISSUE TITLE
Setup.py missing from repo

### ISSUE THREAD

**Issue by GbotemiB** [zarr-developers/zarr-python#1199]
![image](https://user-images.githubusercontent.com/48842684/196394376-82ed8177-287c-4d37-b3c8-296a19e90f92.png)

![image](https://user-images.githubusercontent.com/48842684/196394565-e756377a-a0b2-4e02-8657-b91f47cc311c.png)

It seems setup.py is missing from the main repo @joshmoore and @MSanKeys963

**Comment by jakirkham** [comment]
Yeah PR ( https://github.com/zarr-developers/zarr-python/pull/1158 ) merged a couple days ago changed this. Maybe there are fixes needed?

cc @Saransh-cpp

**Comment by Saransh-cpp** [comment]
The latest documentation outlines the correct way to install `Zarr` - https://zarr.readthedocs.io/en/latest/installation.html#installation. The following should work -

```
python3 -m pip install .
```

Note: Commands like `python setup.py install` should not be used as they are unmaintained. They are now usually referred to as "legacy" commands.
Tip: Always look at the "latest" or "dev" documentation if you are installing from source 😉

**Comment by jakirkham** [comment]
@GbotemiB, if you are still seeing this in the docs somewhere, a PR to update them would be welcome 🙂

**Comment by GbotemiB** [comment]
@Saransh-cpp is right. It is only appearing on the stable branch.

**Comment by GbotemiB** [comment]
I think the [docs](https://zarr.readthedocs.io/) links on the [README](https://github.com/zarr-developers/zarr-python/blob/main/README.md) should link to the [latest](https://zarr.readthedocs.io/en/latest/installation.html#installation) docs

**Comment by jakirkham** [comment]
Yeah not sure. The README is capturing first time users that are likely on a stable release (just trying things out). That link may make sense for them.
