### ISSUE TITLE
Re-use tox where possible from GHA workflows

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#1211]
If the tox.ini file is going to be maintained, then existing workflows should make use of it.

e.g. see https://github.com/zarr-developers/zarr-python/pull/1210#issuecomment-1287771539 in which the `tox -e docs` target was not being tested anywhere.

**Comment by MSanKeys963** [comment]
Hi @joshmoore. Is this issue good for `good-first-issue`?

**Comment by joshmoore** [comment]
Yeah, definitely.

**Comment by jakirkham** [comment]
Suppose the other option would be to drop it

**Comment by MSanKeys963** [comment]
> Suppose the other option would be to drop it

Do you mean not using GHA?

**Comment by joshmoore** [comment]
I think he means drop tox.

**Comment by Saransh-cpp** [comment]
`tox.ini` does three things right now -
- testing - I am not sure if this is up to date
- building docs - this can be carried out using `$ cd docs; make html`
- specifying flake8's `max-line-length` - this is now handled by `pre-commit`

Getting rid of it does sound like a good idea.

**Comment by jakirkham** [comment]
Thanks for checking Saransh! 🙏

Would you like to open a PR?

**Comment by joshmoore** [comment]
Discussion in #1219 had led to the choice to drop tox.
