### ISSUE TITLE
Tox build breaks with python 3.8

### ISSUE THREAD

**Issue by steph237** [zarr-developers/zarr-python#1215]
In a scenario where the build fails, one need to change the 
basepython = python3.8 to the latest version of python( for Ubuntu 22.04 ).
Find the Logs  here 

action: docs, msg: getenv
cwd: /home/steph/zarr-python
cmd: /home/steph/zarr-python/.tox/docs/bin/pip install --no-binary=numcodecs -rrequirements_rtfd.txt
Traceback (most recent call last):
  File "/home/steph/zarr-python/.tox/docs/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 42, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/locations/__init__.py", line 67, in <module>
    from . import _distutils
  File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/locations/_distutils.py", line 21, in <module>
    from distutils.command.install import SCHEME_KEYS
  File "/usr/lib/python3.8/distutils/command/install.py", line 13, in <module>
    from distutils.sysconfig import get_config_vars, is_virtual_environment
  File "/usr/lib/python3.8/distutils/sysconfig.py", line 23, in <module>
    from sysconfig import (
ImportError: cannot import name '_variable_rx' from 'sysconfig' (/usr/lib/python3.8/sysconfig.py)

**Comment by joshmoore** [comment]
Hi @steph237. This is a really odd error. It's happening in a part of Python that Zarr doesn't have any control over. Can you explain how you installed Python? Was it working previously?

If possible, you might want to set up a fresh environment and see if it's still happening.

**Comment by DON-BRAN** [comment]
> In a scenario where the build fails, one need to change the basepython = python3.8 to the latest version of python( for Ubuntu 22.04 ). Find the Logs here
> 
> action: docs, msg: getenv cwd: /home/steph/zarr-python cmd: /home/steph/zarr-python/.tox/docs/bin/pip install --no-binary=numcodecs -rrequirements_rtfd.txt Traceback (most recent call last): File "/home/steph/zarr-python/.tox/docs/bin/pip", line 5, in from pip._internal.cli.main import main File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 9, in from pip._internal.cli.autocompletion import autocomplete File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in from pip._internal.cli.main_parser import create_main_parser File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 8, in from pip._internal.cli import cmdoptions File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in from pip._internal.cli.parser import ConfigOptionParser File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/cli/parser.py", line 12, in from pip._internal.configuration import Configuration, ConfigurationError File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/configuration.py", line 26, in from pip._internal.utils.logging import getLogger File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 29, in from pip._internal.utils.misc import ensure_dir File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 42, in from pip._internal.locations import get_major_minor_version File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/locations/**init**.py", line 67, in from . import _distutils File "/home/steph/zarr-python/.tox/docs/lib/python3.8/site-packages/pip/_internal/locations/_distutils.py", line 21, in from distutils.command.install import SCHEME_KEYS File "/usr/lib/python3.8/distutils/command/install.py", line 13, in from distutils.sysconfig import get_config_vars, is_virtual_environment File "/usr/lib/python3.8/distutils/sysconfig.py", line 23, in from sysconfig import ( ImportError: cannot import name '_variable_rx' from 'sysconfig' (/usr/lib/python3.8/sysconfig.py)

Hi @steph237 I encountered this issue when I was trying to setup my development environment previously. However when I install `build-essential` on `Ubuntu 22.04` using the command `sudo apt install build-essential` everything started working as documented and I was able to build the docs without modifying the configurations. It seems the build need `g++/GNU compiler collection` installed on your machine. 

You can try this process after setting up a fresh environment as @joshmoore mentioned in the comment above. 🙂

**Comment by steph237** [comment]
@DON-BRAN it works now
@joshmoore  I think the solution @DON-BRAN this should be mentioned in the docs considering the fact that we may not be the only ones facing this issue

**Comment by GbotemiB** [comment]
I also had this issue too.

**Comment by joshmoore** [comment]
Note the decision from #1211 to drop tox, so no additional documentation will be needed.
