### ISSUE TITLE
ZipStore: zipfile.BadZipFile with multiprocess pytorch dataloader

### ISSUE THREAD

**Issue by croth1** [zarr-developers/zarr-python#1218]
### Zarr version

2.12.0

### Numcodecs version

0.10.2

### Python Version

3.9.13

### Operating System

Linux

### Installation

conda-forge

### Description

Looks pretty much like: https://github.com/python/cpython/issues/86535, thanks @joshmoore for pointing me to it. This one however is already patched for my interpreter. 

The code below also leads to a `zipfile.BadZipFile` error on my system: `zipfile.BadZipFile: Bad CRC-32 for file 'foo/7.0.0'`.

Maybe actually a python not a zarr bug?

### Steps to reproduce
deps: `conda create -n foo -c conda-forge python=3.9 pytorch pytorch-lightning zarr`
```
import torch
from torch.utils.data import Dataset, DataLoader
from pytorch_lightning import LightningModule, Trainer
import zarr

with zarr.ZipStore('/tmp/foo.zip', mode='w') as store:
    grp = zarr.group(store, overwrite=True)
    grp.create("foo", shape=(42, 256, 256), chunks=(5, None, None))
    grp["foo"][:] = 42

class FooDataset(Dataset):
    def __init__(self):
        store = zarr.ZipStore('/tmp/foo.zip', mode='r')
        self._grp = zarr.group(store)

    def __len__(self):
        return 42

    def __getitem__(self, idx):
        return self._grp["foo"][idx]

class DummyModule(LightningModule):
    def predict_step(self, batch, batch_idx):
        return 0

trainer = Trainer()
data_loader = DataLoader(FooDataset(), batch_size=1, num_workers=5)
while True:
    trainer.predict(DummyModule(), dataloaders=data_loader)
```

**Comment by martindurant** [comment]
It would be great if you can reduce the example to not need torch.

**Comment by croth1** [comment]
I spend 10 minutes or trying to reproduce with multiprocessing.Pool, just like the one in the python issue, but I didn't manage :(. Might be able to play around a bit more tomorrow.

**Comment by jakirkham** [comment]
The [`concurrent.futures.ProcessPoolExecutor`]( https://docs.python.org/3/library/concurrent.futures.html#processpoolexecutor-example ) might be an easier way to explore this than `multiprocessing.Pool`

FWIW Dask has [an adapter class to expose `multiprocessing.Pool` as a `concurrent.futures.Executor`]( https://github.com/dask/dask/blob/a62c0087bf8dcc7fb207287596367b94ac8c9bd5/dask/local.py#L566-L583 ) (if it helps)

Wouldn't be surprised if the behavior is dependent on [the *start method* closed in `multiprocessing`]( https://docs.python.org/3.8/library/multiprocessing.html#contexts-and-start-methods ) (as Martin alluded to [in Gitter]( https://gitter.im/zarr-developers/community?at=635673e89ee3ec22b4d99efe ))

**Comment by croth1** [comment]
Revisited this, and it seems to be a bug on my side: the code needs to be protected by `if __name__ == '__main__'`, otherwise pytorch's way of using parallelism will lead to the zip store creation code being called multiple times and overwriting the zip while it is being read.

**Comment by jakirkham** [comment]
Yeah this is a common pattern needed when using Python `multiprocessing` for parallelism as well.

**Comment by rabernat** [comment]
Would it be worth documenting somewhere best practices for using Zarr with pytorch?
