### ISSUE TITLE
Fixing minor errors in documentation

### ISSUE THREAD

**Issue by sprynt001** [zarr-developers/zarr-python#1234]
I was going through the tutorials and documentation and noticed a couple of things which I think need to be corrected. I am sure of one, but I want to enquire about the other.
1. In the last cell of [Advanced indexing->Indexing with coordinate arrays](https://zarr.readthedocs.io/en/stable/tutorial.html#indexing-with-coordinate-arrays) the results for `z[1, [1, 3]]` and `z[[1, 1], [1, 3]]` are wrong, they should be `array([6, 8])`
2. The last sentence in the second paragraph of [Chunks section in specification](https://zarr.readthedocs.io/en/stable/spec/v2.html#chunks) says:

> The chunk with indices (0, 0) provides data for rows 0-1000 and columns 0-1000 and is stored under the key “0.0”; the chunk with indices (2, 4) provides data for rows 2000-3000 and columns 4000-5000 and is stored under the key “2.4”;
 
I believe chunk with indices (0,0) provides data for rows 0-999 and columns 0-999 and (2,4) for rows (2000-2999) and columns (4000-4999). Is this correct or am I misunderstanding something?

I am happy to updated the documentation as necessary and generate a PR.

**Comment by joshmoore** [comment]
Thanks for reading so carefully, @sprynt001! Do please open a PR if you are so inclined.
