### ISSUE TITLE
Migrating to GitHub code scanning

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-python#1248]
In one of [the recent LGTM jobs]( https://lgtm.com/projects/g/zarr-developers/zarr-python/rev/pr-4fc65c019cae48764eda234b21e680e94cf80449 ), the following message shows up:

> LGTM.com will be shut down in December 2022 — we recommend that you use GitHub code scanning instead. Read more in [our blog post on the GitHub blog]( https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/ ).

So opening this to discuss migrating since December 2022 is coming soon.

**Comment by jakirkham** [comment]
@DimitriPapadopoulos, do you have thoughts on this?

**Comment by joshmoore** [comment]
Hmm.... I thought this was done with #1127 and #1191 -- maybe just since #1149 came in between?

**Comment by DimitriPapadopoulos** [comment]
Yes, it's done for zarr-python, but not yet for numcodecs, see https://github.com/zarr-developers/numcodecs/pull/361 – help welcome.

**Comment by jakirkham** [comment]
Interesting the job linked in the OP is a zarr-python job. Is there more we still need to do here?

Thanks for taking a look at numcodecs as well :)

**Comment by DimitriPapadopoulos** [comment]
I think @joshmoore addressed that: [PR #1149](https://lgtm.com/projects/g/zarr-developers/zarr-python/rev/pr-4fc65c019cae48764eda234b21e680e94cf80449) predates #1191 which eventually got rid of `.lgtm.yml`.

**Comment by joshmoore** [comment]
Closing this, but feel free to re-raise if anyone seems "LGTM" still hanging around.
