### ISSUE TITLE
Sync v3 implementation with spec

### ISSUE THREAD

**Issue by jstriebel** [zarr-developers/zarr-python#1290]
### Description

There have been (and still are) updates to the spec since #898 introduced v3 support, that did not land in zarr-python yet.
A changelog is available here: https://zarr-specs.readthedocs.io/en/latest/v3/core/v3.0.html#change-log

#1269 is a concrete issue for one of the updates done in the spec. The spec is not completely finalized yet. It's safe to assume no large changes after the vote for the related ZEP 1 (planned for end of January, see https://github.com/zarr-developers/zeps/discussions/24).

Besides updates in the spec itself, we should double-check that the implementation does not provide more features than the spec to not create standards that are not in the spec yet. One concrete example here is #1161.

Other related issues:
* #1019

**Comment by jstriebel** [comment]
cc @joshmoore @MSanKeys963 @rabernat
PS: I guess this should rather have the `V3-compat` label

**Comment by jhamman** [comment]
Cross posting https://github.com/zarr-developers/zarr-python/discussions/1480 where we are coordinating a group effort toward this ticket.

**Comment by jhamman** [comment]
I've created a number of actionable tickets that can (hopefully) be addressed individually in an effort to bring Zarr-Python in sync with the spec. The current list includes:

- [ ] https://github.com/zarr-developers/zarr-python/issues/1269
- [ ] https://github.com/zarr-developers/zarr-python/issues/1514
- [ ] https://github.com/zarr-developers/zarr-python/issues/1516
- [ ] https://github.com/zarr-developers/zarr-python/issues/1517
- [ ] https://github.com/zarr-developers/zarr-python/issues/1513

these are all being tracked in the [Zarr-Python - Refactoring Project](https://github.com/orgs/zarr-developers/projects/5). We can keep this ticket open until all the major sub-tickets are closed out.

**Comment by jhamman** [comment]
All the major tickets are closed here. See progress toward the v3 release here: https://github.com/orgs/zarr-developers/projects/5
