### ISSUE TITLE
store metadata explicitly without the dot?

### ISSUE THREAD

**Issue by jingpengw** [zarr-developers/zarr-python#1322]
currently, the metadata is stored in the `.zarray` file. 
The web server in our cluster does not serve dotfile! Since it is a public service, I do not have permission to change it.
Would it be better to rename it without the dot?

**Comment by rabernat** [comment]
This will be changed in Zarr v3. https://zarr-specs.readthedocs.io/en/latest/core/v3.0.html

**Comment by jingpengw** [comment]
cool! great! Thank you for the information!
