### ISSUE TITLE
Refactor core.py

### ISSUE THREAD

**Issue by jstriebel** [zarr-developers/zarr-python#1329]
Atm there is quite some :spaghetti: code in `core.py`, especially around the different read and write cases (partial reads, decode, encode, …). It would be great to refactor this a bit, some ideas:
* add a protocol for codecs to help with partial reads/writes
* add high-level explanation of indexers and selection methods (probably can be refactored)

**Comment by rabernat** [comment]
I agree that a refactoring is needed and would be eager to help.

**Comment by jstriebel** [comment]
Trying to list different use-cases we might want to have in mind when refactoring the API:
* efficient reads & writes for multiple and partial keys (#1106)
  This can be used for uncompressed reads/writes of subchunks, and when using shardings, or with codecs that allow partial reads & writes (e.g. zfp, see https://github.com/zarr-developers/numcodecs/issues/117). The blosc 1 implementation currently also uses partial reads, but a buffer of the full size to comply with the codec.
* custom array classes (#1131)
* consice store API to ease new implementations
* async support (#1104)

Some questions come to my mind. They don't all need to be answered for the refactoring, but I assume they still might help:
* What's the level of backwards-compatibility required? E.g. do third-party store implementations need to continue to work?
* What's the expected (future) usage of zarr with [other array libraries](https://data-apis.org/array-api/latest/purpose_and_scope.html#stakeholders
), and regarding the [array API](https://data-apis.org/array-api)? This defines what features are expected, e.g. what kind of indexing should work out of the box, is #1256 in the zarr scope or not?
* How important are in-memory stores except for tests?

(The refactoring should be no means solve any of those things above, rather make solving them easy if we think they might come up soon).

Also, we might want to wait for #1323 to be done before starting a larger refactoring.

What are the next steps? I'd propose to
* propose APIs and sequence diagrams
* discuss
* consider backwards-compatibility
* implement

cc @d-v-b @martindurant @joshmoore @jakirkham

**Comment by jstriebel** [comment]
A large refactoring effort is on it's way, for the relevant discussions please see https://github.com/zarr-developers/zarr-python/discussions/1480 & https://github.com/zarr-developers/zarr-python/discussions/1569. Closing this issue as a duplicate.
