### ISSUE TITLE
N5Store wrong behavior - dtype

### ISSUE THREAD

**Issue by mzouink** [zarr-developers/zarr-python#1339]
### Zarr version

v2.13.3

### Numcodecs version

v0.11.0

### Python Version

3.8

### Operating System

Mac

### Installation

using conda

### Description

N5Store is exposing N5 data as Zarr. 
When asking for ".zarray" the store convert the key to "attributes.json". then, read the file and convert the meta key and values to Zarr conventions. but for data type it is kept as numpy `dtype ("uint8")` which should be `dtype.str` ("|u1")

The problem is solved by `Array`. But when i want to expose the store to other service i get bugs.
@d-v-b 

### Steps to reproduce

```
import json
import zarr
from zarr.n5 import N5FSStore
from zarr.storage import MemoryStore

n5_store = N5FSStore('/tmp/test_n5')
z = zarr.open(n5_store)
z.create_dataset("test", shape=(1000, 1000, 10), dtype="u1")

print(json.loads(zarr_store["test/.zarray"])["dtype"])

zarr_store = MemoryStore()
z = zarr.open(zarr_store)
z.create_dataset("test", shape=(1000, 1000, 10), dtype="u1")

print(json.loads(n5_store["test/.zarray"])["dtype"])
```

### Additional output

uint8
|u1

**Comment by MSanKeys963** [comment]
Solved in https://github.com/zarr-developers/zarr-python/pull/1340. Closing this now.
Thanks, @mzouink!
