### ISSUE TITLE
ReadOnlyError when opening a v3 store

### ISSUE THREAD

**Issue by jhamman** [zarr-developers/zarr-python#1382]
### Zarr version

v2.14.2

### Numcodecs version

v0.11.0

### Python Version

3.10.8

### Operating System

Mac (M2)

### Installation

pip

### Description

When opening a v3 store, it is possible to trigger `zarr.errors.ReadOnlyError: object is read-only` when `mode='r'`. 

### Steps to reproduce

The reproducer here is a bit tough because it requires using Fsspec+Kerchunk+ZarrV3 but I'll show a traceback and point to a traceback and a where the offending code is in Zarr:

Traceback:

```python
/Users/jhamman/miniforge3/envs/zarr-testlib/python3.10/site-packages/xarray/backends/api.py:526: in open_dataset
    backend_ds = backend.open_dataset(
/Users/jhamman/miniforge3/envs/zarr-testlib/python3.10/site-packages/xarray/backends/zarr.py:891: in open_dataset
    store = ZarrStore.open_group(
/Users/jhamman/miniforge3/envs/zarr-testlib/python3.10/site-packages/xarray/backends/zarr.py:430: in open_group
    zarr_group = zarr.open_group(store, **open_kwargs)
/Users/jhamman/miniforge3/envs/zarr-testlib/python3.10/site-packages/zarr/hierarchy.py:1416: in open_group
    store = _normalize_store_arg(
/Users/jhamman/miniforge3/envs/zarr-testlib/python3.10/site-packages/zarr/hierarchy.py:1288: in _normalize_store_arg
    return normalize_store_arg(store,
/Users/jhamman/miniforge3/envs/zarr-testlib/python3.10/site-packages/zarr/storage.py:181: in normalize_store_arg
    return normalize_store(store, storage_options, mode)
/Users/jhamman/miniforge3/envs/zarr-testlib/python3.10/site-packages/zarr/_storage/v3.py:622: in _normalize_store_arg_v3
    store['zarr.json'] = store._metadata_class.encode_hierarchy_metadata(None)
/Users/jhamman/miniforge3/envs/zarr-testlib/python3.10/site-packages/zarr/_storage/v3.py:115: in __setitem__
    super().__setitem__(key, value)
```

This happens because Zarr is trying to add a key to a store that is opened with mode='w':

https://github.com/zarr-developers/zarr-python/blob/4b0705c6d85cdfc20a33cbb39a90c8c9d11006c1/zarr/_storage/v3.py#L621-L622

### Additional output

A localized reproducer can be triggered like this:

```python
out = {'version': 1, 'refs': {'zarr.json': '{"extensions":[],"metadata_encoding":"https:\\/\\/purl.org\\/zarr\\/spec\\/protocol\\/core\\/3.0","metadata_key_suffix":".json","zarr_format":"https:\\/\\/purl.org\\/zarr\\/spec\\/protocol\\/core\\/3.0"}', 'meta/root.group.json': '{"attributes":{"_zroot":"<zarr.hierarchy.Group \'\\/\'>","attr0":"3"}}', 'meta/root/data.array.json': '{"attributes":{"_ARRAY_DIMENSIONS":["x","y"]},"chunk_grid":{"chunk_shape":[10,10],"separator":"\\/","type":"regular"},"chunk_memory_layout":"C","data_type":">f8","extensions":[],"fill_value":null,"shape":[10,10]}', 'data/root/data/c0/0': ['memory://data.nc3', 152, 800]}}
_normalize_store_arg_v3("reference://", storage_options={"fo": out, "remote_protocol": "memory"})
```

The full reproducer is a test failure in Kerchunk:

- https://github.com/fsspec/kerchunk/pull/292
- https://github.com/fsspec/kerchunk/actions/runs/4070352216/jobs/7184796481#step:5:763

### Proposal

This could be a fairly simple fix to `_normalize_store_arg_v3` where the 'zarr.json' key is only added when the store is writable:

```python
if mode != 'r':
    store['zarr.json'] = store._metadata_class.encode_hierarchy_metadata(None) 
```

cc @martindurant

**Comment by rabernat** [comment]
There have been a _ton_ of these "read only" errors recently.
- https://github.com/zarr-developers/zarr-python/issues/1352
- https://github.com/zarr-developers/zarr-python/issues/1353
- https://github.com/zarr-developers/zarr-python/issues/1306
- https://github.com/zarr-developers/zarr-python/issues/1362

I thought we fixed it in 2.14.2. But maybe not fully.
