### ISSUE TITLE
Release 2.15.0a1

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-python#1401]
Raising this to discuss making a release

Since there is some new functionality we may want to fine tune, am suggesting an alpha release (in line with what we have done in the past)

Continued from this discussion ( https://github.com/zarr-developers/zarr-python/pull/1378 )

**Comment by jakirkham** [comment]
Thoughts @joshmoore @rabernat ?

**Comment by joshmoore** [comment]
Apologies for the quiet slowness (slow quietness?) Trusting all of you on the to pre-release or not decision, I think there's no reason to not get the _pre-release_ out ASAP. I'll review the docs in #1404 and then tag ASAP.

**Comment by jakirkham** [comment]
Thanks Josh! 🙏
