### ISSUE TITLE
Appending data using Zarr resize and Dask store produce 0s values or access errors

### ISSUE THREAD

**Issue by josephnowak** [zarr-developers/zarr-python#1414]
### Zarr version

2.14.2

### Numcodecs version

0.10.2

### Python Version

3.9.7

### Operating System

Windows

### Installation

Using pip install zarr command

### Description

I'm trying to append data to an existing Zarr array using Dask store without adding a lock, but for some reason, it is producing multiple random 0s or even access errors, I have already tried to use the Xarray to_zarr method with the append_dim option for this but it also generates the same problem (I already reported this problem some years ago in Xarray https://github.com/pydata/xarray/issues/5511).

### Steps to reproduce

```py
import zarr
import numpy as np
import dask.array as da

# Writing an small zarr array with 42.2 as the value
z1 = zarr.open('data/example.zarr', mode='w', shape=(152), chunks=(30), dtype='f4')
z1[:] = 42.2

# resizing the array 
z2 = zarr.open('data/example.zarr', mode='a')
z2.resize(308)

z2 = zarr.open('data/example.zarr', mode='a')

# New data to append
append_data = da.from_array(np.array([50.3] * 156), chunks=(30))

# If you pass to the lock parameters None or False you will get the PermissonError or some 0s in the final result.
da.store(append_data, z2, regions=[tuple([slice(152, 308)])], lock=None)

# the result can contain many 0s or throw an error
print(z2[:])
```

**Comment by MSanKeys963** [comment]
Hi @josephnowak, thanks for raising the issue.
I could reproduce the bug, and it's happening as you described above.

@jrbourbeau, do you have an idea if this could be something on Dask's end? 
Thanks!

**Comment by josephnowak** [comment]
Hi, hopefully, this help to find the bug.
I was checking that if I rechunk the array based on the overlapping region then the issue disappears, so I suspect that dask.store is not properly aligning the chunks of the array with the ones of the storage if and only if one of those chunks is not perfectly overlapped.

I did the following code to exemplify the behavior:

```py3
import zarr
import numpy as np
import dask.array as da


chunk_size = 3

# Size of the original array stored on the first part of the code
original_array_size = 9

# Complete size of the new data
new_data_size = 12

# Indicate how much of the new data is not perfectly aligned with the chunks of the storage
imperfect_overlapping_size = 1

# New size of the original array
resize = original_array_size + new_data_size - imperfect_overlapping_size

# Size of the data that is going to be append
append_data_size = new_data_size - imperfect_overlapping_size

for apply_overlap_rechunk in [True, False]:
    # Writing a small Zarr array with 1.2 as the value
    z1 = zarr.open(
        'data/example.zarr',
        mode='w', 
        shape=(original_array_size, ), 
        chunks=(chunk_size, ),
        dtype='f4'
    )
    z1[:] = 1.2

    # resizing the array 
    z2 = zarr.open('data/example.zarr', mode='a')
    z2.resize(resize)

    # New data to append
    append_data = da.from_array(
        np.array([2.3] * new_data_size),
        chunks=(chunk_size, )
    )
    
    if apply_overlap_rechunk:
        # If this option is enabled then there are no errors, so I suspect that the dask store
        # is not aligning properly the chunks if there is one that is not perfectly aligned
        
        # Modify the chunks based on the overlapping region size, in this example, only one cell is not perfectly overlapped
        new_chunks = (
            imperfect_overlapping_size, 
            *[
                min(chunk_size, append_data_size - c) 
                for c in range(0, append_data_size, chunk_size)
            ]
        )

        append_data = append_data.rechunk(
            (new_chunks, )
        )
        # This how the new chunks looks
        print(append_data.chunks)

    # If you pass to the lock parameters None or False you will get the PermissonError or some 0s in the final result.
    da.store(
        append_data, 
        z2, 
        regions=[
            (slice(original_array_size - imperfect_overlapping_size, resize),)
        ], 
        lock=None
    )

    # the result can contain many 0s or throw an error
    print(z2[:])
```

**Comment by josephnowak** [comment]
I was validating the tasks generated by the Dask store (using the same code that I sent previously but with the compute option equal to False) and I found the following tasks:
```py3
(('store-map-2b21182fc59ba2dd3586e7df25a4fa73', 0), (<function store_chunk at 0x7f73dc37ae50>, ('array-a0e18d6341ddffe755ee7ef403660d62', 0), <zarr.core.Array (20,) float32>, (slice(8, 11, None),), None, False))
(('store-map-2b21182fc59ba2dd3586e7df25a4fa73', 1), (<function store_chunk at 0x7f73dc37ae50>, ('array-a0e18d6341ddffe755ee7ef403660d62', 1), <zarr.core.Array (20,) float32>, (slice(11, 14, None),), None, False))
(('store-map-2b21182fc59ba2dd3586e7df25a4fa73', 2), (<function store_chunk at 0x7f73dc37ae50>, ('array-a0e18d6341ddffe755ee7ef403660d62', 2), <zarr.core.Array (20,) float32>, (slice(14, 17, None),), None, False))
(('store-map-2b21182fc59ba2dd3586e7df25a4fa73', 3), (<function store_chunk at 0x7f73dc37ae50>, ('array-a0e18d6341ddffe755ee7ef403660d62', 3), <zarr.core.Array (20,) float32>, (slice(17, 20, None),), None, False))
```

The slices indicate that the reads and writes are not independent, for example on the first slice it is going to write to the array as follows z[8:11] = arr, then it is going to assign on z[11: 14] but due that the chunks are of size 3, both slices are going to write on the chunk 4 (chunk 1 goes from 0 to 2, chunk 2 from 3 to 6, chunk 3 from 7 to 9, chunk 4 from 10 to 12), so I think that explain the problem with dask.store, so probably it would be good to add a parameter to the method that allows aligning the chunks of the source array with the one on the target to avoid nonindependent writes or if that is not an option at least have a warning on the docs indicating that the method needs a Lock if and only if the chunks are not correctly aligned by the user.

**Comment by josephnowak** [comment]
Hi, I will close this issue, I sent a PR to Xarray to fix the validation of the chunks alignment and now a proper error is raised on the Xarray side to prevent these scenarios.
