### ISSUE TITLE
SQLiteStore Locking

### ISSUE THREAD

**Issue by John-P** [zarr-developers/zarr-python#1417]
When using the `SQLiteStore` I am encountering the error `sqlite3.programmingerror: recursive use of cursors not allowed.` from `__getitem__`:

https://github.com/zarr-developers/zarr-python/blob/cc16d8c8cbafc2dd736f11b9c1ad28a58529e40d/zarr/storage.py#L2591-L2595

Should this use `with self.lock` as `__delitem__` does? Adding that in appears to fix the issue for me.

https://github.com/zarr-developers/zarr-python/blob/cc16d8c8cbafc2dd736f11b9c1ad28a58529e40d/zarr/storage.py#L2600-L2604

**Comment by John-P** [comment]
Happy to open a PR for this, but I wasn't sure if this was intentionally not done for some reason.

**Comment by jhamman** [comment]
I'm going to close this. Sorry it didn't get any traction here. This store has been deprecated and will be removed in 3.0.
