### ISSUE TITLE
Mailing list for Zarr-Python Core devs

### ISSUE THREAD

**Issue by MSanKeys963** [zarr-developers/zarr-python#1439]
Hi all. 👋🏻 

We're creating a mailing list (Google group) for the current Zarr-Python core devs listed here → @zarr-developers/python-core-devs.

We want to coordinate with Zarr-Python core devs on the upcoming roadmap for the development.

We've successfully added some of you from the list but couldn't find the email addresses for a few of you. 

→ If you've accepted an invite, you're good. ✅
→ If you've received an invite, please accept it. 🙏🏻
→ If you haven't received an invite, please mention your email addresses in the chat or send me a `Hi` [here](mailto:svsanketverma5@gmail.com) so I can add you to the group. ✉️

CC: @zarr-developers/steering-council 

Thank you for your time and efforts!

**Comment by jhamman** [comment]
Pinging this issue again because there is a pending core-dev nomination vote happening. Please chime in if you did not get the original invite / nomination email.
