### ISSUE TITLE
Release 2.16.0

### ISSUE THREAD

**Issue by rabernat** [zarr-developers/zarr-python#1456]
I would like to release 2.16.0 this week. Are there any other PRs folks would like to try to get in before then?

**Comment by d-v-b** [comment]
I'd like to get these three in: 
https://github.com/zarr-developers/zarr-python/pull/1323
https://github.com/zarr-developers/zarr-python/pull/1305
https://github.com/zarr-developers/zarr-python/pull/1299

I'm not sure how hard it will be to rebase; I might open new PRs if it's too onerous.

**Comment by rabernat** [comment]
Great. How can I help?

**Comment by d-v-b** [comment]
take a look at #1457 -- that's a fresh black / ruff effort. I'll start moving on the testing refactor.

**Comment by jakirkham** [comment]
Yes
