### ISSUE TITLE
remove bsddb3

### ISSUE THREAD

**Issue by d-v-b** [zarr-developers/zarr-python#1464]
We have [tests](https://github.com/zarr-developers/zarr-python/blob/aa5db9f7ea688c392bd2036fd3f64516059a695b/zarr/tests/test_core.py#L2088) that attempt to import [`bsddb3`](https://pypi.org/project/bsddb3/). I couldn't run these tests because I could not get `bsddb3` to install (because the project is dead). The `bsddb3` project page recommends using the [`berkeleydb`](https://pypi.org/project/berkeleydb/), but I couldn't get that to install either (on my m2 mac).

It seems that, at a minimum, we should remove any attempt to import `bsddb3`, since it's dead. What should we replace it with, if anything?

**Comment by jakirkham** [comment]
Looking at the packaging situation, it appears there is [a `bsddb3` package in `conda-forge`]( https://github.com/conda-forge/bsddb3-feedstock ), which are built for several OSes & architectures including macOS ARM. There is also discussion about [adding `berkeleydb` to `conda-forge`]( https://github.com/conda-forge/staged-recipes/issues/22320 ). Don't see wheels for either

There were several of these added a while back in PR ( https://github.com/zarr-developers/zarr-python/pull/186 ), which are all pretty similar

Maybe it would be worth refactoring out one class that could handle any flavor of these (maybe taking an `open` function to use). Then we could keep the handful that are useful / testable and then point users wanting anything else to the refactored class. WDYT?

**Comment by joshmoore** [comment]
No objections to the refactoring, though it'd suggest a deprecation cycle.

Additional option would be to extract the class. My proposal for how to start on that if someone is interested is in https://github.com/zarr-developers/cookiecutter-zarr-store

**Comment by dstansby** [comment]
See https://github.com/zarr-developers/zarr-python/issues/904#issuecomment-2564286978
