### ISSUE TITLE
Allow setting of `write_empty_chunks` for `zarr.core.Array` objects

### ISSUE THREAD

**Issue by RKuttruff** [zarr-developers/zarr-python#1478]
When opening a Zarr group via `zarr.hierarchy.open_group()` there is currently no way to specify `write_empty_chunks=False`, this can be problematic when appending to existing zarr groups with sparse data as found in pydata/xarray#8009 / pydata/xarray#8016. A simple solution to this would be setting `write_empty_chunks=False` for `Array` objects as they are retrieved from the group. Or, perhaps, allowing the user to specify their preference for `write_empty_chunks` for `Array`s in the group when opening/getting the individual `Array`s from the group.

**Comment by joshmoore** [comment]
cc: @jni

**Comment by d-v-b** [comment]
Thanks @RKuttruff, I have felt this problem acutely. 

One fundamental challenge for `zarr-python` is the friction between a) dynamic options for accessing arrays (like `read_only`, and `write_empty_chunks`, among others) and b) the `MutableMapping` API used by zarr groups to represent their contents. As long as we support `array = group['my_array']`, it's hard to figure out where a user can provide the dynamic options.

As a stopgap, we should make these dynamic options correspond to settable properties of arrays, so users can modify the arrays after getting them from the group. I find this really distasteful, but it should work.

**Comment by jhamman** [comment]
I see there being two options for making this work given the current API. 

First, lean into using the state of the Array via setters:

```python
array = group['my_array']
array.write_empty_chunks = False
array[:] = ...
```

Second, utilize some sort of scoped config:

```python
with zarr.config.set(write_empty_chunks=False):
    array = group['my_array']
    array[:] = ...
```

Neither are perfect but I think I would lean toward the latter option if I had to.

**Comment by jhamman** [comment]
We're sorting this out for 3.0 over in #2409. I'm going to close this in favor of the more recent ticket.
