### ISSUE TITLE
zarr.group(meta_array=...) argument?

### ISSUE THREAD

**Issue by ivirshup** [zarr-developers/zarr-python#1484]
If `zarr.group` is able to create a group from a store, I think it would make sense for it to accept `meta_array` as an argument.

Though I'm a little unclear on what the intended difference in usage is between `zarr.group` and `zarr.Group` other than being able to pass `zarr.group` a string for `store`. But most other arguments are shared.

**Comment by joshmoore** [comment]
cc: @madsbk

**Comment by madsbk** [comment]
I think that is a good idea. 
`zarr.array` and `zarr.Array` takes a `meta_array` argument already

**Comment by jakirkham** [comment]
Also +1

**Comment by d-v-b** [comment]
Could the functionality of `meta_array` be achieved via a type annotation? e.g., if we parametrized zarr arrays over the type of the wrapped array, e.g. `foo_array = zarr.Array[cp.Array](...)`, and similarly for zarr groups? The advantage of doing this via a type annotation is that it exposes the array type to all the static typing machinery.

**Comment by madsbk** [comment]
> Could the functionality of `meta_array` be achieved via a type annotation? e.g., if we parametrized zarr arrays over the type of the wrapped array, e.g. `foo_array = zarr.Array[cp.Array](...)`, and similarly for zarr groups? The advantage of doing this via a type annotation is that it exposes the array type to all the static typing machinery.

I think this might work and would be cool! but let's investigate this in a new issue. 
@d-v-b could you open a new issue that propose changing `meta_array` everywhere?
