### ISSUE TITLE
[DOC] Update .readthedocs.yaml

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#1492]
Received via email:

Hello,
You are receiving this email because your Read the Docs project is impacted by an upcoming deprecation.

Read the Docs used to pre-install common scientific Python packages like scipy, numpy, pandas, matplotlib and others at system level to speed up the build process. However, with all the work done in the Python ecosystem and the introduction of "wheels", these packages are a lot easier to install via pip install and these pre-installed packages are not required anymore. If you have Apt package dependencies, they can be installed with [build.apt_packages](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-apt-packages).

With the introduction of our new "Ubuntu 20.04" and "Ubuntu 22.04" Docker images, we stopped pre-installing these extra Python packages and we encouraged users to install and pin all their dependencies using a requirements.txt file. We have already stopped supporting "use system packages" on these newer images.

We are removing the "use system packages" feature on August 29th. Make sure you are installing all the required dependecies to build your project's documentation using a requirements.txt file and specifying it in your .readthedocs.yaml.

Here you have an example of the section required on the .readthedocs.yaml configuration file:

```
python:
  install:
    - requirements: docs/requirements.txt
```

The content of docs/requirements.txt would be similar to:

```
scipy==1.11.1
numpy==1.25.2
pandas==2.0.3
matplotlib==3.7.2
```

We are sending you this email because you are a maintainer of the following projects that are affected by this removal. Either using "Use system package" checkbox in the Admin UI, or the config key python.sytem_packages or python.use_system_site_packages in your .readthedocs.yaml file:

 - [zarr](https://readthedocs.org/projects/zarr/)

Read more about this in our [Reproducible builds](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html) guide for more details.

cc: @MSanKeys963

**Comment by jakirkham** [comment]
Yeah I saw this email too. However when looking at `.readthedocs.yml` it wasn't clear that there was anything too change (perhaps they are referring to an old version of Zarr?)

Including the recent config below in case others can spot what is needed (or confirm things are fine):

https://github.com/zarr-developers/zarr-python/blob/6ed4d785db71d7087b276f0f6dc5b3f7cfedd7f1/.readthedocs.yaml#L1-L15

**Comment by jakirkham** [comment]
Maybe they are referring to this option on [the RTD Advanced Settings page]( https://readthedocs.org/dashboard/zarr/advanced/ ):

<img width="487" alt="Screenshot 2023-08-08 at 7 39 01 PM" src="https://github.com/zarr-developers/zarr-python/assets/3019665/7ec5da42-3005-4d08-bbab-0633ae489ea7">

I've unticked that box and started a new build. Let's see how it goes

**Comment by jakirkham** [comment]
That seemed to work. Also emptied this "Requirement file" field as it is redundant with the config

<img width="574" alt="Screenshot 2023-08-08 at 7 44 27 PM" src="https://github.com/zarr-developers/zarr-python/assets/3019665/bcf47d40-ea91-45ac-a700-b69f0cb321ae">

Started [a new build]( https://readthedocs.org/projects/zarr/builds/21552914/ ), which also seems to work

**Comment by MSanKeys963** [comment]
Thanks for opening the issue, @joshmoore, and going through this, @jakirkham.

When I saw this, I realised we'd already fixed the dependency issue when we migrated to `pyproject.toml` via #1158.

Is it safe to close this now?

**Comment by jakirkham** [comment]
Think it would be nice to move these requirements to `pyproject.toml` ( https://github.com/zarr-developers/zarr-python/pull/1494 ) as [Numcodecs did]( https://github.com/zarr-developers/numcodecs/blob/d667b31ebe7e8a49f8be6adb15e32c30e957487a/pyproject.toml#L49-L54 )
