### ISSUE TITLE
[v3] CI ENH: Add testing with the development version of dependencies

### ISSUE THREAD

**Issue by bsipocz** [zarr-developers/zarr-python#1496]
Nightly wheels of development version of core scientific python libraries are built and distributed, and downstream is strongly encouraged to use these as part of their standard CI, and then report issues upstream.

more context https://scientific-python.org/specs/spec-0004/ as well as here https://numpy.org/devdocs/dev/depending_on_numpy.html#testing-against-the-numpy-main-branch-or-pre-releases

**Comment by jhamman** [comment]
This would be nice to include as part of the 3.0 release when we get there.
