### ISSUE TITLE
Add dimension_names key to V3 array_metadata

### ISSUE THREAD

**Issue by jhamman** [zarr-developers/zarr-python#1516]
The V3 spec included a new array metadata field ([`dimension_names`](https://zarr-specs.readthedocs.io/en/latest/v3/core/v3.0.html#dimension-names)) to specify the names of the axes corresponding to each dimension in an array. This field should be added to the Array constructor and related utilities.

**Comment by tasansal** [comment]
@jhamman I'll take a stab at this. Can you elaborate on what the "related utilities" are?

**Comment by jhamman** [comment]
@tasansal - we may want to hold on this until some internal refactors land on #1290. We are currently exploring the best path to bringing this library up to spec and are considering pulling in some of the internal work sitting in [Zarritta](https://github.com/scalableminds/zarrita). That lib already has the dimension names attribute so if we pull the V3Array class over, this will come for free.

**Comment by jhamman** [comment]
Closing as this is now done on the v3 branch. See https://github.com/zarr-developers/zarr-python/pull/1583 for more context on the v3 effort.

p.s. @tasansal - would be happy to get your 👀 on the above design doc.
