### ISSUE TITLE
Feature request: add a close() method

### ISSUE THREAD

**Issue by pgunn** [zarr-developers/zarr-python#1544]
In most cases, h5py and zarr have the same APIs, to the extent that it's usually possible to write code that looks at file extensions to do a one-line open with the right library, and the handles are nearly interchangable (at least for the codebases I maintain).

There's one annoying difference - zarr's handles don't have a close() method, making the most reasonable way to portably do this to `del` the variable instead, which looks ugly and has some problems of its own.

It'd be great if zarr-python's handles had a close() method too.

**Comment by d-v-b** [comment]
@pgunn in what situation do you find yourself needing to `del` zarr objects?

**Comment by pgunn** [comment]
Because there's no close(), if I want to serialise/move/rename or hand one off to another process, I want to get the python process to close any file handles and stop thinking about the object, same as hdf5 (and most other file types people use if they're careful).

**Comment by d-v-b** [comment]
zarr doesn't retain any file handles, so there's no need to use `del` or `close` to serialize a zarr object to another process

**Comment by pgunn** [comment]
That may be the case, but it would be nice to provide an identical API to h5py, which does.

**Comment by d-v-b** [comment]
so it looks like the `BaseStore` class does define [`close`](https://github.com/zarr-developers/zarr-python/blob/1ed37f5fa7039cbc8849bf9b0e9aae9c890e7ced/zarr/_storage/store.py#L84). I think the store classes are analogous to h5py's `File` objects. Does this work for you?

**Comment by pgunn** [comment]
That should do.

I think it'd still be nice for zarr.open() to be pairable with a close, because that's what most users will find and use, but I'll revise our code to use BaseStore or something in that family instead. Thanks.

**Comment by d-v-b** [comment]
Perhaps part of the issues stems from the fact that `zarr.open()` returns a `Group` or `Array` (analogous to `Group` and `Dataset` in `h5py`), but it's the `.store` property of that `Group` / `Array` which has the `.close` method; however, in`h5py` you _first_ create a `h5py.File`, and then use that to get your `Group` / `Dataset`, and so the first thing you create (the `File`) is also the thing you can call `close` on. I agree that the symmetry of the `h5py` approach is nicer than what we are doing with `zarr.open()`, which I think has been optimized for convenience more than anything else.

**Comment by pgunn** [comment]
Ah, I see. Yes, that makes sense; I didn't dig very deep into zarr-python and only over this discussion did I notice what zarr.open() actually returns (we work with a lot of different software packages; our use of them tends to be very goal-oriented because attention is scarce).

Thanks for the chat; glad I got a solution out of this.
