### ISSUE TITLE
Resolve Mypy errors in `v3` branch

### ISSUE THREAD

**Issue by jhamman** [zarr-developers/zarr-python#1593]
The `v3` branch needs some Mypy attention. As expected, our port of the zarrita code (see https://github.com/zarr-developers/zarr-python/pull/1584) has left a number of mypy errors that would be great to resolve.

This ticket can be closed when:

- [x] we have CI running against the `v3` codebase
- [x] we have zero mypy errors when checked in a github action

Marking this as _help-wanted_!

**Comment by jhamman** [comment]
This is feeling like a fairly high priority to start ticking off. For now, I've disabled the mypy checks in pre-commit (#1649) but this should be a short lived state.

**Comment by DahnJ** [comment]
I wanted to get into zarr a little and this issue had "help wanted" tag, so I picked it up here: https://github.com/zarr-developers/zarr-python/pull/1692

I made a few choices in fixing some of the issues, hope it helps more than adds noise 🙂

**Comment by jhamman** [comment]
closed by https://github.com/zarr-developers/zarr-python/pull/1692 and lots more work by @dstansby. See https://github.com/zarr-developers/zarr-python/issues/1783 for ongoing work on this topic.
