### ISSUE TITLE
h5py compatibility in v3 

### ISSUE THREAD

**Issue by jhamman** [zarr-developers/zarr-python#1597]
Zarr-Python currently supports most of the h5py API in groups/arrays. As part of #1583, we've decided to break this to clean up the core API going forward.

Going forward, h5py compatibility could be provided in a set of wrapper classes.

Marking this as _help-wanted_!

**Comment by joshmoore** [comment]
@clbarnes' https://github.com/clbarnes/h5py_like might be something to look at.

**Comment by clbarnes** [comment]
Yes, I'd hope that would do most of the heavy lifting! Was written a while ago so might need some updates but we'll see if/ when it gets used.
