### ISSUE TITLE
Remove attrs from V3

### ISSUE THREAD

**Issue by normanrz** [zarr-developers/zarr-python#1624]
In zarrita, I used attrs and cattrs for structuring the metadata and (de)serialization. However, it would be desirable to have less dependencies in zarr-python (see https://github.com/zarr-developers/zarr-python/pull/1583/files#r1420168951). We can use dataclasses instead and implement our own (de)serialization methods.

**Comment by jhamman** [comment]
xref: https://github.com/zarr-developers/zarr-python/discussions/1625
