### ISSUE TITLE
Not possible to submit minor feature requests (e.g. doc improvements)

### ISSUE THREAD

**Issue by dstansby** [zarr-developers/zarr-python#1682]
### Zarr version

n/a

### Numcodecs version

n/a

### Python Version

n/a

### Operating System

n/a

### Installation

n/a

### Description

When I go to open a new issue, there's no option for minor feature requests that don't need to be part of the zarr spec. For example, I currently want to open a suggestion to improve the docs by adding a new section to the tutorial, but there isn't really a sensible option for me to click on when I open a new issue:

![Screenshot 2024-02-27 at 14 23 15](https://github.com/zarr-developers/zarr-python/assets/6197628/b9b39c23-de65-44f6-9219-3d45a99a3eae)

### Steps to reproduce

n/a

**Comment by joshmoore** [comment]
Thanks for the heads up, @dstansby, and sorry for the confusion. The bit you want is the blank issue at the bottom:

<img width="401" alt="image" src="https://github.com/zarr-developers/zarr-python/assets/88113/38a8c765-8243-428c-8574-4b8cdb6d8037">

**Comment by dstansby** [comment]
Ah thanks!

**Comment by rabernat** [comment]
I agree @dstansby that this template needs to be changed. I opened an issue about that as well at some point but I can't find the link anywhere...
