### ISSUE TITLE
Duplicate name: '.zattrs' when saving to ZipStore

### ISSUE THREAD

**Issue by jwrth** [zarr-developers/zarr-python#1695]
### Zarr version

2.16.1

### Numcodecs version

0.11.0

### Python Version

3.9.18

### Operating System

Windows

### Installation

pip install zarr

### Description

Hi,

when I write a `zarr.zip` file using `ZipStore` and try to stepwise add new key and value pairs to `.attrs` I get a UserWarning and end up with multiple `.zattrs` files where each represents the state of the object after each manipulation event. If I write to a normal zarr directory, this does not happend and I end up with one `.zattrs` file containing all keys and values as I would expect.

Any ideas how to solve this? Thanks a lot in advance!

Best,
Johannes

### Steps to reproduce

```Python
import zarr
with zarr.ZipStore("testout.zarr.zip", mode="a") as zipstore:
    store = zarr.open(zipstore, mode="a")
    store.attrs["foo"] = "heyho"
    store.attrs["test"] = "check"

```

Error:
```Python
[\lib\zipfile.py:1514](file:/lib/zipfile.py:1514): UserWarning: Duplicate name: '.zattrs'
  return self._open_to_write(zinfo, force_zip64=force_zip64)
```

**Comment by MSanKeys963** [comment]
Hi @jwrth, thanks for opening the issue.

The ZipStore does not allow the modification, removal, or replacement of its contents. To achieve your goal, you should use a [DirectoryStore](https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.DirectoryStore) and then Zip all the files together.

Read more about ZipStore here: https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.ZipStore

**Comment by jwrth** [comment]
Dear @MSanKeys963, thanks a lot for your answer! Ok this explains why the old `.zattrs`s are not removed. It helped to first collect all attributes that I wanted to add in one dictionary and then add this dictionary using the `.put` function:

```Python
with zarr.ZipStore("/path/to/file", mode='w') as zipstore:
   store = zarr.open(zipstore, mode="a")
   store.attrs.put(dictionary)
```

**Comment by rossbar** [comment]
I just ran into this too - the documentation is quite clear but focuses specifically on arrays - IMO `attrs` are a special case because `.attrs[k] = v` is likely the most common practice, and having multiple attrs per array is likely not uncommon either (certainly not for my use-cases!). Perhaps the `.attrs` could be handled lazily? Either way, I think it's at least worth documenting the `attrs` case specifically and providing the workaround of using `.put` or `.update` to avoid the issue.
