### ISSUE TITLE
[v3] `LocalStore__eq__`

### ISSUE THREAD

**Issue by d-v-b** [zarr-developers/zarr-python#1744]
Right now, `LocalStore('tmp') == LocalStore('tmp')` is `False`. I think this should evaluate to `True`; fixing it requires implementing `__eq__` on [LocalStore](https://github.com/zarr-developers/zarr-python/blob/76c345071db950b2362f7588ad20da4a1af03b85/src/zarr/v3/store/local.py#L48). 

This would be good issue for anyone interested in working on v3 stuff.

**Comment by TahsinAyman** [comment]
I'm interested in contributing to this Project. but I could not find the class `LocalStore`.

**Comment by d-v-b** [comment]
[`LocalStore`](https://github.com/zarr-developers/zarr-python/blob/76c345071db950b2362f7588ad20da4a1af03b85/src/zarr/v3/store/local.py#L48) is in the [v3 branch](https://github.com/zarr-developers/zarr-python/tree/v3)

**Comment by jhamman** [comment]
closed by https://github.com/zarr-developers/zarr-python/pull/1792
