### ISSUE TITLE
[v3] Support numcodecs via entrypoints 

### ISSUE THREAD

**Issue by jhamman** [zarr-developers/zarr-python#1750]
This ticket tracks ensuring that Numcodecs can be used in Zarr-Python 3. The upstream issue is here: https://github.com/zarr-developers/numcodecs/issues/502.

**Comment by jhamman** [comment]
@normanrz - can you provide an update here?

**Comment by normanrz** [comment]
Just requested a review on the open PR in numcodecs.

**Comment by normanrz** [comment]
The PR in numcodecs is pretty close now: https://github.com/zarr-developers/numcodecs/pull/524

**Comment by dstansby** [comment]
Can this be closed as done now the numcodecs code is merged and released?
