### ISSUE TITLE
[v3] Deprecate stores that we don't expect to include in v3

### ISSUE THREAD

**Issue by jhamman** [zarr-developers/zarr-python#1756]
Following #1274, we expect the v3 release to include a smaller subset of stores. Specifically:

- MemoryStore
- DirectoryStore
- ZipFileStore
- FsspecStore

The thought is to move everything else to another library or, deprecate entirely.

As a first step, we should mark stores that we expect to move out of this library as deprecated and provide a discussion issue where we can direct users of those stores to.

TODOs here:

- [ ] deprecate existing stores
- [ ] open discussion issue
- [ ] make at least one Zarr-Python release ahead of the 3.0 release with this deprecation warning
- [ ] last step, remove existing stores

**Comment by d-v-b** [comment]
this is happening in #1791

**Comment by joshmoore** [comment]
Thanks for pushing this, guys. I find it unfortunate that the stores weren't in their own modules since I'd very much for keeping their git history. I'd be inclined even with the mega module to use a filter branch to populate the new repositories.

**Comment by jhamman** [comment]
> Thanks for pushing this, guys. I find it unfortunate that the stores weren't in their own modules since I'd very much for keeping their git history. I'd be inclined even with the mega module to use a filter branch to populate the new repositories.



@joshmoore - its not too late to do this. I'd fully support someone taking this on.

**Comment by joshmoore** [comment]
>it's not too late to do this.

definitely! :+1:
