### ISSUE TITLE
[V3] mypy not running properly in CI

### ISSUE THREAD

**Issue by d-v-b** [zarr-developers/zarr-python#1788]
I'm seeing the following output in CI in the v3 branch, under the `run mypy` stage:
```
Run hatch run test:run-mypy
─────────────────────────── test.py3.10-1.24-minimal ───────────────────────────
/bin/sh: 1: mypy: not found
Error: Process completed with exit code 127.
```

Nonetheless, GHA reports this stage as succeeding :upside_down_face: Maybe because 127 is not one of the exit codes it considers a failure. However I think we can consider this test a failure. How should we fix this?

cc @dstansby

**Comment by jhamman** [comment]
I believe the discussion in #1789 ended with us a) adding mypy to the test env (useful for dev workflows) and b) concluding that we don't need to run mypy in our test action in addition to the pre-commit check. So to close this issue out, we just need to remove the mypy check from the test github action.
