### ISSUE TITLE
[v3] Files created during tests

### ISSUE THREAD

**Issue by d-v-b** [zarr-developers/zarr-python#1812]
Running the [dimension separator tests](https://github.com/zarr-developers/zarr-python/blob/v3/tests/v2/test_dim_separator.py) in `v3` results in a directory called `src/fixture` being created, which is not the correct thing for a test to be doing. Files generated for testing should be written to temporary directories. We should change `test_dim_separator` so that it does not write these files.

The files being written come from [this fixture](https://github.com/zarr-developers/zarr-python/blob/0f755cc02e5b501cc99c25a31ec69ee0dbacbbff/tests/v2/test_dim_separator.py#L32). I don't really understand what this fixture is doing, since it takes `tmpdir`, but contains a branch that ignores `tmpdir` and tries to write array data to a hard-coded path in the project directory, if that path is empty. It looks like it's trying to reference [these files](https://github.com/zarr-developers/zarr-python/tree/v3/fixture)? If those files are static test fixtures, then should we move them to the tests directory, and remove the capacity for the pytest fixture in `test_dim_separator.py` to overwrite those fixtures?

@joshmoore do you have any ideas here?

**Comment by d-v-b** [comment]
I found a few more examples of this pattern: https://github.com/search?q=repo%3Azarr-developers%2Fzarr-python+.resolve%28%29&type=code

I feel like if these tests _can_ work with data generated at testing time, then that's preferable to a hard-coded fixture, in which could we replace the logic for locating the project root with a `tmpdir` fixture?

**Comment by joshmoore** [comment]
These aren't temporary files. These are the fixture that are expected to exist. They are getting created, more or less to keep conda-forge (and first time fixture developers) happy. There are extended conversations around this on the feedstock. See https://github.com/zarr-developers/zarr-python/issues/1347

**Comment by d-v-b** [comment]
I'm trying to wrap my head around that issue you linked @joshmoore, maybe I don't understand enough about the conda feedstock process, but why can't we just put these fixture files in the directory with the tests?

**Comment by joshmoore** [comment]
Because then they need to be present after `pip install`.

**Comment by joshmoore** [comment]
conda-forge expects all tests to pass when installed "out of tree".

**Comment by d-v-b** [comment]
but if the fixtures are moved inside the test suite, then aren't they available if and only if the tests are available?

**Comment by d-v-b** [comment]
we have been running all our tests in v3 out of tree for a while now...

**Comment by d-v-b** [comment]
@normanrz  #1890 resulted in fixture files being accidentally added to `src/zarr/fixture`, which I think underscores the need to resolve this issue.

To summarize the situation: our test suite generates fixture files, but it does not save them in a temporary directory. To resolve this, I think we need to choose between two options: 

- those files are generated during test time and stored in a temporary directory.
- those files are loaded during test time and stored in the test suite as static assets. 

I prefer the first option, because clearly the files can be dynamically generated, but I will accept anything short-term that keeps these files from being generated in `src/zarr` every time we run the test suite. See https://github.com/zarr-developers/zarr-python/pull/1813 for an implementation of the second option.
