### ISSUE TITLE
NumPy 2.0 support

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-python#1818]
NumPy 2.0 is coming out soon ( https://github.com/numpy/numpy/issues/24300 ). NumPy 2.0.0rc1 packages for conda & wheels came out 3 weeks back ( https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 )

To prepare for NumPy 2.0, it might be worthwhile to start testing against NumPy 2 in CI

NumPy has put out [a migration guide]( https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide ). More details are in [the release notes]( https://numpy.org/devdocs/release/2.0.0-notes.html )

Also as NumPy is tracking ecosystem support for NumPy 2.0, it would be helpful to share Zarr's current support status in issue (with any plans): https://github.com/numpy/numpy/issues/26191

**Comment by jakirkham** [comment]
This will depend on migrating Numcodecs: https://github.com/zarr-developers/numcodecs/issues/521

**Comment by jhamman** [comment]
@jakirkham - do you want to try to drop in numpy==2 to the test matrix on the v3 branch here: https://github.com/zarr-developers/zarr-python/blob/096c900a76d08eb6bde86f5583eda697781710c8/pyproject.toml#L115

**Comment by jakirkham** [comment]
Fixed in the Zarr 2.x line with the PR linked below in 2.18.0

* https://github.com/zarr-developers/zarr-python/pull/1842

Also fixed in Zarr 3.x with the PR linked below

* https://github.com/zarr-developers/zarr-python/pull/1828

Closing as completed
