### ISSUE TITLE
Enable v3 branch builds on readthedocs

### ISSUE THREAD

**Issue by dstansby** [zarr-developers/zarr-python#1836]
In the version selection at https://zarr.readthedocs.io/en/latest/ it looks like the v3 branch isn't enabled - it would be good to enable it so it's easy to see what the v3 docs look like as it's developed.

**Comment by jhamman** [comment]
We should be ready to get started on this once #1884 goes in.

**Comment by jhamman** [comment]
@zarr-developers/steering-council - can you activate builds on the `v3` branch. (see also https://github.com/zarr-developers/zarr-python/issues/1905)

**Comment by joshmoore** [comment]
Done. https://zarr.readthedocs.io/en/v3/ is now active though the version number looks odd.

![image](https://github.com/zarr-developers/zarr-python/assets/88113/541e9242-b04b-4c3d-ae84-13894bf4f8ae)
