### ISSUE TITLE
Ruff conflicts with pep8

### ISSUE THREAD

**Issue by normanrz** [zarr-developers/zarr-python#1841]
In this PR #1839 I have a conflict where the @pep8speaks bot is in conflict with the ruff formatter.
PEP8 comment: https://github.com/zarr-developers/zarr-python/pull/1839#issuecomment-2094937391
Ruff pre-commit: https://results.pre-commit.ci/run/github/48049137/1715025400.r2onHl8LSX240CJ0_K4lOw

The difference is illustrated in this commit: https://github.com/zarr-developers/zarr-python/pull/1839/commits/d8b5ca7748f0d1a0bcb049aa414aac4bdbc2d876

**Comment by jhamman** [comment]
@MSanKeys963  - I don't have privileges to turn off pep8speaks here. Can you do that for us?

**Comment by MSanKeys963** [comment]
Hi @jhamman. I just checked, and my privileges are the same as yours and ZP core developers.
@joshmoore, can you help us here?

**Comment by joshmoore** [comment]
Here are the installed apps:

![image](https://github.com/zarr-developers/zarr-python/assets/88113/11c2354f-0893-41d8-b1c7-bcb1c0502e87)


I've "suspended" pep8speaks. Let's see if that does the right thing.

At one of the first core devs meetings, let's go through permissions and set things up correctly.

**Comment by normanrz** [comment]
Thanks!
