### ISSUE TITLE
Support Blosc2 codec

### ISSUE THREAD

**Issue by eschnett** [zarr-developers/zarr-python#1896]
Zarr supports the Blosc library as a codec https://zarr-specs.readthedocs.io/en/latest/v3/codecs/blosc/v1.0.html . Blosc is now somewhat outdated, and a successor Blosc2 exists. It would be nice if Blosc2 was supported as a codec as well.

Since both the APIs and the container (on-disk) formats changed between Blosc and Blosc2, it might be best to support Blosc2 as a new codec.

Is this a good idea? How would I go about proposing this officially? At the technical level, I assume that actually writing the specification and opening a pull request would be a step towards receiving feedback?

**Comment by jhamman** [comment]
There are some active threads on the subject already:

- https://github.com/zarr-developers/numcodecs/issues/413
- https://github.com/zarr-developers/zarr-python/issues/713

Okay if we close this in favor of those open issues?

**Comment by MSanKeys963** [comment]
Also adding https://github.com/zarr-developers/numcodecs/pull/463 to the list.

**Comment by dstansby** [comment]
I'm going to re-open this, because I was going to request support for blosc2 in Zarr too. I'm not sure whether this depends on adding blosc2 to numcodecs or not, but even if it does it would be good to keep this issue open to disucss the ability to use it directly in zarr-python.

**Comment by d-v-b** [comment]
In the interest of relaxing our numcodecs dependency, I would be interested in supporting it _without_ adding it to numcodecs
