### ISSUE TITLE
v3 arrays have no `.name` attribute

### ISSUE THREAD

**Issue by rabernat** [zarr-developers/zarr-python#1924]
V2 arrays have a `.name`: https://zarr.readthedocs.io/en/stable/_autoapi/zarr.core.Array.html#zarr.core.Array.name

V3 arrays don't:

```python
import zarr
arr = zarr.Array.create(store=zarr.store.MemoryStore(), shape=(10,), chunks=(5,), dtype="i4")
arr.name
# attribute error
```

It would be a pretty disruptive API change to remove this.

**Comment by jhamman** [comment]
I've started implementing this. PR coming soon.
