### ISSUE TITLE
v3 arrays have no `.chunks` attribute

### ISSUE THREAD

**Issue by rabernat** [zarr-developers/zarr-python#1925]
Similar to: https://github.com/zarr-developers/zarr-python/issues/1924

V2 arrays have a `.chunks` attribute: https://zarr.readthedocs.io/en/stable/_autoapi/zarr.core.Array.html#zarr.core.Array.chunks

V3 arrays don't:

```python
import zarr
arr = zarr.Array.create(store=zarr.store.MemoryStore(), shape=(10,), chunks=(5,), dtype="i4")
arr.chunks
# -> attribute error

# instead it is available at
arr.metadata.chunk_grid.chunk_shape
```

It would be a pretty disruptive API change to remove this. I understand that the ChunkGrid concept makes this more complicated to support. We should reimplement a sane default for this attribute for regular chunk grids. So much code likely relies on this parameter.

**Comment by jhamman** [comment]
👍 - we've discussed this. A bit of thought will be needed for how to handle other chunk grids (as you say) but for now, we should just pass `arr.metadata.chunk_grid.chunk_shape` as a property of the array.
