### ISSUE TITLE
v3 Arrays should support `get_block_selection`

### ISSUE THREAD

**Issue by rabernat** [zarr-developers/zarr-python#1926]
The `array.get_block_selection` capability was added in https://github.com/zarr-developers/zarr-python/issues/991. (See https://zarr.readthedocs.io/en/stable/tutorial.html#block-indexing) It's likely that users may be relying on this. It's useful.

We should consider reimplementing this in the V3 API.

**Comment by normanrz** [comment]
Fixed by #1917
