### ISSUE TITLE
Finish v3 API reference docs

### ISSUE THREAD

**Issue by dstansby** [zarr-developers/zarr-python#1993]
In https://github.com/zarr-developers/zarr-python/pull/1918 I added structure for generating API docs, but only added the `zarr` namespace. We should add the other namespaces that need documenting too.

Does someone more involved in `v3` have a list of which sub-modules should be added to the API docs?

**Comment by d-v-b** [comment]
If we are auto-generating content, then I would say we add everything to start, and then remove things later as needed.
