### ISSUE TITLE
[v3] Release 3.0.0.alpha.1

### ISSUE THREAD

**Issue by jhamman** [zarr-developers/zarr-python#2008]
We've landed some important fixes to the v3 branch in the past two weeks. I'd like us to make another alpha release soon (perhaps on Monday July 8th?). 

The following PRs seem close and good candidates to get in before the next release:

- https://github.com/zarr-developers/zarr-python/pull/1967
- https://github.com/zarr-developers/zarr-python/pull/1982
- https://github.com/zarr-developers/zarr-python/pull/2000
- https://github.com/zarr-developers/zarr-python/pull/2006

Plus @dstansby has some good additions to the docs in flight:

- https://github.com/zarr-developers/zarr-python/pull/2002
- https://github.com/zarr-developers/zarr-python/pull/2003

@brokkoli71, @normanrz, @dstansby, @d-v-b, and @akshaysubr - does this sound reasonable and/or am I missing anything here?

**Comment by dstansby** [comment]
👍 sounds good to me
