### ISSUE TITLE
Incorrect version on main docs page

### ISSUE THREAD

**Issue by martindurant** [zarr-developers/zarr-python#2016]
### Zarr version

current

### Numcodecs version

NA

### Python Version

NA

### Operating System

NA

### Installation

NA

### Description

The current state of the docs front page:

<img width="1007" alt="Screenshot 2024-07-05 at 10 07 56" src="https://github.com/zarr-developers/zarr-python/assets/6042212/667e9e00-0d26-492e-9e61-372fe4715a23">

### Steps to reproduce

Go to https://zarr.readthedocs.io/en/stable/

**Comment by joshmoore** [comment]
Thanks, @martindurant. Unifying on #2012 after #1986 did so.... Think we need to get this fixed ;)

**Comment by dstansby** [comment]
This is still an issue :(

**Comment by joshmoore** [comment]
Thanks for the continued hammering on this, @dstansby!

**Comment by dstansby** [comment]
Woop woop, this is fixed now: https://zarr.readthedocs.io/en/stable/

**Comment by joshmoore** [comment]
Yeah!
