### ISSUE TITLE
auto chunks

### ISSUE THREAD

**Issue by d-v-b** [zarr-developers/zarr-python#2019]
At the moment, if you attempt to call `Array.create` without specifying `chunks` or `chunk_shape`, a `ValueError` is raised. But I think we should allow automatically creating chunks if the chunks are not specified. In the short term we can use the same heuristic that zarr v2 uses, and in the longer term we could consider making this behavior a configuration point.

**Comment by jhamman** [comment]
This should be easy to port from v2.

**Comment by d-v-b** [comment]
this is implemented in https://github.com/zarr-developers/zarr-python/pull/2042

**Comment by d-v-b** [comment]
closed by #2042
