### ISSUE TITLE
allow `null` attributes

### ISSUE THREAD

**Issue by d-v-b** [zarr-developers/zarr-python#2024]
We currently error if the `attributes` field of `zarr.json` is missing. We should handle this instead of erroring.

reported by @joshmoore 

Edit: data was originally written by tensorstore

**Comment by jhamman** [comment]
👍 TIL that `attributes` is indeed optional in the v3 metadata doc.

**Comment by d-v-b** [comment]
yeah, my preference would be for it not to be optional, since an empty object sufficiently conveys "no attributes" 🤷 I will get a fix out for this soon.
