### ISSUE TITLE
allow missing 'configuration' in chunk_key_encoding

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#2025]
Similar to #2024, the "configuration" key of `chunk_key_encoding` is optional. If it's missing, a ValueError is raised:

```
  File "/Users/jamoore/opt/challenge/zarr-python/src/zarr/common.py", line 130, in parse_named_configuration
    raise ValueError(f"Named configuration does not have a 'configuration' key. Got {data}.")
ValueError: Named configuration does not have a 'configuration' key. Got {'name': 'default'}.
```

cc: @d-v-b 

Edit: data was originally written by tensorstore

**Comment by joshmoore** [comment]
```
diff --git a/src/zarr/common.py b/src/zarr/common.py
index 342db141..1534fa16 100644
--- a/src/zarr/common.py
+++ b/src/zarr/common.py
@@ -127,6 +127,7 @@ def parse_named_configuration(
     if "configuration" in data:
         configuration_parsed = parse_configuration(data["configuration"])
     elif require_configuration:
+        return name_parsed, {}
```
works around the immediate issue

**Comment by d-v-b** [comment]
yes that would be an immediate fix. longer term we should remove `parse_named_configuration` and replace it with something like `parse_chunk_key_encoding`, `parse_chunk_grid`, etc, that each can handle a `NamedConfiguration` as input.

**Comment by joshmoore** [comment]
The same testing for https://github.com/zarr-developers/zarr-python/issues/2029 applies:

 * this error was occurring with 3.0.0a0
 * but *not* with 3.0.0b1

:tada:
