### ISSUE TITLE
[v3] Missing array attributes: nbytes, nchunks, nchunks_initialized

### ISSUE THREAD

**Issue by tomwhite** [zarr-developers/zarr-python#2027]
### Zarr version

3.0.0a1

### Numcodecs version

0.12.1

### Python Version

3.11.9

### Operating System

Mac

### Installation

pip

### Description

The array attributes `nbytes`, `nchunks`, and `nchunks_initialized` are all missing in v3.

### Steps to reproduce

```python
>>> import zarr.v2 as zarr
>>> z = zarr.open(store='example-v2.zarr', mode='w', shape=(3, 2))
>>> z.nbytes, z.nchunks, z.nchunks_initialized
(48, 1, 0)
>>> import zarr
>>> z = zarr.open(store='example-v3.zarr', mode='w', shape=(3, 2))
>>> z.nbytes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Array' object has no attribute 'nbytes'
>>> z.nchunks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Array' object has no attribute 'nchunks'. Did you mean: 'chunks'?
>>> z.nchunks_initialized
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Array' object has no attribute 'nchunks_initialized'
```

**Comment by d-v-b** [comment]
`nbytes` and `nchunks` should be easy, but i'm wondering if / how we should implement `nchunks_initialized`, since this triggers a lot of IO.

**Comment by d-v-b** [comment]
@tomwhite how essential is `nchunks_initialized` for your usage?

**Comment by tomwhite** [comment]
> @tomwhite how essential is `nchunks_initialized` for your usage?

It's not as important as the other two, but we use it in Cubed to see if an array has been fully computed when resuming a computation after a restart. Currently we don't need to know how many chunks have been initialized, only if any haven't been - in which case we'll recompute them all. So an API like the one mentioned in https://github.com/zarr-developers/zarr-specs/issues/300#issuecomment-2204768992 for TensorStore would be sufficient.

**Comment by d-v-b** [comment]
so my personal view is that "what's going on with my chunks" is a very important question and zarr-python should provide basic tools with which people can answer that question, _and_ making `nchunks_initialized` an array attribute gives the false impression that this is a cheap quantity to represent accurately, which it is not. So for me the easiest thing would be to spin `nchunks_initialized` off into a standalone function in `array.py`, with a docstring that explains the caveats and whatnot. Would that work for Cubed?

**Comment by tomwhite** [comment]
> Would that work for Cubed?

Yes, thanks

**Comment by d-v-b** [comment]
while we are at it, `chunks_initialized(array) -> tuple[chunk_identifier]` seems a bit better than `nchunks_initialized(array) -> int`. Something to think about when this PR gets opened.
