### ISSUE TITLE
[v3] Missing `array` method on groups

### ISSUE THREAD

**Issue by tomwhite** [zarr-developers/zarr-python#2028]
### Zarr version

3.0.0a1

### Numcodecs version

0.12.1

### Python Version

3.11.9

### Operating System

Mac

### Installation

pip

### Description

There is no [`Group.array`](https://zarr.readthedocs.io/en/stable/api/hierarchy.html#zarr.hierarchy.Group.array) method in v3, which is a fairly common way of creating nested arrays.

### Steps to reproduce

```python
>>> import numpy as np
>>> import zarr.v2 as zarr
>>> a = np.arange(100000000).reshape(10000, 10000)
>>> root = zarr.group()
>>> root.array("a", a)
<zarr.v2.core.Array '/a' (10000, 10000) int64>
>>> import zarr
>>> root = zarr.group()
>>> root.array("a", a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Group' object has no attribute 'array'. Did you mean: 'arrays'?
```

**Comment by d-v-b** [comment]
this functionality is handled by [`Group.create_array`](https://github.com/zarr-developers/zarr-python/blob/b8baa6868c8fa95e6b2948c9fd9c725331ca23ec/src/zarr/group.py#L323) (that's the async function, which is wrapped by a method with the same name on the synchronous group class)

**Comment by tomwhite** [comment]
It's an incompatible change - and it doesn't allow the data to be passed in to the function.

**Comment by d-v-b** [comment]
noted. my personal view is that `create_array` is a better name for this routine than `array` and so long-term that function should be what people use, and I do think `create_array` should be changed to take a `data` parameter. As a stop-gap measure for v2 compatibility, perhaps we could implement `SyncGroup.array` as a wrapper around `SyncGroup.create_array`, with a loud deprecation warning? Not sure what the deprecation window should be.

thoughts @jhamman ?

**Comment by rabernat** [comment]
I strongly favor not breaking existing public Zarr API with the V3 release as much as feasible. Doing so will make users unhappy. Yes the API may be too broad. So let's deprecate things carefully, rather than releasing breaking changes.

**Comment by d-v-b** [comment]
@tomwhite I started working on this [over here](https://github.com/d-v-b/zarr-python/tree/array_on_group). Feel free to weigh in on that branch, or on the PR it will become in a few days.
