### ISSUE TITLE
pytest is an unnecessary dependency?

### ISSUE THREAD

**Issue by TomAugspurger** [zarr-developers/zarr-python#2068]
### Zarr version

main

### Numcodecs version

na

### Python Version

na

### Operating System

na

### Installation

na

### Description

https://github.com/zarr-developers/zarr-python/blob/064b2e09b188b8e09536fb327d2c0f5fe8492f2b/pyproject.toml#L35 has pytest as a required dependency (note that this isn't as an dev-only extras dependency).

Looks like that was added in https://github.com/zarr-developers/zarr-python/pull/1785. It wasn't discussed, so it was presumably intended to be a dev-only dependency.

Slightly related, but would you be open to defining `tool.hath.envs.test` as a standard optional dependency? https://github.com/zarr-developers/zarr-python/blob/064b2e09b188b8e09536fb327d2c0f5fe8492f2b/pyproject.toml#L106 https://hatch.pypa.io/latest/config/environment/overview/#features recommends doing something like

```
[tool.hatch.envs.test]
features = [
  "test",
]
```

which should work for both.

### Steps to reproduce

na

**Comment by d-v-b** [comment]
we need pytest because of [this class](https://github.com/zarr-developers/zarr-python/blob/v3/src/zarr/testing/store.py)

**Comment by TomAugspurger** [comment]
Thanks. I see that the `__init__` guards against pytest missing: https://github.com/zarr-developers/zarr-python/blob/064b2e09b188b8e09536fb327d2c0f5fe8492f2b/src/zarr/testing/__init__.py#L4-L7. So maybe the intended behavior is to just not have that class be importable if pytest isn't installed?

**Comment by d-v-b** [comment]
> . So maybe the intended behavior is to just not have that class be importable if pytest isn't installed?

This seems right! (@jhamman feel free to issue a correction here).

**Comment by jhamman** [comment]
Pytest should not be a required dependency so +1 to removing it.
