### ISSUE TITLE
Store ABC doesn't match spec

### ISSUE THREAD

**Issue by dcherian** [zarr-developers/zarr-python#2104]
### Zarr version

irrelevant

### Numcodecs version

irrelevant

### Python Version

irrelevant

### Operating System

irrelevant

### Installation

irrelevant

### Description

https://zarr-specs.readthedocs.io/en/latest/v3/core/v3.0.html#abstract-store-interface lists `erase_values` and `erase_prefix` which are not present in https://github.com/zarr-developers/zarr-python/blob/v3/src/zarr/abc/store.py.

Also `erase` has been renamed to `delete`. it would be good to update one of the two so that both are consistent.

### Steps to reproduce

irrelevant

**Comment by jhamman** [comment]
I opened https://github.com/zarr-developers/zarr-specs/issues/307 to clarify that the ABC and the spec need not match. However, we should add the `erase_*` methods (or something similar).

**Comment by jhamman** [comment]
I'm going to close this in favor of the work in the spec repo to clarify the abstract store interface. I'll open a new issue with erase/delete/rename store methods.
