### ISSUE TITLE
Odd, very late Codecov comments

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-python#2138]
Not sure what is up here, but am seeing Codecov comment on PRs that are quite literally years old

Here's one example from PR: https://github.com/zarr-developers/zarr-python/pull/1023

<img width="1840" alt="Screenshot 2024-08-28 at 5 46 07 PM" src="https://github.com/user-attachments/assets/46757e3e-43d3-4ff9-87ce-006989794aeb">

Do we know what is going on here?

**Comment by joshmoore** [comment]
I do not. I commented underneath a few of them as well, flabbergasted.

**Comment by jhamman** [comment]
I posted a bug report here: https://github.com/codecov/feedback/issues/497

**Comment by jakirkham** [comment]
Thanks Joe! 🙏

Was wondering if there was a setting we changed that may have inadvertently triggered a Codecov bug

In any event, agree it is best to follow up with upstream. Thanks again for starting that process 🙏

**Comment by joshmoore** [comment]
> Was wondering if there was a setting we changed that may have inadvertently triggered a Codecov bug

Not that I know of.


> I posted a bug report here: [codecov/feedback#497](https://github.com/codecov/feedback/issues/497)


:+1:

**Comment by jhamman** [comment]
These seem to have died down (and the codecov team is now looking into this). Closing.
