### ISSUE TITLE
`storage_transformers` are not an accepted keyword for ArrayV3Metadata

### ISSUE THREAD

**Issue by mpiannucci** [zarr-developers/zarr-python#2178]
### Zarr version

3.0.0a3

### Numcodecs version

0.13.0

### Python Version

3.11.9

### Operating System

Mac

### Installation

pip install

### Description

The zarr v3 Array metadata spec specfies the `storage_transformers` key can exist, but zarr crashes when reading a buffer that includes the `storage_transformers` key, even as an empty list: 

```TypeError: ArrayV3Metadata.__init__() got an unexpected keyword argument 'storage_transformers'```

### Steps to reproduce

```python
import json
import zarr

metadata = json.loads("""{
  "zarr_format": 3,
  "node_type": "array",
  "shape": [
    10
  ],
  "data_type": "int64",
  "chunk_grid": {
    "name": "regular",
    "configuration": {
      "chunk_shape": [
        10
      ]
    }
  },
  "chunk_key_encoding": {
    "name": "default",
    "configuration": {
      "separator": "/"
    }
  },
  "fill_value": 0,
  "codecs": [
    {
      "name": "bytes",
      "configuration": {
        "endian": "little"
      }
    }
  ],
  "storage_transformers": null,
  "dimension_names": null,
  "attributes": {
    "foo": 101
  }
}""")

metadata = zarr.core.array.parse_array_metadata(metadata)
```

**Comment by d-v-b** [comment]
sorry about that! although we don't have any code in `zarr-python` right now that can actually do anything with a storage transformer, we should support that key in metadata. #2180 aims to fix this.

**Comment by mpiannucci** [comment]
Awesome thank you!

**Comment by jhamman** [comment]
yeah - thanks @d-v-b for hopping right on this :)
