### ISSUE TITLE
Default to a RemoteStore for (some) string `StoreLike`

### ISSUE THREAD

**Issue by TomAugspurger** [zarr-developers/zarr-python#2195]
### Zarr version

v3

### Numcodecs version

n/a

### Python Version

n/a

### Operating System

n/a

### Installation

n/a

### Description

Zarr v2 users (either direct, or indirect through libraries like xarray) probably relied on the ability to pass an fsspec URI to `zarr.open` and have it work with a remote file system. Is there any tolerance for trying to interpret some string `store` arguments as an argument to `RemoteStore` rather than `LocalFile`? For example:

```python
zarr.open_group("s3://hrrrzarr")
```

would be interpreted as

```python
zarr.open_group(zarr.store.RemoteStore("s3://hrrrzarr"))
```

We'd also need to expose `storage_options` in all the API endpoints that create a `Store` / `StorePath` from user input, to allow customizing the filesystem that's created.

### Steps to reproduce

```python
import zarr

g = zarr.open_group(store="s3://hrrrzarr", storage_options={"anon": False})
```

**Comment by d-v-b** [comment]
> Is there any tolerance for trying to interpret some string store arguments as an argument to RemoteStore rather than LocalFile? For example:

Definitely! In the short term, we should copy what v2 was doing, modulo the storage classes. Longer term, I would like to consider a few things in this direction:
- expose a URI attribute on stores, groups and arrays.
- set up a scheme: store class registry
