### ISSUE TITLE
zarr file load of gcp climate data fails with "SSL: CERTIFICATE_VERIFY_FAILED"

### ISSUE THREAD

**Issue by klaus-upgrata** [zarr-developers/zarr-python#2226]
It works on Windows and Linux. The python package requests works fine with SSL. 

       zstore = 'gs://cmip6/CMIP6/ScenarioMIP/NCAR/CESM2-WACCM/ssp585/r5i1p1f1/day/tasmax/gn/v20200206/'
        mapper = self.gcs.get_mapper(zstore)
        # open it using xarray and zarr
        ds: xr.Dataset = xr.open_zarr(mapper, consolidated=True)

Fails with:
_request out of retries on exception: Cannot connect to host storage.googleapis.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
Traceback (most recent call last):
  File "/Users/klausfabian/Upgrata/climate/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1080, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by klaus-upgrata** [comment]
Seems to be python apple xcode homebrew whatever problem. Sigh. They say you should use requests :(
https://openradar.appspot.com/7111585

**Comment by jhamman** [comment]
Hi @klaus-upgrata -

Would you mind opening a new issue with the details in the bug report template: https://github.com/zarr-developers/zarr-python/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

This will help us point you in the right direction. On the surface, this seems like more of a Fsspec issue but happy to take a look.

**Comment by klaus-upgrata** [comment]
The issue is resolved. It seems to be related how asyncio is installed of Mac Silicon Python. The certificates directory is configured incorrectly and no HTTPS request works - unless it is through requests. I don't know who's fault it is but I wouldn't think the fault of zarr library.
