### ISSUE TITLE
Add documentation for `zarr.array`

### ISSUE THREAD

**Issue by MSanKeys963** [zarr-developers/zarr-python#2245]
xref: #2215

This issue tracks the documentation progress for the [`zarr.array`](https://github.com/zarr-developers/zarr-python/blob/v3/src/zarr/core/array.py) module. We'll be focusing on adding docstrings and code samples to the functions.

Progress:

- [ ] docstrings
- [ ] code samples

**Comment by e-marshall** [comment]
I'll start working on this, if anyone else also is, maybe we can coordinate on which parts of the module we're working on?

**Comment by MSanKeys963** [comment]
Hi @e-marshall!
I'm also working on this. Which functions are you working on?

**Comment by MSanKeys963** [comment]
This is completed via #2276 and #2281. Thanks, all!
Closing this.
