### ISSUE TITLE
Add documentation for `zarr.api.synchronous`

### ISSUE THREAD

**Issue by MSanKeys963** [zarr-developers/zarr-python#2248]
xref: #2215

This issue tracks the documentation progress for the [`zarr.api.synchronous`](https://github.com/zarr-developers/zarr-python/blob/v3/src/zarr/api/synchronous.py) module. We'll be focusing on adding docstrings and code samples to the functions.

Progress:

- [ ] docstrings
- [ ] code samples

**Comment by jhamman** [comment]
closed by #2549
