### ISSUE TITLE
Bad title contrast in dark theme in docs

### ISSUE THREAD

**Issue by dstansby** [zarr-developers/zarr-python#2285]
Go to https://zarr.readthedocs.io/en/stable/ and switch to the dark theme:

<img width="476" alt="Screenshot 2024-10-01 at 17 52 43" src="https://github.com/user-attachments/assets/d4bc2145-7ddb-4ca6-bb4b-3fa27845b594">

**Comment by d-v-b** [comment]
a lot of things bug me about the styling here! what knobs can we turn in sphinx to make this better?
