### ISSUE TITLE
Installation fails on Python 3.13

### ISSUE THREAD

**Issue by veenstrajelmer** [zarr-developers/zarr-python#2317]
### Zarr version

latest

### Numcodecs version

latest

### Python Version

3.13

### Operating System

Windows

### Installation

pip install zarr

### Description

Installation fails

### Steps to reproduce

`pip install zarr` in a Python 3.13 environment

### Additional output

Also reported at numcodecs: https://github.com/zarr-developers/numcodecs/issues/593

**Comment by veenstrajelmer** [comment]
The entire traceback is included in the linked numcodecs issue. I did not test beyond numcodecs, so I am not sure whether there will be a zarr-specific problem after this is resolved. However, since zarr cannot be installed because of this I thought it would be useful to have a zarr issue also. But feel free to close as won't do if there is indeed nothing zarr-specific in this installation failure.

**Comment by veenstrajelmer** [comment]
@TomAugspurger After the release of numcodecs 0.13.1, `pip install zarr` works again. I would like to suggest to add python 3.13 to the ci and supported versions, but feel free to close this issue you think otherwise.

**Comment by TomAugspurger** [comment]
Thanks. Let's keep this open for those tasks.

**Comment by jhamman** [comment]
I think we can close this following #2344.
