### ISSUE TITLE
[v3] V2 Codec pipeline is not consistent with legacy usage of `filters`

### ISSUE THREAD

**Issue by mpiannucci** [zarr-developers/zarr-python#2325]
### Zarr version

3.0.0a8

### Numcodecs version

0.13.0

### Python Version

3.11

### Operating System

Mac

### Installation

pip in virtual environment

### Description

I am reading a kerchunk reference filesystem as a zarr v2 store with zarr python. The entire reference file is attached, but an example `.zarray` is as follows: 

```json
    {
        "shape": [
            1
        ],
        "fill_value": null,
        "zarr_format": 2,
        "order": "C",
        "filters": [
            {
                "id": "zlib",
                "level": 2
            }
        ],
        "dimension_separator": ".",
        "compressor": null,
        "chunks": [
            1
        ],
        "dtype": "<i4"
    }
```

Notably, the `filters` contains `zlib` which is a `BytesBytesCodec` in zarr-python v3+. The issue comes, when we look at the codec pipeline created for V2 arrays: https://github.com/zarr-developers/zarr-python/blob/9bce89006aa55d76ac80d0abcf132cd1e04048cb/src/zarr/core/array.py#L105-L113

This defines the pipeline as two codecs, `filters` and `compressor`. The problem here is that `V2Filters` is defined as a `ArrayArrayCodec` and `V2Compressor` is defined as a `ArrayBytesCodec`. Because of this, all codecs defined in the metadata as `filters` are expected to be `ArrayArrayCodecs` and applied once the buffer is translated to an array. Further, the `compressor` can only define one codecs that is an `ArrayBytesCodec`, which leaves no place to define a `BytesBytesCodec` in v2 metadata. 

With the current `.zarray` above, the pipeline crashes because the `zlib` codec outputs bytes and not an array as is expected.

[test_dict.json](https://github.com/user-attachments/files/17317599/test_dict.json)

cc @jhamman @martindurant 

### Steps to reproduce

```bash
pip install git+https://github.com/TomAugspurger/zarr-python@xarray-compat git+https://github.com/TomAugspurger/xarray/@fix/zarr-v3
```

```python
import json
import fsspec
import xarray as xr
import zarr

test_dict = json.load('test_dict.json')
fs = fsspec.implementations.reference.ReferenceFileSystem(fo=test_dict, remote_options=remote_options)
store =  zarr.storage.RemoteStore(fs, mode="r")

# This will crash in the codec pipeline
ds = xr.open_dataset(store, engine="zarr", zarr_format=2, backend_kwargs=dict(consolidated=False))
```

**Comment by jhamman** [comment]
also cc @normanrz who knows the v2 pipeline path the best

**Comment by normanrz** [comment]
Thanks for reporting this. I wasn't aware, that zarr-python 2 worked with using compressors, such as `zlib`, as filter. That will need some workarounds in zarr-python 3.

**Comment by martindurant** [comment]
In v2, there is no conceptual difference between filters and codecs. To reiterate, the pipeline actually run is `filers + ([] if compression is None else [compression])`, at least in python. This is why the numcodecs classes don't specify if they are compression, or bytes-to-bytes or whatever, but they take and produce "buffers" which may be numpy or bytes/memoryview.

**Comment by rabernat** [comment]
Should we bring this API back to V3 as a convenience / compatibility layer?

We could inspect the arguments to filters + compressors and translate them into a proper V3 codec pipeline.

**Comment by d-v-b** [comment]
i'm not sure it is generally possible to map a v2 `([filters], compressor)` setup into v3, but we could define a v2-specific codec pipeline that places no restrictions on the order of its contents, and otherwise adheres to the same protocol (i.e., the same behavior) as the v3 codec pipeline. I can't wait to see if someone tries to back-port sharding into v2 using this mechanism.

**Comment by rabernat** [comment]
In terms of breaking API changes, this is one of the biggest ones from V2 to V3. Folks who depend on zarr python have existing code that creates compressors and filters.

> i'm not sure it is generally possible to map a v2 `([filters], compressor)` setup into v3

We could try!
```python
codecs = [v2_to_v3_codec(filt) for filt in filters] + [v2_to_v3_codec(compressor)]
```

> I can't wait to see if someone tries to back-port sharding into v2 using this mechanism.

Let's leave that out of scope.

**Comment by martindurant** [comment]
> codecs = [v2_to_v3_codec(filt) for filt in filters] + [v2_to_v3_codec(compressor)]

(with check for filters or compressor being None)

This will work. If there's some dataset that defines these such that an array codec tries to act on the output of a bytes codec, we can warn maybe, and understand that they were relying on bytes buffers even where we think a codec produces arrays.

**Comment by jhamman** [comment]
closed by https://github.com/zarr-developers/zarr-python/issues/2325
