### ISSUE TITLE
Clean up non core branches, and require PRs to come from forks?

### ISSUE THREAD

**Issue by dstansby** [zarr-developers/zarr-python#2350]
While we're changing some of the branches around, I thought it might be a nice oppurtunity to clear out some old branches, and to keep this repository clean require that all pull request branches are made from forks (which is what folks without commit access have to do anyway). What do @zarr-developers/python-core-devs think?

There's about 20 branches that aren't `main`, `v3`, or `support/v2`. Of these:

- Some are marked as being merged in a PR, so we can delte them safely (I think?)
- A handful are old (> 5 years) by @alimanfoo with no assosciated PR. @alimanfoo, can we delete these branches?
- Otherwise there are two un-merged branches from @normanrz, which we could leave until they're merged (or decided not to merge)

**Comment by jhamman** [comment]
+1 on cleaning these up. GitHub soft deletes branches now so I think anything that a) isn't attached to an open PR or b) hasn't moved in > 1yr can be deleted without major risk.

**Comment by jhamman** [comment]
I've gone ahead and cleaned up most of the super-stale branches. There are a few active ones from @d-v-b and @normanrz that I left around for now.
