### ISSUE TITLE
[v3] It is possible to create v3 data with features not currently written into the spec (dtypes, codecs, etc.)

### ISSUE THREAD

**Issue by jhamman** [zarr-developers/zarr-python#2411]
### Zarr version

3.0.0.beta

### Numcodecs version

0.13

### Python Version

3.11

### Operating System

Mac

### Installation

pip

### Description

We have discussed adding a warning when writing data to `zarr_format=3` that is outside the current spec. Currently, this mostly applies to data types and codecs but also includes stores (e.g. `ZipStore`).

**Comment by normanrz** [comment]
This we need to put warnings on
- variable length string/bytes codecs and dtype
- consolidated metadata

numcodecs codecs already report a warning
