### ISSUE TITLE
Clean up number of versions on readthedocs

### ISSUE THREAD

**Issue by dstansby** [zarr-developers/zarr-python#2415]
There's a lot of doc versions available on readthedocs, and it would be nice to slim these down. I think a good start would be to just keep the last version of every 2.x release (e.g., drop 2.3.0, 2.3.1, and keep 2.3.2). I'm not sure who has permissions on readthedocs, but I would be happy to do this if someone can give me the right permissions.

<img width="285" alt="Screenshot 2024-10-19 at 20 23 15" src="https://github.com/user-attachments/assets/b0eab828-0bee-4be0-8b59-ba538554f9f4">

**Comment by TomAugspurger** [comment]
If possible, it'd be nicer to just hide these from the version UI to avoid breaking links pointing to those URLs.

**Comment by dstansby** [comment]
Looks like that's possible by [changing the versions to hidden](https://docs.readthedocs.io/en/stable/versions.html#version-states), which hides them from the version switcher and search engines, but keeps the links alive.

**Comment by jhamman** [comment]
I've added everyone on @zarr-developers/python-core-devs (that had an account) as maintainers on read the docs (including @dstansby )

**Comment by dstansby** [comment]
I've:

- Hidden micro versions as suggested in the top comment
- Removed the `2.5.0` build, because there's a `v2.5.0` build too which I assume is the real docs
- Removed the `latest` build, because it was duplicating `main` (and I think `main` is a clearer indication that it's a development branch IMO, but happy to switch the other way)
- Added a `support/v2` build so we can see what the dev version of the v2 docs looks like

**Comment by jhamman** [comment]
> Removed the latest build, because it was duplicating main (and I think main is a clearer indication that it's a development branch IMO, but happy to switch the other way)

I reverted this change as I know of a few downstream projects that link to `latest` via intersphinx.

xref: https://github.com/pydata/xarray/pull/9652#event-14755144845

**Comment by dstansby** [comment]
Woops, thanks for fixing that!
