### ISSUE TITLE
Comprehensive docstrings for all top-level exports

### ISSUE THREAD

**Issue by d-v-b** [zarr-developers/zarr-python#2475]
Very few of the [top-level functions](https://github.com/zarr-developers/zarr-python/blob/498cb788b29900183dbcfd7633c48afd5cee8a95/src/zarr/__init__.py#L37-L67) have doctrings. This is bad and we should fix it, either by writing good docstrings from scratch or dynamically copying docstrings from other functions where appropriate.

**Comment by jhamman** [comment]
Huh! Most of the top level API functions should have docstrings. We copy these from the asynchronous API: 

https://github.com/zarr-developers/zarr-python/blob/498cb788b29900183dbcfd7633c48afd5cee8a95/src/zarr/api/synchronous.py#L292-L316

But looking at the docs page, this doesn't seem to be working as expected. Let's definitely fix this.

**Comment by VjayRam** [comment]
Hey @d-v-b, I'm willing to contribute to this issue. Is it still open?

**Comment by jhamman** [comment]
The issue is still open. There is some question about why our auto-api sphinx plugin is not picking up our docstrings. @dstansby and I noticed this again today. Some exploration on the sphinx configuration side would be where I would start here.

**Comment by dstansby** [comment]
I think this is a drawback of using https://sphinx-autoapi.readthedocs.io/en/latest/ for automatically creating the API docs - because it never imports the code, it only knows about docstrings that are "hard coded" into the source files, not docstrings that are modified at import time.

**Comment by d-v-b** [comment]
should we copy + paste the docstrings then (and maybe add a test that ensures that these should-be-copied docstrings are in fact identical between the source function and the derived function?)

**Comment by dstansby** [comment]
copy/pasting identical docstrings doesn't seem like fun in terms of long term maintenance.

Couple of potential other options I can see:

- Wrap funcitons with [`functools.wraps`](https://docs.python.org/3/library/functools.html#functools.wraps), and maybe `autoapi` will pick up that the docstring should be copied across? If not, we could open an upstream issue for this, I think it would be reasonable for `autoapi` to do this.
- Use [`sphinx-automodapi`](https://github.com/astropy/sphinx-automodapi) instead
- Drop automatic api documentaiton, and document stuff more manually.

**Comment by d-v-b** [comment]
> copy/pasting identical docstrings doesn't seem like fun in terms of long term maintenance.

Hm, I thought this would mostly be a one-time chore. If we have tests that enumerate over pairs of functions and ensure that their docstrings match, then the long term maintenance seems low? E.g., If someone modifies the docstring for func `foo`, but they fail to make the same changes to func `foo_but_sync`, then the tests would fails and they would do a 1-time copy + paste. 

Another plus is that "use a real docstring" is the only solution that puts a real, accurate docstring in the static source code of the project, which should be our goal IMO.

**Comment by dstansby** [comment]
FWIW I tried the functools.wraps idea and it doesn't seem to work with autoapi.

👍 I see the benefits of having docstrings next to the code - as long as they're robustly tested to make sure they don't get out of sync.
