### ISSUE TITLE
Missing `packaging` dependency

### ISSUE THREAD

**Issue by TomAugspurger** [zarr-developers/zarr-python#2487]
### Zarr version

v3

### Numcodecs version

na

### Python Version

na

### Operating System

na

### Installation

na

### Description

https://github.com/zarr-developers/zarr-python/blob/main/src/zarr/codecs/zstd.py#L10C6-L10C15 import `packaging`, but it's not in our pyproject.toml.

### Steps to reproduce

na

**Comment by d-v-b** [comment]
thanks for flagging this, I also ran into this problem (I assumed I had done something to break my dev environment)
