### ISSUE TITLE
Why is `Array.name` nullable?

### ISSUE THREAD

**Issue by d-v-b** [zarr-developers/zarr-python#2498]
The name of an array can be `None`, which is a bit odd since `None` is not a valid location in a file system. Can someone explain what we are expressing by allowing `Array.name` to be `None`? Note that this is carried over from v2, and the docstring references h5py.

https://github.com/zarr-developers/zarr-python/blob/d6508b57332d8af829b1b399708561a8903e7c45/src/zarr/core/array.py#L813-L827

**Comment by d-v-b** [comment]
My next question is, what would we lose by using the empty string '' instead of `None` for this case?

**Comment by d-v-b** [comment]
I did some quick research and apparently in hdf5, the name of a dataset or a group can be `NULL` if the array / group is an anonymous group, i.e. a group / dataset has _not_ been added to an extant hierarchy, otherwise it should be a string. We have never supported this in `zarr-python`, So I don't think `zarr-python` v2 was correctly modelling hdf5's semantics here, and I don't think we should continue to incorrectly model hdf5.

see #2499

**Comment by jhamman** [comment]
closed by https://github.com/zarr-developers/zarr-python/pull/2499
