### ISSUE TITLE
UserWarning: Codec 'numcodecs.blosc' not configured in config

### ISSUE THREAD

**Issue by TomNicholas** [zarr-developers/zarr-python#2509]
When using zarr-python v3 (inside virtualizarr + icechunk) I got these warnings, which I have no idea how to prevent.

```
/Users/tom/miniconda3/envs/coiled/lib/python3.12/site-packages/zarr/core/metadata/v3.py:71: UserWarning: Codec 'numcodecs.blosc' not configured in config. Selecting any implementation.
  out += (get_codec_class(name_parsed).from_dict(c),)
/Users/tom/miniconda3/envs/coiled/lib/python3.12/site-packages/numcodecs/zarr3.py:94: UserWarning: Numcodecs codecs are not in the Zarr version 3 specification and may not be supported by other zarr implementations.
  warn(
```

The first one especially seems like I should be able to prevent it being emitted by setting some config, but the message doesn't tell me how to do that or where to look for further information. (If someone tells me where to find out I can submit a PR to improve the message.)

**Comment by normanrz** [comment]
For a bit of context, there is a config mechanism to select codec implementations if multiple implementations exist for the same codec. An example for that would be that there is the default blosc and a GPU-based blosc codec.

I think we can remove this message if only 1 implementation exists. @brokkoli71 could you take care of that?

@TomNicholas Why are you using the numcodecs.blosc instead of the in-zarr blosc?

**Comment by TomNicholas** [comment]
> Why are you using the numcodecs.blosc instead of the in-zarr blosc?

Ignorance? 😅 

Are you saying I could potentially fix this just by importing the codec from inside zarr instead of from numcodecs?

**Comment by normanrz** [comment]
Yes, I think you would just need to specify the blosc codec differently so that this class will be used: https://github.com/zarr-developers/zarr-python/blob/main/src/zarr/codecs/blosc.py#L87

**Comment by dstansby** [comment]
Is this fixed by https://github.com/zarr-developers/zarr-python/pull/2571?

**Comment by normanrz** [comment]
Yes 👍
