### ISSUE TITLE
ValueError: I/O operation on closed file.

### ISSUE THREAD

**Issue by DarshanSP19** [zarr-developers/zarr-python#2516]
### Zarr version

v2.16.1

### Numcodecs version

v0.11.0

### Python Version

v3.8.19

### Operating System

Linux

### Installation

using pip in to virtual env

### Description

```
zf = zarr.open(target)
with opener(url) as file:
    logger.info(f"Opened {url}")
    ds = xr.open_dataset(file, engine='cfgrib')
    for vname in vars:
        logger.info(f"Started {vname} from {url}")
        zv = zf[vname]
        zv[region] = ds[vname].values
        logger.info(f"Done {vname} from {url}")
    logger.info(f"Finished for {url}")
    del zv
    del ds
```

Above code snipped is giving `ValueError: I/O operation on closed file.` while running on Google `dataflow`. 

```
file = grib dataset downloaded from Google Storage Bucket.
target = zarr store located on Google Storage Bucket.
```

### Steps to reproduce

```
zf = zarr.open(target)
with opener(url) as file:
    logger.info(f"Opened {url}")
    ds = xr.open_dataset(file, engine='cfgrib')
    for vname in vars:
        logger.info(f"Started {vname} from {url}")
        zv = zf[vname]
        zv[region] = ds[vname].values
        logger.info(f"Done {vname} from {url}")
    logger.info(f"Finished for {url}")
    del zv
    del ds
```

**Comment by jhamman** [comment]
Hi @DarshanSP19 - Thanks for opening the issue. I'm noticing that you are using a fairly old version of Zarr/Python. Any chance you could try this with Zarr version 2.18.3 and report back? As it stands, without a reproducer with sample data, there's not much we can do here.

**Comment by DarshanSP19** [comment]
I tried using a newer version and it seems to be working. Closing the issue. Thanks @jhamman.
