### ISSUE TITLE
Clean up optional dependencies

### ISSUE THREAD

**Issue by dstansby** [zarr-developers/zarr-python#2539]
On the current main branch, there are "extra" and "optional" optional dependecy groups. These names aren't very descriptive, so over in https://github.com/zarr-developers/zarr-python/pull/2538 I wasn't sure how to documente them. It would be good if we moved or renamed these dependencies. Does anyone have any suggestions?

```toml
[project.optional-dependencies]
...
extra = [
    'msgpack',
]
optional = [
    'universal-pathlib>=0.0.22',
    'rich'
]
...
```

**Comment by d-v-b** [comment]
Do `msgpack`, `rich` or `universal-pathlib` interact in the codebase? I am guessing that they are pretty independent, which means that they probably shouldn't be grouped. Maybe one dependency group for each one is the way to address this?

**Comment by dstansby** [comment]
It looks like:
- `msgpack` is only used in the docs (?), so we can remove it from "extra" (and remove "extra")
- `universal-pathlib` is used once, so we can move to a "universal-pathlib" extra
- `rich` is only used for tree, so we can get rid of it from "optional"

How does that sound?
