### ISSUE TITLE
Only support tuple[int, int] for `ByteRangeRequest`s

### ISSUE THREAD

**Issue by maxrjones** [zarr-developers/zarr-python#2567]
> I don't think there should be two different ways to specify "the beginning of the buffer".

this also holds for `zarr-python` -- I think we currently use [`None` and `0` to express the same thing](https://github.com/zarr-developers/zarr-python/blob/775979fce31175149a35aee04f0f7b8cb29ab9a4/src/zarr/abc/store.py#L22), which should be fixed.

_Originally posted by @d-v-b in https://github.com/zarr-developers/zarr-python/issues/1661#issuecomment-2546026844_

Based on this discussion, `None` should not be supported as the `start` or `end` for `ByteRangeRequest`s.

**Comment by maxrjones** [comment]
I would be glad to work on this if helpful.

**Comment by d-v-b** [comment]
thanks for opening this issue! I think always using a non-negative int for the start of a byte range will work, but I'm not sure about the end -- I suspect `None` might be necessary to model an unknown size. Someone who knows the stores better than I do (cc @normanrz ) would have a better idea here.

**Comment by maxrjones** [comment]
> I think always using a non-negative int for the start of a byte range will work, but I'm not sure about the end -- I suspect None might be necessary to model an unknown size. 

Ah, this actually brings up a third scenario which might also motivate typing of tuple[int, int | None]. The [ObjectStore PR](https://github.com/zarr-developers/zarr-python/pull/1661) supports a suffix request with the [length indicated by a negative start value](https://github.com/kylebarron/zarr-python/blob/3aa35786b84344ad30389f32555bfa19872991e3/src/zarr/storage/object_store.py#L84-L85). Local store seems to [support this as well](https://github.com/zarr-developers/zarr-python/blob/775979fce31175149a35aee04f0f7b8cb29ab9a4/src/zarr/storage/local.py#L36-L39), with an additional possibility of a [negative end value](https://github.com/zarr-developers/zarr-python/blob/775979fce31175149a35aee04f0f7b8cb29ab9a4/src/zarr/storage/local.py#L40-L42). So in both cases negative values indicate the number of bytes from the end of the file. FsspecStore does not seem to support this.

I was really surprised to discover `ByteRangeRequest` is actually `[start, length]` rather than `[start, end]` given the [typical structure of range headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range). I think this will need to be very prominently documented for potential extensions (e.g., as far as I can tell https://github.com/zarr-developers/zarr-python/pull/1661 was written assuming `ByteRangeRequest` represents `[start, end]`).

**Comment by d-v-b** [comment]
We should minimize surprises here, so I would support normalizing our byte range convention to match what people expect

**Comment by maxrjones** [comment]
Darn, I'm sorry that I missed that this is a duplicate of https://github.com/zarr-developers/zarr-python/issues/2437. Let's continue any discussion there.
