### ISSUE TITLE
Array.nbytes logic is wrong

### ISSUE THREAD

**Issue by rabernat** [zarr-developers/zarr-python#2575]
### Zarr version

3.0.0.b2

### Numcodecs version

!

### Python Version

!

### Operating System

!

### Installation

!

### Description

This logic is obviously and embarrassingly wrong:

https://github.com/zarr-developers/zarr-python/blob/f035d453894ec83234f69f7627b540390ee2b6eb/src/zarr/core/array.py#L977-L982

### Steps to reproduce

Read the code

**Comment by d-v-b** [comment]
🤡
