### ISSUE TITLE
HTML jstree doesn't work in jupyter lab

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/zarr-python#259]
#### Problem description

When calling ``group.tree()`` in a jupyter notebook environment, an expandable tree should be rendered via jstree. This works in classical jupyter notebook but doesn't work in jupyter lab.

#### Version and installation information

* Value of ``zarr.__version__``: 2.2.0
* Jupyter Lab version: 0.32.1
* Version of Python interpreter: 3.6.5
* Operating system (Linux/Windows/Mac): Linux
* How Zarr was installed (e.g., "using pip into virtual environment", or "using conda"): conda

**Comment by jakirkham** [comment]
Can't find the exact issue, but JupyterLab apparently disallows inlining the `script` tag. So this is likely causing us issues. I'm not sure what the easiest solution is, but one option would be to rewrite this using ipywidgets. Maybe someone else knows a simpler option.

ref: https://github.com/jupyterlab/jupyterlab/issues/2710#issuecomment-316476443

**Comment by jakirkham** [comment]
Looks like PR ( https://github.com/jupyterlab/jupyterlab/pull/2595 ) is where inlined `script` tags got sanitized. A fair bit of discussion is happening in issue ( https://github.com/jupyterlab/jupyterlab/issues/3118 ) about whether this is a good idea and how best to address user expectations. Maybe this is one of those wait and see problems.

**Comment by alimanfoo** [comment]
Thanks @jakirkham, I [added a comment](https://github.com/jupyterlab/jupyterlab/issues/3118#issuecomment-387373986) re zarr.

**Comment by jakirkham** [comment]
Thanks for doing that @alimanfoo. :)

**Comment by jakirkham** [comment]
cc-ing @jasongrout (as we talked about this one in person ;), for advice on how we should fix this.

**Comment by jakirkham** [comment]
Maybe [this doc page]( https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html ) is useful? Not sure if those are the most up-to-date ones though.

**Comment by jakirkham** [comment]
Probably also worth looking at how XArray is approaching this. ( https://github.com/pydata/xarray/pull/1820 )

**Comment by jakirkham** [comment]
So one short-term option might be to add `_repr_json_`. This is something that JupyterLab knows how to display. That said, it does leave some things to be desired.

<img width="1089" alt="screen shot 2018-12-15 at 20 18 39" src="https://user-images.githubusercontent.com/3019665/50048949-ab4c8280-00a6-11e9-8cd5-7fdc2b8ea8c9.png">

**Comment by jakirkham** [comment]
It looks like QuantStack has been working on [ipytree]( https://github.com/QuantStack/ipytree ), which taken from the description states it is "a Tree Widget using Jupyter-widgets protocol and [jsTree]( https://www.jstree.com/ )". This seems pretty close to what we are looking for. Might be worth giving it a try.

**Comment by jakirkham** [comment]
FWIW I did a brief experiment with [ipytree]( https://github.com/QuantStack/ipytree ).

Here's [the notebook from it]( https://gist.github.com/jakirkham/aa9ffd9bf8cdca48db2c26334f5bfe74 ). If you install ipytree, it works great with both the Jupyter Notebook and JupyterLab.

Currently it doesn't render in nbviewer (or GitHub) though. Have raised issue ( https://github.com/QuantStack/ipytree/issues/8 ) on this point. Not sure how much of a blocker this is for us. Perhaps we can have our own fallback to mitigate this (maybe reusing our existing implementation)?

**Comment by jakirkham** [comment]
Reimplemented `.tree`'s representation using `ipytree`. Have added PR ( https://github.com/zarr-developers/zarr-python/pull/450 ) with a working implementation. Still need to update docs and get tests running on CI (though tests are written).
