### ISSUE TITLE
Make MemoryStore private?

### ISSUE THREAD

**Issue by dstansby** [zarr-developers/zarr-python#2598]
I noticed that [MemoryStore](https://zarr.readthedocs.io/en/latest/_autoapi/zarr/storage/index.html#zarr.storage.MemoryStore) is marked as

> for testing purposes

Does this mean it's not meant for user consumption? If so, should we make it a private part of the API in v3? Would be good to make a decision either way on this before v3, and if it's intended to be public the docstring should be updated to make it less ambiguous about whether it's intended just for internal use or not

**Comment by d-v-b** [comment]
MemoryStore should definitely be public, so the solution here is probably to amend the "for testing purposes" designation.
