### ISSUE TITLE
TFRecords to Zarr

### ISSUE THREAD

**Issue by phamnam95** [zarr-developers/zarr-python#281]
Hello.
I am trying to put all of my TFRecord files to Zarr. Are there any tutorials or suggestions on how to do it? Thanks

**Comment by jakirkham** [comment]
Is there a spec for `TFRecord`s somewhere?

**Comment by phamnam95** [comment]
I do not understand your question. What do you mean?

**Comment by phamnam95** [comment]
I do not have a TFRecord dataset right now. But I think there are plenty of TFRecord dataset in online tutorial. I will try to create one.

**Comment by alimanfoo** [comment]
I think if we just had an idea of what each record contained, that would be
helpful, i.e., a use case with a description of the data involved. I think
there will be a fairly simple transformation from a TFrecord to a zarr
group of arrays, but would be nice to check against something concrete.

**Comment by phamnam95** [comment]
Each record will contain a dictionary with image height, image width, image channel, image dtype, image name, and image value itself.

**Comment by jakirkham** [comment]
Does [this]( http://warmspringwinds.github.io/tensorflow/tf-slim/2016/12/21/tfrecords-guide/ ) match what you are thinking about?

**Comment by phamnam95** [comment]
Yes. It does. Do you have any suggestions?

**Comment by jakirkham** [comment]
Sounds like you want a Zarr Array. Would take a look at the [tutorial]( http://zarr.readthedocs.io/en/stable/tutorial.html ). Particularly would read about [persistent arrays]( http://zarr.readthedocs.io/en/stable/tutorial.html#persistent-arrays ). The height, width, and number of channels will be included in the `shape` attribute. The `dtype` will have type information. Name and value have pretty straightforward analogues. Feel free to ask more question if reading that or these suggestions are not sufficient.

**Comment by phamnam95** [comment]
Thanks. I will try to read it. I want something like h5py to store the tfrecords

**Comment by alimanfoo** [comment]
+1 on @jakirkham's comment. Also if you have multiple channels, you may have a choice about how to store them. If they all have the same dtype then you could combine into a single array as @jakirkham suggests. Althernatively you could store each channel as a separate array within a group. I don't know enough about tensorflow to know which approach is best. E.g., adapting the pascal voc example (untested):

```python
from PIL import Image
import numpy as np
import zarr
import os

# setup zarr persistent storage to local disk
store = zarr.DirectoryStore('/path/to/zarr/data')
root = zarr.group(store=store)

for img_path, annotation_path in filename_pairs:
    
    # create a group for data for this image, need a name, could be anything
    group_name = os.path.basename(os.path.splitext(img_path)[0])
    group = root.create_group(group_name)

    # load the image data
    img = np.array(Image.open(img_path))
    annotation = np.array(Image.open(annotation_path))

    # store images
    group.create_dataset('image', data=img)
    group.create_dataset('annotation', data=annotation)
    
```

**Comment by alimanfoo** [comment]
...and this is how you'd read back out again:

```python
import zarr

store = zarr.DirectoryStore('/path/to/zarr/data')
root = zarr.group(store=store)

for _, group in root.groups():

    # load as numpy arrays
    img = group['image'][:]
    annotation = group['annotation'][:]

```

**Comment by joshmoore** [comment]
@phamnam95: were you successful with this? I'd likely close just this issue, but if it's worthwhile, we could capture this as an example in the documentation.
