### ISSUE TITLE
Similar to h5py with zarr

### ISSUE THREAD

**Issue by phamnam95** [zarr-developers/zarr-python#282]
Are there any tutorials on how to create zarr group similar to h5py that can store features of multiple numpy arrays in one zarr file? (similar to this tutorial with h5py: http://machinelearninguru.com/deep_learning/data_preparation/hdf5/hdf5.html

**Comment by jakirkham** [comment]
Sure, take a look at [this section in the tutorial]( http://zarr.readthedocs.io/en/stable/tutorial.html#groups ).

**Comment by clbarnes** [comment]
You may also be interested in [z5py](https://github.com/constantinpape/z5/), which aims for a h5py-like interface for a subset of HDF5's features, although it's less mature than the core zarr.

**Comment by jrbourbeau** [comment]
I suspect the "Groups" sections of the tutorial answers the originally posted question. Probably safe to close this issue.

**Comment by jakirkham** [comment]
If you have more questions, please feel free to raise them.

**Comment by clbarnes** [comment]
In case anyone comes across this in future, and is interest in easily wrapping other libraries in h5py-like interfaces, here's a shameless plug for https://github.com/clbarnes/h5py_like , a library of ABCs which allow you to achieve that by implementing a minimal number of methods.

**Comment by jakirkham** [comment]
cc @axtimwalde @joshmoore (who may be happy to see `h5py_like`)
