### ISSUE TITLE
Zarr error when loading group

### ISSUE THREAD

**Issue by phamnam95** [zarr-developers/zarr-python#283]
I have the error: ValueError: codec not available: 'blosc' when open the group. Any suggestions how to fix?
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-f5d316dfbadf> in <module>()
----> 1 img = store.traindata['image'][:]

/usr/local/lib/python3.7/site-packages/zarr/hierarchy.py in __getitem__(self, item)
    326             return Array(self._store, read_only=self._read_only, path=path,
    327                          chunk_store=self._chunk_store,
--> 328                          synchronizer=self._synchronizer, cache_attrs=self.attrs.cache)
    329         elif contains_group(self._store, path):
    330             return Group(self._store, read_only=self._read_only, path=path,

/usr/local/lib/python3.7/site-packages/zarr/core.py in __init__(self, store, path, read_only, chunk_store, synchronizer, cache_metadata, cache_attrs)
    121 
    122         # initialize metadata
--> 123         self._load_metadata()
    124 
    125         # initialize attributes

/usr/local/lib/python3.7/site-packages/zarr/core.py in _load_metadata(self)
    138         """(Re)load metadata from store."""
    139         if self._synchronizer is None:
--> 140             self._load_metadata_nosync()
    141         else:
    142             mkey = self._key_prefix + array_meta_key

/usr/local/lib/python3.7/site-packages/zarr/core.py in _load_metadata_nosync(self)
    166                 self._compressor = None
    167             else:
--> 168                 self._compressor = get_codec(config)
    169 
    170             # setup filters

/usr/local/lib/python3.7/site-packages/numcodecs/registry.py in get_codec(config)
     33     cls = codec_registry.get(codec_id, None)
     34     if cls is None:
---> 35         raise ValueError('codec not available: %r' % codec_id)
     36     return cls.from_config(config)
     37 

ValueError: codec not available: 'blosc'

**Comment by martindurant** [comment]
Do you have blosc installed? Available on pypi or conda.

**Comment by phamnam95** [comment]
Is Zarr only supported for python 3.5 or above?

**Comment by phamnam95** [comment]
I installed blosc using pip install -U blosc

**Comment by jakirkham** [comment]
It's actually vendored in `numcodecs`. Have you installed `numcodecs`? It's a requirement of `zarr` so should already be installed. Just would like to check before proceeding further.

**Comment by phamnam95** [comment]
Ok. I installed numcodecs and the problem is solved now. Thanks

**Comment by jrbourbeau** [comment]
Glad to hear your issue was resolved @phamnam95. Is it safe to close this issue?

**Comment by jakirkham** [comment]
If any more issues come up, please feel free to raise a new issue.
