### ISSUE TITLE
Using a bot to manage requirement updates

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-python#322]
A fair bit of discussion on this in PR ( https://github.com/zarr-developers/numcodecs/pull/90 ).

Basically would be interesting to look into using a bot to update requirements. Though there are some potential issues that came up in our discussion. Namely indirect requirements being dropped or introduced that are not captured, incompatibilities introduced by updating to latest in all cases, etc.. One possible solution that came up is to track only direct requirements with some loss to reproducibility.

**Comment by joshmoore** [comment]
@jakirkham, I'm closing this based on https://github.com/zarr-developers/zarr-python/pull/734 but feel free to re-open if I'm mistaken.

**Comment by jakirkham** [comment]
Of course. Thanks Josh! 😄
