### ISSUE TITLE
Specifying chunks with an integer

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-python#364]
#### Minimal, reproducible code sample, a copy-pastable example if possible

```python
In [1]: import zarr                                                             

In [2]: z = zarr.zeros(shape=(4, 4), chunks=1)                                  

In [3]: z.chunks                                                                
Out[3]: (1, 4)
```

#### Problem description

When specifying chunks with an integer, initially thought this would behave the same way that Dask does (please see example below). Namely Zarr would apply this chunking for all dimensions. However it seems Zarr only applies this chunking to the first dimension and lets the rest of the dimensions have a chunk size that matches the shape for that dimension.

```python
In [1]: import dask.array as da                                                 

In [2]: a = da.zeros(shape=(4, 4), chunks=1)                                    

In [3]: a.chunksize                                                             
Out[3]: (1, 1)
```

#### Version and installation information

Please provide the following:

* Value of ``zarr.__version__``: 2.2.0
* Value of ``numcodecs.__version__``: 0.5.5
* Version of Python interpreter: 3.6.6
* Operating system (Linux/Windows/Mac): macOS
* How Zarr was installed (e.g., "using pip into virtual environment", or "using conda"): Using Conda

**Comment by jrbourbeau** [comment]
This still seems to be the case today:

```python
In [1]: import zarr                                                                                                                  

In [2]: zarr.__version__                                                                                                             
Out[2]: '2.3.3.dev4+dirty'

In [3]: z = zarr.zeros(shape=(4, 4), chunks=1)                                                                                       

In [4]: z.chunks                                                                                                                     
Out[4]: (1, 4)
```

I had the same initial thought as @jakirkham (i.e. Zarr would apply the same chunking for all dimensions). Is there consensus that specifying an integer for `chunks` should behave the same way as Dask? If so, I'm happy to submit a PR with these changes

**Comment by alimanfoo** [comment]
Sounds good to me that Zarr should behave the same way as Dask, a PR would be very welcome.
