### ISSUE TITLE
Handle change in dbm missing key deletion behavior

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-python#391]
In [CPython issue 33106]( https://bugs.python.org/issue33106 ), the behavior of handling the deletion of a key that does not exist has changed to raise `error` (defined in the specific module e.g. `dbm.error`) instead of `KeyError` or similar. We should make sure we are prepared for this change, which will be included in Python 3.8.

**Comment by jakirkham** [comment]
Sorry forgot to add this is specifically scoped to deletion in the read-only case. IDK if we want to do anything about that. Maybe just letting the error propagate is fine.

**Comment by alimanfoo** [comment]
Usually we raise `PermissionError` when someone tries to modify something that's read-only. But maybe in this case it's fine to propagate the `dbm.error`, sounds more trouble than it's worth to try and detect and convert the error appropriately.

**Comment by jhamman** [comment]
We've opted to deprecate the `DBMStore` so I'm going to close this now.
