### ISSUE TITLE
Change name of this repo to zarr-python?

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/zarr-python#407]
I wondering if it would be helpful to change the name of this repo from "zarr" to "zarr-python" to make it clear this repo is for work on the Python implementation of the zarr specs.

(Currently the specs still live in this repo, but the intention is to migrate those to the [zarr-specs](https://github.com/zarr-developers/zarr-specs) repo.)

**Comment by jakirkham** [comment]
That or `python-zarr` or `py-zarr`. Just to add a few other options to consider.

**Comment by jakirkham** [comment]
Related question: If we do rename this repo, how do we want to handle naming on PyPI and conda-forge?

**Comment by meggart** [comment]
Assuming you choose one of the options, would this also imply the naming convention for other language implementations, or would this still be free? 

In Julia we have the convention to do capitalize package names and let them end with .jl so that probably `Zarr.jl` would be the obvious choice (I called my attempt [`ZarrNative`](https://github.com/meggart/ZarrNative.jl) to separate it from a C-Wrapper that might come in the future). Other programming languages probably have their package naming best practises as well. 
On the other hand I think it would be nice to have a consistent package listing under the zarr umbrella, like 

* `python-zarr`
* `r-zarr`
* `julia-zarr`
* `c-zarr`
* ...

**Comment by jakirkham** [comment]
Thanks for mentioning these, @meggart. Another question that you lightly touch on is how do these libraries then relate to each other.

For instance with a C implementation, we may decide to bind many other implementations to the C library. Should those live in the same repo or across many? How do we name them?

Though there are (and may soon be more) mixed language implementations that are bound to different language implementations, but don't use C per se (e.g. C++ and Python, Rust and Python, etc.). How do these fit in this scheme?

Other implementations may be designed to be pure implementations in their respective language (e.g. Zarr now is pure Python). How should these be named in respect to the C bound libraries?

Finally there may be many ways to achieve the same goal. For instance there is a Zarr Scala implementation. This could be compiled to JavaScript. How do we acknowledge this in its naming (if at all)? What do we do if a JavaScript implementation of Zarr shows up?

**Comment by alimanfoo** [comment]
Thanks @meggart and @jakirkham for comments. This is a tricky one to see a solution that generalises well to all languages/implementations. However I would like to do something in the short term that at least makes it clear this repo is just for the pure Python implementation. 

Re naming in the Python space, there is no consistency. E.g., "msgpack-python" is the name of the github repo and of the conda package; however, the conda package for graphviz Python is "python-graphviz", and the conda package for Python arrow is "pyarrow".

I think I would prefer in general to use "zarr" as a prefix (rather than suffix) for both repo names and conda package names. So at least then there is consistency between github and conda names, and also the conda packages will all appear together in alphabetical listing. 

For this repo I think I prefer "zarr-python" for now at least.

If other languages tend to follow different conventions then I'd be happy to follow that. E.g., I'd be happy with "Zarr.jl" if that fits better with common practice in Julia community.

On the question of what we might do if at some point there is both a pure Python implementation and Python bindings to a C implementation, I propose we don't worry about that for now and cross that bridge when we come to it. 

Any objections to going with "zarr-python" for now?

**Comment by alimanfoo** [comment]
I've gone ahead with renaming this repo to zarr-python for now, but very happy to revisit if there are objections or consensus that there's a better option, either now or further down the line.

I've also transferred various issues which are not related to the Python implementation either to the [zarr-specs repo](https://github.com/zarr-developers/zarr-specs) or to a new [community repo](https://github.com/zarr-developers/community) that I've created.

**Comment by joshmoore** [comment]
Thanks, @alimanfoo

**Comment by jakirkham** [comment]
Should we rename this on Readthedocs or keep it the same? Could see reasonable arguments either way.
