### ISSUE TITLE
Sqlite store delete wrong array

### ISSUE THREAD

**Issue by potter420** [zarr-developers/zarr-python#439]
When there is multiple arrays in the same SqliteStore groups, if there exists 2 arrays named as follow: 'prefix', 'prefix_suffix.'
If there is a operation that overwrite on the array 'prefix', the array 'prefix_suffix' is removed too.

#### Minimal, reproducible code sample, a copy-pastable example if possible

```python
import zarr
import numpy as np

path = 'D:/test.db'
store = zarr.SQLiteStore(path)
group = zarr.open_group(store)
group.array('prefix', np.arange(1000))
group.array('prefix_suffix', np.arange(100))
group['prefix_suffix']
Traceback (most recent call last):
  Python Shell, prompt 3, line 1
    # Used internally for debug sandbox under external interpreter
  File "d:\Program\Anaconda3\envs\dev\Lib\site-packages\zarr\hierarchy.py", line 333, in __getitem__
    raise KeyError(item)
builtins.KeyError: 'prefix_suffix'

```

#### Problem description

The prefix_suffix array should not be touched. This work well in directory store 

#### Version and installation information

Please provide the following:

* Value of ``2.3.1``
* Value of ``0.6.3``
* Version of Python interpreter : 3.7.2
* Operating system Windows
* How Zarr was installed  "using conda"

#### Solution
By changing a few lines of SQL queries in SQLiteStore Class, I was able to circumvent the problem. But as I am completely new to GitHub, I did not know where to post the solution for testing.

**Comment by jakirkham** [comment]
Ouch! Sorry for the trouble @potter420. If you already have a fix, would be happy to review a PR. If not, happy to take a closer look at this issue.

**Comment by potter420** [comment]
@jakirkham Thank you, I submitted a PR for this issue for review.
https://github.com/zarr-developers/zarr/pull/440

**Comment by jakirkham** [comment]
Fixed by PR ( https://github.com/zarr-developers/zarr-python/pull/440 ).
