### ISSUE TITLE
Use of Zarr on HPC file systems

### ISSUE THREAD

**Issue by pbranson** [zarr-developers/zarr-python#451]
Cross-posting of issue https://github.com/pangeo-data/pangeo/issues/659 to get some input from zarr-developers:

When using Zarr on HPC filesystems for large datasets, frequently a large number of files are created depending on the chunk_size utilised.

On HPC often file inode limits are placed as many small files can adversely affect the stability of the filesystem and place significant load on the metadata servers.

After creating the Zarr datasets in a directory, they can be stored into zip files (without compression as chunks should already be compressed) and the zarr.storage.ZipStore utilised to access the files and this works well, i.e.:

```
ds = xr.open_zarr(zarr.storage.ZipStore(zipfile,mode='r'))
```

Also the recently added zarr.consolidate_metadata works too.

Whilst this works well, often I have found the it is more efficient to still partition the dataset into years/months depending on the source files and size of the dataset.

I am wondering about what the recommended way to consolidate metadata across multiple zarr ZipStores might be? Is it possible to create an intake catalog for this? I think that would require some minor alterations xr.open_zarr to check for .zip file extension and use ZipStore. Alternatively is it possible to create some sort of .zmetadata file that consolidates the metadata?

ww3.aus_4m.197901.zip
ww3.aus_4m.197902.zip
ww3.aus_4m.197903.zip
ww3.aus_4m.197904.zip
ww3.aus_4m.197905.zip
ww3.aus_4m.197906.zip

At present I use the following boilerplate code to load a mult-zipstore dataset:

```
from dask import delayed, compute

def open_mf_zarrzipstore(zips,keep_vars=None):
    @delayed
    def open_zip_store(z,keep_vars=None):
        store = zarr.storage.ZipStore(z,mode='r')
        ds = xr.open_zarr(store,consolidated=True)
        if keep_vars is not None:
            ds = ds[keep_vars]
        return ds
    
    mf_ds = compute([open_zip_store(z,keep_vars) for z in zips])[0]
    ds = xr.concat(mf_ds,dim='time')
    return ds

ds = open_mf_zarrzipstore(zips,keep_vars=['hs',])
```

@martindurant has provided some helpful input (see https://github.com/pangeo-data/pangeo/issues/659#issuecomment-508130226 and  https://github.com/pangeo-data/pangeo/issues/659#issuecomment-508188348) where he suggested the idea of a "metadata only" zarr group.

Thanks for any advice

**Comment by jakirkham** [comment]
I wonder if [`ChainMap`]( https://docs.python.org/3/library/collections.html#collections.ChainMap ) would be useful here.
