### ISSUE TITLE
Question: When does Zarr write to disk?

### ISSUE THREAD

**Issue by manolinux** [zarr-developers/zarr-python#454]
Hi, I've got one  process that iterative checks 23000 elements (numpy small matrices), do a processing on them and then writes a flag in Zarr that means no further computing for that matrix needed.

So, there's something like: 

  zarr_group.attrs['trigger'] = trigger

where trigger is a boolean value (right now, an integer being 0 or 1)

I've observed that iteration goes on for some thousand elements, then stops for a couple of seconds and so on. 

Is the writing for trigger attr taking place inmediately, or is there any kind of buffering until some amount of space is reached and then written to disk? Does it exist any flush operation that may writes become faster (depending on the buffer size).

Any advice for I/O in Zarr would be welcome, any percentage of speedup gain in writes would be welcome.

Kind regards, and thank you for this software!

P.S. Kind of storage is DirectoryStore. Don't think caching is useful here as we're iterating lineally through elements. Maybe could we read in advance some elements and write only a few times?

**Comment by jakirkham** [comment]
Basically we are just using the [`.write()`]( https://github.com/zarr-developers/zarr-python/blob/d330cdf69d5fe21604aaba8f93cd1cfaed486d58/zarr/storage.py#L765-L772 ) method of Python file objects. This is the same whether it is an attribute or a chunk of data.

If you want to write several attributes at once, use the [`.update()`]( https://github.com/zarr-developers/zarr-python/blob/fb8e6d5ea6bc26e451e5cf0eaaee36977556d5b5/zarr/attrs.py#L120-L123 ) method of `.attrs` instead. That should do one write after updating all the attributes you have provided.

**Comment by manolinux** [comment]
Thanks a lot.im using update attribute now, and also noticed great
improvement of performance using python concurrent tasks as I,m writing
disjoint arrays so I can somehow overlap calculations from next iterations
of my loop having still pending writes that are run in ither thread. Now my
performance is quite near to the calculation step alone, writing is not so
painful as before. Thanks a lot again, I like zarr very much!
