### ISSUE TITLE
Azure tests failing on AppVeyor CI

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-python#467]
Seeing the following error on AppVeyor now with the Azure tests.

```
azure.common.AzureHttpError: The REST version of this request is not supported by this release of the Storage Emulator. Please upgrade the storage emulator to the latest version. Refer to the following URL for more information: http://go.microsoft.com/fwlink/?LinkId=392237
```

ref: http://go.microsoft.com/fwlink/?LinkId=392237
ref: https://ci.appveyor.com/project/zarr-developers/zarr/builds/26623115

cc @shikharsg

**Comment by shikharsg** [comment]
Thanks. Will have a look in a couple of days
