### ISSUE TITLE
Difference between zarr creation functions

### ISSUE THREAD

**Issue by CDitzel** [zarr-developers/zarr-python#471]
I am wondering what the use case is for 

`z = zarr.array(a, chunks=(1000, 100))
`
Why would I ever want to create a zarr array in my RAM? 

Also, I dont quite get the difference between the function

`
z = zarr.open('data/example.zarr', mode='w', shape=(10000, 10000), chunks=(1000, 1000), dtype='i4')
`
and the simple save method

`
zarr.save('data/example.zarr', a)
`

Can someone clearify please?

**Comment by jakirkham** [comment]
It can be useful if your data is just a bit bigger than your available RAM uncompressed. Also in conjunction with a library like Dask, it can be handy to parallelize computations by chunks in that in-memory array. This is not too different from [the equivalent feature in HDF5]( http://docs.h5py.org/en/stable/high/file.html?highlight=core#file-drivers ).

Let's leave the last part for issue ( https://github.com/zarr-developers/zarr-python/issues/463 ), which seem to already ask this.

**Comment by alimanfoo** [comment]
> Why would I ever want to create a zarr array in my RAM?

Just to second @jakirkham, sometimes data are highly compressible, and so you can't store uncompressed in memory but can store compressed in memory. In which case computation can be very fast, only pay overhead of compression/decompression, no I/O.

**Comment by alimanfoo** [comment]
Going to close as #463 deals with clarifications.
