### ISSUE TITLE
data of array with dtype set to bytes is truncated

### ISSUE THREAD

**Issue by wrobell** [zarr-developers/zarr-python#474]
Using zarr 2.3.2 and numcodecs 0.6.3.

Please consider the two following scripts.

First script creates data
```
import zarr

N = 1024 ** 2
CHUNK = 256 * 1024

fout = zarr.open('test-bytes.zarr', 'w')
ds = fout.empty('message', shape=(N,), chunks=(CHUNK,), dtype=bytes)

for i in range(N // CHUNK):
    k1 = i * CHUNK
    k2 = k1 + CHUNK
    ds[k1:k2] = [bytes([0x01, 0, 0, 0, 0, 0, 0])] * CHUNK
```

Second script reads the data
```
import zarr

fout = zarr.open('test-bytes.zarr', 'r')
print(fout['message'][:5])
count = sum(1 for v in fout['message'] if len(v) != 7)
print(count)
```

The output of the 2nd script is
```
[b'\x01' b'\x01' b'\x01' b'\x01' b'\x01']
1048576
```

As you can see, all trailing null bytes are truncated. As this is byte data (*not* null-terminated string) I would expect the null bytes to be preserved.

The info of the message dataset is
```
Name               : /message
Type               : zarr.core.Array
Data type          : object
Shape              : (1048576,)
Chunk shape        : (262144,)
Order              : C
Read-only          : True
Filter [0]         : VLenBytes()
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 8388608 (8.0M)
No. bytes stored   : 22824 (22.3K)
Storage ratio      : 367.5
Chunks initialized : 4/4
```

**Comment by wrobell** [comment]
And simpler example
```
import zarr
import numcodecs

z = zarr.array([b'\x00\x01\x00', b'\x01\x02'], dtype=object, object_codec=numcodecs.VLenBytes())

print(list(z))
```

Above script prints
```
[b'\x00\x01', b'\x01\x02']
```

**Comment by wrobell** [comment]
Trying the codec directly, there seems to be no issue

```
import numcodecs

codec = numcodecs.MsgPack()
v = codec.encode(bytearray(b'\x00\x01\x00'))
print(codec.decode(v))

codec = numcodecs.VLenBytes()
v = codec.encode(b'\x00\x01\x00')
print(codec.decode(v))
```

and the output

```
[0 1 0]
[b'\x00\x01\x00']
```

**Comment by alimanfoo** [comment]
Hi @wrobell, apologies this didn't get a reply at the time. FWIW I think the problem is [here](https://github.com/zarr-developers/zarr-python/blob/27f07262ade3bdc89517b847099b7c9dd8c08784/zarr/creation.py#L320), when the input data is not a numpy array then zarr tries to convert it to an array via np.asanyarray, but does not provide a dtype, in which case numpy infers a fixed length string dtype and does the truncation. E.g.:

```python
In [15]: np.asarray([b'\x00\x01\x00', b'\x01\x02'])                                                                                                           
Out[15]: array([b'\x00\x01', b'\x01\x02'], dtype='|S3')
```

The fix would be to first look for a dtype in the provided kwargs, and pass that into np.asanyarray().

**Comment by jakirkham** [comment]
Just to add another option here, this should also work...

```python
import numpy
import zarr
import numcodecs

z = zarr.array(numpy.array([b'\x00\x01\x00', b'\x01\x02'], dtype=object), object_codec=numcodecs.VLenBytes())

print(list(z))
```

**Comment by dstansby** [comment]
Looks like this was solved, so I'll close. Thanks for opening, and feel free to open an new issue if you're still having issues!
