### ISSUE TITLE
Return view when slicing

### ISSUE THREAD

**Issue by Pierre-Bartet** [zarr-developers/zarr-python#478]
When slicing a numpy array, a view is return, for example:

```
a = np.arange(1000000000)
b = a[::10] # Instantaneous, b is only a view
```
While zarr arrays slicing leads to loading into memory:

```
z = zarr.array(a)
y = z[::10] # Slow, data is really loaded
```

I guess it is now too late for such a breaking change, but IMHO and looking at the choices made in other libraries who have np.ndarray equivalent (TensorFlow, pyTorch, h5py), I find it much more convenient when slicing just returns views (TensorFlow, pyTorch) than when it loads data (zarr, h5py).

```
def f(x):  
    "Expect a (L * 2) array. Maybe in practice L will be super large and this function will use chunks."

    return x[:, 0].mean() - x[:, 1].mean()

a = np.random.rand(L, 5)
b = a[:, [1, 3]] # I don't want data to be loaded here, it might not even be possible if L is large

print(f(b))
```

**Comment by alimanfoo** [comment]
Hi @Pierre-Bartet, I would suggest to use Dask here, e.g.:

```
import dask.array as da
z = ...  # some zarr array
zd = da.from_array(z)
y = zd[::10]  # this is like a view - it's a deferred result, not computed until needed
```

**Comment by Pierre-Bartet** [comment]
@alimanfoo indeed that is a good solution, I was just wondering why not just sticking to numpy behaviour when possible.

**Comment by alimanfoo** [comment]
> @alimanfoo indeed that is a good solution, I was just wondering why not just sticking to numpy behaviour when possible.

Mainly for compatibility with h5py. Many users (including me:-) transition from h5py to zarr, so I wanted to make that as seamless as possible.

**Comment by jakirkham** [comment]
Yeah it's a bit difficult to provide a view of data that is chunked and compressed on disk unfortunately. Users like yourself may appreciate using either Dask with Zarr. Or looking at caching [before]( https://zarr.readthedocs.io/en/latest/api/storage.html#zarr.storage.LRUStoreCache ) or after ( https://github.com/zarr-developers/zarr-python/pull/306 ) decompression.

**Comment by Pierre-Bartet** [comment]
Ok, I understand ! Closing.

**Comment by wrobell** [comment]
Bit more about this subject

https://github.com/h5py/h5py/issues/1268
