### ISSUE TITLE
attrs cannot store  values of type np.int32 or np.bool_ 

### ISSUE THREAD

**Issue by amkigit** [zarr-developers/zarr-python#481]
Hello,

I tried to store some np.int32 or np.bool8 values in the attrs of the root group, but this failed.

Values of type np.float64 work. 

Please see the attached example

[zerror.txt](https://github.com/zarr-developers/zarr-python/files/3668047/zerror.txt)

**Comment by jrbourbeau** [comment]
Thanks for opening an issue @amkigit! I'm able to reproduce an error with your example (pasting here for future reference):

```python
import zarr
import numpy as np

root = zarr.open('zerror', mode='w')

vals=[np.float64(1), np.int32(2), np.bool8(True)]

for i in range(len(vals)):
    try:
        root.attrs[str(i)]=vals[i]
    except:
        print(type(vals[i]))
        val=int(vals[i])
        root.attrs[str(i)]=val
```

This is a current limitation of Zarr as attributes must be json-serializable. This was previously reported and discussed over in #156. Would it be alright to close this issue as a duplicate and move the conversation over to #156?

**Comment by jakirkham** [comment]
Yeah let's close this and consolidate.

As a workaround, @amkigit you may consider converting your data to native JSON types first.
