### ISSUE TITLE
Source links in docs

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/zarr-python#50]
Get source links working in docs.

**Comment by alimanfoo** [comment]
Working locally, not sure why not working on rtfd. Not the first to see this: https://github.com/rtfd/readthedocs.org/issues/2139

**Comment by jakirkham** [comment]
This appears closed upstream. Maybe [this comment]( https://github.com/rtfd/readthedocs.org/issues/2139#issuecomment-390389784 ) is useful for fixing this?

**Comment by jrbourbeau** [comment]
Looks like the "source" links are working properly now (e.g. see https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.DictStore). I suspect this issue can be closed.

**Comment by jrbourbeau** [comment]
Closing as source links appear to be working now

**Comment by jakirkham** [comment]
Thanks James! 😄
