### ISSUE TITLE
Test against/ build for python 3.8

### ISSUE THREAD

**Issue by clbarnes** [zarr-developers/zarr-python#511]

**Comment by jrbourbeau** [comment]
There's a open PR (ref #499) for this, which should be good to merge once there are Python 3.8 wheels for `h5py`

**Comment by clbarnes** [comment]
Sorry, my bad, only searched the issues.

**Comment by jakirkham** [comment]
No worries. It's good to see other people are interested in this 😉

**Comment by jrbourbeau** [comment]
Yeah, not a problem. Thanks for opening this issue up

**Comment by clbarnes** [comment]
h5py wheels are blocking half my repos too...

**Comment by jakirkham** [comment]
Was going to suggest raising an issue, but looks like you already have ( https://github.com/h5py/h5py/issues/1410 ). Thanks for doing that btw. 🙂

**Comment by jakirkham** [comment]
Would add we probably need these for Windows too.
