### ISSUE TITLE
cannot import name "ensure_ndarry"

### ISSUE THREAD

**Issue by yasohasakii** [zarr-developers/zarr-python#524]
For bug reports, please follow the template below. For enhancement proposals, feel free
to use whatever template makes sense.

#### Minimal, reproducible code sample, a copy-pastable example if possible

```python
# import zarr

```

#### Problem description

Explain why the current behavior is a problem, what the expected output/behaviour 
is, and why the expected output/behaviour is a better solution.
after installed zarr by pip successfully, import it by get failed error:
> from numcodecs.compat import ensure_bytes,ensure_ndarray
>ImportError: cannot import name "ensure_bytes"

#### Version and installation information

Please provide the following:

* Value of ``zarr.__version__``2.3.2
* Value of ``numcodecs.__version__``0.5.4
* Version of Python interpreter 3.6
* Operating system (Linux/Windows/Mac)windows 10
* How Zarr was installed (e.g., "using pip into virtual environment", or "using conda")pip

Also, if you think it might be relevant, please provide the output from ``pip freeze`` or
``conda env export`` depending on which was used to install Zarr.

**Comment by alimanfoo** [comment]
Hi @yasohasakii, thanks for reporting. It looks like your version of numcodecs needs to be upgraded, zarr version 2.3.2 requires numcodecs >= 0.6.2. Can you upgrade numcodecs in your environment?

**Comment by yasohasakii** [comment]
thanks，problem solved.
