### ISSUE TITLE
zarr.tree() example in docs doesn't work as of 2.4.0

### ISSUE THREAD

**Issue by ryan-williams** [zarr-developers/zarr-python#537]
#### Minimal, reproducible code sample, a copy-pastable example if possible

Taken from [the docs](https://zarr.readthedocs.io/en/stable/tutorial.html#copying-migrating-data):
```python
import h5py
import zarr
import numpy as np
source = h5py.File('data/example.h5', mode='w')
foo = source.create_group('foo')
baz = foo.create_dataset('bar/baz', data=np.arange(100), chunks=(50,))
spam = source.create_dataset('spam', data=np.arange(100, 200), chunks=(30,))
zarr.tree(source)
```

#### Problem description

Tree widget renders correctly in Zarr 2.3.2:
![image](https://user-images.githubusercontent.com/465045/74668441-345fbd80-5173-11ea-811d-e75ee50fed59.png)

Same code throws a `ValueError` (and renders some text) in 2.4.0:
![image](https://user-images.githubusercontent.com/465045/74668501-59ecc700-5173-11ea-835f-db8aa8922d5c.png)

#### Version and installation information
2.3.2 works as expected; `pip freeze`:
```
appnope==0.1.0
asciitree==0.3.3
backcall==0.1.0
decorator==4.4.1
fasteners==0.15
h5py==2.10.0
ipykernel==5.1.4
ipython==7.12.0
ipython-genutils==0.2.0
jedi==0.16.0
jupyter-client==5.3.4
jupyter-core==4.6.2
monotonic==1.5
numcodecs==0.6.4
numpy==1.18.1
parso==0.6.1
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.3
ptyprocess==0.6.0
Pygments==2.5.2
python-dateutil==2.8.1
pyzmq==18.1.1
six==1.14.0
tornado==6.0.3
traitlets==4.3.3
wcwidth==0.1.8
zarr==2.3.2
```

2.4.0 exhibits the failure; `pip freeze`:
```
appnope==0.1.0
asciitree==0.3.3
backcall==0.1.0
decorator==4.4.1
fasteners==0.15
h5py==2.10.0
ipykernel==5.1.4
ipython==7.12.0
ipython-genutils==0.2.0
jedi==0.16.0
jupyter-client==5.3.4
jupyter-core==4.6.2
monotonic==1.5
numcodecs==0.6.4
numpy==1.18.1
parso==0.6.1
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.3
ptyprocess==0.6.0
Pygments==2.5.2
python-dateutil==2.8.1
pyzmq==18.1.1
six==1.14.0
tornado==6.0.3
traitlets==4.3.3
wcwidth==0.1.8
zarr==2.4.0
```
(the Zarr version is the only difference)

https://github.com/zarr-developers/zarr-python/pull/450 seems relevant (cc @jakirkham); possibly discussion at https://github.com/zarr-developers/zarr-python/issues/259 as well.

**Comment by jakirkham** [comment]
Are you rendering it in the notebook? If so, you need to install `ipytree` now. This dependency was added so rendering would work in JupyterLab. Though, once installed, it should work in the notebook too.

Sounds like we could use a clear error message though.

**Comment by jakirkham** [comment]
@ryan-williams? 🙂

**Comment by mzjp2** [comment]
Should we add `ipytree` to our requirements in that case? (or make it an `extras_require`?)

**Comment by jakirkham** [comment]
It is listed [in the `extras_require`]( https://github.com/zarr-developers/zarr-python/blob/994f2449b84be544c9dfac3e23a15be3f5478b71/setup.py#L35 ).

**Comment by mzjp2** [comment]
Ah, my bad. Thanks. :)

Agree with your earlier comment, we could do with a clearer error message.

**Comment by jakirkham** [comment]
No worries 😉

Yeah we can make this fallback behavior nicer 🙂
