### ISSUE TITLE
Create Zenodo DOI for Zarr-Python

### ISSUE THREAD

**Issue by rabernat** [zarr-developers/zarr-python#544]
There is no scientific publication about Zarr. We should try to write one eventually. In the meantime, I would like to cite Zarr somehow in a proposal where URLs are forbidden.

An easy thing we could do is generate a DOI for Zarr-python with Zenodo.
https://guides.github.com/activities/citable-code/
This would need to be done by someone with owner privileges on the zarr-developers org.

That would be a nice temporary solution.

**Comment by mzjp2** [comment]
I guess @alimanfoo can do this. Maybe @jakirkham?

Also, can you add the Zarr logo to the organization logo/team logo whilst you're at it :D

**Comment by wtbarnes** [comment]
I am currently a co-author on a paper where we used Zarr and would like to be able to cite it more formally. A URL would be ok, but a Zenodo DOI would be even better!

**Comment by alimanfoo** [comment]
I did the zenodo integration for the zarr-python repo, latest release (2.4.0) has a record [here](https://zenodo.org/record/3773450#.XqgZI3VKiV4), DOI https://doi.org/10.5281/zenodo.3773450

**Comment by wtbarnes** [comment]
🎉  thanks very much @alimanfoo!

**Comment by jakirkham** [comment]
Do they have a badge for this? Maybe we can add it to the main repo then?

**Comment by jrbourbeau** [comment]
It looks like we already have a zenodo badge in the main `README.md`. Is it safe to close this issue then?

**Comment by jakirkham** [comment]
Indeed. Totally missed that. Yeah let's close.

**Comment by jakirkham** [comment]
Thanks @alimanfoo! 😄

**Comment by alimanfoo** [comment]
No worries :-) Just to note it looks like the badge is release specific, so
readme needs to be updated after each release, unless I'm missing
something.

**Comment by jakirkham** [comment]
What did you have to do to create it?

**Comment by alimanfoo** [comment]
> What did you have to do to create it?

I've previously created a zenodo account linked to my github account. To add zarr-python I went to https://zenodo.org/account/settings/github/ and followed the 3 step instructions to add a github repository. 

I had a bit of trouble as none of the repos in the zarr-developers organisation were showing in the list initially, but I [fixed that](https://github.com/zenodo/zenodo/issues/1814#issuecomment-620555444) after some thrashing about.

When you "flip the switch" on a github repo, zenodo installs a webhook. Then when you make a new release on github, zenodo automatically archives it. Fortunately we hadn't declared github releases for either v2.3.2 or v2.4.0 tags, so I turned those tags into releases and zenodo did the rest.

**Comment by jrbourbeau** [comment]
It looks like we can use https://doi.org/10.5281/zenodo.3773449 to point to the latest release. See the "Cite all versions?" text in the screenshot below:

<img width="375" alt="Screen Shot 2020-04-28 at 3 43 21 PM" src="https://user-images.githubusercontent.com/11656932/80536089-740f0680-8967-11ea-9439-323ab4725197.png">

**Comment by alimanfoo** [comment]
> It looks like we can use https://doi.org/10.5281/zenodo.3773449 to point to the latest release. See the "Cite all versions?" text in the screenshot below:
> 
> <img alt="Screen Shot 2020-04-28 at 3 43 21 PM" width="375" src="https://user-images.githubusercontent.com/11656932/80536089-740f0680-8967-11ea-9439-323ab4725197.png">

Ah, cool. Annoyingly, I created the v2.3.2 release *after* I created the v2.4.0 release, so currently zenodo thinks 2.3.2 is the latest. Should be back to normal after we make the next release though.

**Comment by jrbourbeau** [comment]
> Should be back to normal after we make the next release though

Any objection to doing a v2.4.1 release today (or soon-ish) then? There have been a few commits since the last release in January and I think the current `master` is in an okay state to cut a new release. This would also be a good opportunity to test out the zenodo webhook. To be clear, I'm happy to manage the release

**Comment by jakirkham** [comment]
SGTM. Thanks for doing that James! 😄

**Comment by wtbarnes** [comment]
I am using v2.6.1 for an upcoming paper, but it looks like the latest citable DOI on Zenodo is v2.5. Did something happen to the Zenodo/GitHub integration?

**Comment by joshmoore** [comment]
Hi @wtbarnes. Argh, you're right. There does look to be an issue or two. The releases are not being auto-generated, which I can fix manually, but even for those (like https://github.com/zarr-developers/zarr-python/releases/tag/v2.6.1) the Zenodo link hasn't yet been created. I'll give it a bit to catch up, and open an issue if Zenodo doesn't catch up.

**Comment by joshmoore** [comment]
@wtbarnes: Manually creating a release *does* work. https://zenodo.org/record/5085171#.YOwCEhMzb0o now exists. It looks like the link back *doesn't* get updated in the release page as it did previously. If anyone knows how to make that work, I'm all ears. I'll generate the rest of the releases asap.

**Comment by jakirkham** [comment]
Someone just created a citation tool for GitHub

https://mobile.twitter.com/natfriedman/status/1420122675813441540

**Comment by joshmoore** [comment]
:+1: Does anyone have an example that fits the current zarr-python model (citation via zenodo DOI)?
