### ISSUE TITLE
Indexing behaviour comparison with TensorStore

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/zarr-python#554]
Raising this issue just to note that [TensorStore's indexing behaviour](https://google.github.io/tensorstore/python/indexing.html) is very interesting and carefully thought through. A useful reference for any future discussion of indexing behaviour in zarr-python.

**Comment by jakirkham** [comment]
I'm now curious if they were talking with @shoyer 🙂

**Comment by shoyer** [comment]
I think my main contribution to the design of TensorStore was pointing them in the direction of zarr 😂

**Comment by jakirkham** [comment]
Seems to have had an impact 😉

**Comment by dstansby** [comment]
I'm going to close this, since I think most zarr core devs are aware of tensorestore, so not sure there's much action to take here? If there's a more specific part of the tensorestore API that is worth thinking about/implementing for zarr-python then I'd suggest opening a new issue/issues.
