### ISSUE TITLE
Reshape with core.Array.view

### ISSUE THREAD

**Issue by prokotg** [zarr-developers/zarr-python#558]
Hi there!

I have been working with `zarr` for some time now and I love it so far :smile:  Recently I wanted to reshape my array and the only solution that came to my mind was to use a `view` method like that:
```python
import zarr

import numpy as np 

arr = np.arange(2000).reshape(5, 100, 4)
zarr_arr = zarr.array(arr)
v = zarr_arr.view(shape=(500, 4), chunks=(1, 4))
print(v[0])
print(v[:])
```
but I get 0's every time I put sth inside `shape` argument:
```console
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
```

I wanted to ask if reshaping in this way is not desirable or is it because `view` is still an experimental feature and it's being worked on. I would love to contribute if simple shape mapping would be ok :smile:  

Cheers!

**Comment by alimanfoo** [comment]
Hi @prokotg, the most robust approach if you want to be able to reshape your array in the same way as you might reshape a numpy array would be to use [dask.array](https://docs.dask.org/en/latest/array.html). E.g.:

```python
import dask.array as da
arr = np.arange(2000).reshape(5, 100, 4)
zarr_arr = zarr.array(arr)
dask_arr = da.from_array(zarr_arr)
x = dask_arr.reshape((500, 4))
```

The new variable `x` would of course be a dask array.

Hth.

**Comment by prokotg** [comment]
@alimanfoo that works perfectly, thank you! Had no idea `zarr` is compatible with `dask`.

**Comment by alimanfoo** [comment]
> @alimanfoo that works perfectly, thank you! Had no idea `zarr` is compatible with `dask`.

Zarr was designed very much with Dask in mind :-)
