### ISSUE TITLE
How to improve random access time via dask?

### ISSUE THREAD

**Issue by prokotg** [zarr-developers/zarr-python#567]
Hi there! I wasn't sure if I should post it here or in `Dask` repo but I figured it's more related to the structure of `zarr.core.Array`.

I have a relatively large array of length (first dimension) around `86000000` where second dimension varies between `30` and `1600`.
 In other words I have arrays of `uint8` of shape `(86000000, 30` ,`(86000000, 150)`, etc...

The first dimension represents the number of examples in my machine learning project while second is the length of pre-computed features for each example.

The idea of using `zarr` is perfect for me since I get to store an entire array in one place, I have a unified interface to access all the arrays and I do not have to load the entire array into RAM since I'm using `zarr` with conjunction with `Dask`

#### Use case in my ML pipeline

Like many ML pipelines, I need to get `N` ***random*** examples every now and then so every iteration I have a list of `N` indices that I sort and use it to retrieve examples that I need

```python
# Your code here
import dask.array as da

features_array = da.from_array(my_zarr_array, chunks=my_zarr_array.chunks)
examples = feature_array[sorted(batch_indices)].compute() # very slow, takes few seconds (usually around 9)
```
`N` is usually between 2,000 and 20,000

#### What I have tried

- chunking array to have `(50, feature_length)` chunks - still slow
- chunking array to have `(1, feature_length)` chunks - slower than the former
- turning off the compression
- moving array from HDD to SSD (nice improvement, still a little bit slow)
-I thought of buffering some part of array and then taking batch from that buffer like in `Tensorflow` but I'm using `PyTorch` and there is no out of hand solution for that
#### Question

How can I improve random access read time?
#### Environment
* Value of ``zarr.__version__`` : 2.4.0
* Value of ``numcodecs.__version__`` : 0.6.4
* Version of Python interpreter 3.7
* Operating system (Linux/Windows/Mac) Linux
* How Zarr was installed (e.g., "using pip into virtual environment", or "using conda") `pip`

**Comment by alimanfoo** [comment]
Hi @prokotg, short answer is that zarr is not designed for random access like this, although I would have thought that performance will improve as you reduce the length of the chunk along the dimension you are randomly sampling, as you tried. If you are concerned about a large number of files then you might want to try one of the key-value stores like [LMDB](https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.LMDBStore).

**Comment by prokotg** [comment]
Hi @alimanfoo thanks for the response. Yeah, I think I hit the drive speed capability and that made it. I still think it's a great package :))

**Comment by alimanfoo** [comment]
Thanks @prokotg :-)
