### ISSUE TITLE
Group list members optimization when scanning keys

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/zarr-python#57]
When a store does not implement listdir and keys need to be scanned, there is a possible optimization for listing members of a group because child arrays and groups could be discovered within the key scan, rather than requiring additional `__contains__` tests.

**Comment by marynaggita** [comment]
@joshmoore  i am Mary, an outreachy candidate. Iam interested in this issue.

**Comment by marynaggita** [comment]
Kindly provide pointers which i can look at

**Comment by joshmoore** [comment]
@marynaggita: the `listdir()` method that is being referred to can be found here: https://github.com/zarr-developers/zarr-python/blob/main/zarr/storage.py#L214-L220

It uses `_listdir_from_keys()` method here:
https://github.com/zarr-developers/zarr-python/blob/main/zarr/_storage/store.py#L409

Maybe the first thing to do is to find a test that uses the `listdir` method.

**Comment by jhamman** [comment]
No longer relevant in the 3.0 store api.
