### ISSUE TITLE
negative chunks don't work as expected

### ISSUE THREAD

**Issue by ludwigVonKoopa** [zarr-developers/zarr-python#582]
#### Problem description

Hi all,

In my code, i recently came across a strange behaviour.

As stated in [documentation](https://zarr.readthedocs.io/en/stable/tutorial.html#chunk-size-and-shape), we can precise chunk size in zarr variable creation, and specify `None`or -1 for using the hole dimension.

Correct me if i'm wrong, but i feel the -1 chunk specification is corrupting the memory : 

```python
import zarr
import numpy as np

fichier1 = "/tmp/test.zarr"

example = np.zeros((10))
zh = zarr.open(fichier1, "w")

var1 = zh.create_dataset("var1", 
    shape=example.shape, 
    dtype=example.dtype,      
    chunks=(10)
)
var1[:] = 2.
print("var1 : ", var1[:])  # output as expected

var2 = zh.create_dataset("var2", 
    shape=example.shape, 
    dtype=example.dtype,      
    chunks=(-1)
)
var2[:] = 7.
print("var2 : ", var2[:])  # should be 7 but is 2 as var1
```
gives 

```python
var1 :  [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
var2 :  [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
```

#### More funny : 

```python
import zarr
import numpy as np

fichier1 = "/tmp/test.zarr"

zh1 = zarr.open(fichier1, "w")

example1 = np.zeros((10)) + 3
var1 = zh1.create_dataset("var1", 
    shape=example1.shape, 
    dtype=example1.dtype,      
    chunks=(10)
)
var1[:] = example1 + 5
print("var1 : ", var1[:])

example2 = np.zeros((10))
var2 = zh1.create_dataset("var2", 
    shape=example2.shape, 
    dtype=example2.dtype,      
    chunks=(-1)
)
var2[:] = 5
print("var2 : ", var2[:])
```

If you run this cell in a jupyter notebook it output : 
```python
var1 :  [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
var2 :  [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
``` 

if you **re-run** this cell, it output : 
```python
var1 :  [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
var2 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
``` 

#### Version and installation information
versions : 

```python
np.__version__
>>> '1.18.1'
zarr.__version__
>>> '2.3.2'
python
>>> Python 3.7.6 64-bit
```
Operating system : Linux

link on the notebook i created to demonstrate the problem : [zarr-chunk-corrupted](https://github.com/ludwigVonKoopa/problems/blob/master/negative_chunks_zarr.ipynb)

**Comment by jakirkham** [comment]
Note that `(1)` and `(1,)` are different.

```python
In [1]: (1)
Out[1]: 1

In [2]: (1,)
Out[2]: (1,)
```

**Comment by ludwigVonKoopa** [comment]
You are right. 
When i discovered this i had multiple dimensions data, so i defined tuples in chunks and shapes and for the minimal example i did not delete parenthesis.

Moreover, the problem still persist with tuples.

**Comment by ludwigVonKoopa** [comment]
Tested on version zarr==2.8.1, there is no probleme anymore.

Closing this issue.

**Comment by jakirkham** [comment]
Thanks for the update 😄
