### ISSUE TITLE
Place to list all zarr implementations in the docs. 

### ISSUE THREAD

**Issue by Carreau** [zarr-developers/zarr-python#585]
During today's call we mentioned a couple of zarr implementation, it would be good to have a place that list all of them (even incomplete) as well as version of zarr they support and languages written in,  order to show that Zarr is not Python specific and avoid duplication of work. 

We were pointed at https://github.com/constantinpape/zarr_implementations

But I think it would be nice to have that in the same main docs.

Having a number of test datasets of increasing complexity would also be good to test implementations.

**Comment by constantinpape** [comment]
> We were pointed at https://github.com/constantinpape/zarr_implementations

In case it's helpful for you, feel free to reuse any of the code datasets in there.

I would also not mind transfering ownership of this repository to the zarr organisation if anyone wants to build on this.

**Comment by joshmoore** [comment]
@constantinpape : :+1:

**Comment by rabernat** [comment]
It would be very helpful to update the main Zarr docs with a link to the various implementations.

**Comment by joshmoore** [comment]
@rabernat : agreed.

NB: From the above, zarr_implementations has now been migrated to the org, and I think we're working toward having a generated page showing which features are implemented in each.

**Comment by rabernat** [comment]
Do we perhaps want to consider reorganizing our web presence more broadly. Perhaps a high-level landing page (e.g. zarr-format.org) that links out to the spec and the various implementation doc pages?

**Comment by manzt** [comment]
> Do we perhaps want to consider reorganizing our web presence more broadly. Perhaps a high-level landing page (e.g. zarr-format.org) that links out to the spec and the various implementation doc pages?

Happy to help with this if there is interest.

**Comment by rabernat** [comment]
Great @manzt! Do we like zarr-format.org as the domain for the high-level page? If so I will buy it.

**Comment by joshmoore** [comment]
Really unfortunate we can't get zarr.org. (The only other suggest I have this evening is `zarr.store` ;) )

**Comment by rabernat** [comment]
zarr.ar? 🙄

**Comment by jhamman** [comment]
https://github.com/zarr-developers/zarr_implementations
