### ISSUE TITLE
Indexing based on chunk's coordinates

### ISSUE THREAD

**Issue by skgbanga** [zarr-developers/zarr-python#596]
Hello,

This came up in the issue #595 when we wanted to write to a zarr file in chunks to best use gcs backend. 
The code that I wrote looked like this:

```py
            ...
            start = (num_chunks - 1) * chunk_size
            end = num_chunks * chunk_size
            z[start:end, :] = np.array(rows)
            ...
```

I was looking in the docs (https://zarr.readthedocs.io/en/stable/tutorial.html#) to see if we can index based on chunk i.e. (hypothetical api)

```py
z.chunk((3,4)) = np.array(rows)
```

where (3, 4) are the coordinates of the chunk that you want to write/read. 

Does this suggestion make sense? Is there a better way to accomplish the above?

Thanks!

**Comment by joshmoore** [comment]
See also https://github.com/zarr-developers/zarr-python/issues/518

**Comment by skgbanga** [comment]
Ah, thanks @joshmoore. I will close this issue and +1 that thread.
