### ISSUE TITLE
ValueError: path '' contains an array

### ISSUE THREAD

**Issue by srib** [zarr-developers/zarr-python#598]
#### What am I doing?

1. Create an array on the local filesystem
2. Upload the array to an S3 bucket.
3. Try and read from the S3 bucket

#### Minimal, reproducible code sample, a copy-pastable example if possible
1. Create an array
```python
compressor = Blosc(cname='lz4', clevel=3, shuffle=Blosc.BITSHUFFLE)

z = zarr.open(LOCAL_ZARR_PATH/file.zarr, mode='w', shape=(3000, 4000, 5000), chunks=(300, 400, 500), dtype=np.float32, synchronizer=zarr.ThreadSynchronizer(), compressor=compressor)

# Fill some data
```

2. Copy to S3 bucket
```bash
aws s3 sync LOCAL_ZARR_PATH/file.zarr s3://BUCKET_NAME/file.zarr
```

3. Read from S3
```python
import s3fs
s3 = s3fs.S3FileSystem(client_kwargs=dict(region_name='us-east-1'))
store = s3fs.S3Map(root='BUCKET_NAME/file.zarr', s3=s3, check=True)
cache = zarr.LRUStoreCache(store, max_size=2**28)
root = zarr.group(store=cache)
```

Error message:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-170-90fc06d336b0> in <module>
      3 store = s3fs.S3Map(root='tgs-datascience-zarr-experiments/Campos-109GB.zarr', s3=s3, check=True)
      4 cache = zarr.LRUStoreCache(store, max_size=2**28)
----> 5 root = zarr.group(store=cache)

site-packages/zarr/hierarchy.py in group(store, overwrite, chunk_store, cache_attrs, synchronizer, path)
   1082     if overwrite or not contains_group(store):
   1083         init_group(store, overwrite=overwrite, chunk_store=chunk_store,
-> 1084                    path=path)
   1085 
   1086     return Group(store, read_only=False, chunk_store=chunk_store,

site-packages/zarr/storage.py in init_group(store, overwrite, path, chunk_store)
    440     # initialise metadata
    441     _init_group_metadata(store=store, overwrite=overwrite, path=path,
--> 442                          chunk_store=chunk_store)
    443 
    444 

site-packages/zarr/storage.py in _init_group_metadata(store, overwrite, path, chunk_store)
    452             rmdir(chunk_store, path)
    453     elif contains_array(store, path):
--> 454         err_contains_array(path)
    455     elif contains_group(store, path):
    456         err_contains_group(path)

site-packages/zarr/errors.py in err_contains_array(path)
     15 
     16 def err_contains_array(path):
---> 17     raise ValueError('path %r contains an array' % path)
     18 
     19 

ValueError: path '' contains an array
```
#### Problem description

Explain why the current behavior is a problem, what the expected output/behaviour 
is, and why the expected output/behaviour is a better solution.

#### Version and installation information

Please provide the following:

* Value of ``zarr.__version__``: 2.4.0
* Value of ``numcodecs.__version__``: 0.6.4
* Version of Python interpreter: 3.7.7
* Operating system (Linux/Windows/Mac): Ubuntu 18.04
* How Zarr was installed (e.g., "using pip into virtual environment", or "using conda"): pip

Also, if you think it might be relevant, please provide the output from ``pip freeze`` or
``conda env export`` depending on which was used to install Zarr.

**Comment by joshmoore** [comment]
The path you are configuring (`file.zarr`) isn't a group but an array which is why the `zarr.group()` method is failing. Try using `zarr.open(store=cache)` instead.

**Comment by srib** [comment]
Thanks, @joshmoore! That fixed it for me.

**Comment by aiqc** [comment]
this behavior pushed me away from the tool. just take my array. this is the part in numpy and pandas where you pass in the array/df, so that's what i'm expecting to do here.
