### ISSUE TITLE
Have a BaseStore class ?

### ISSUE THREAD

**Issue by Carreau** [zarr-developers/zarr-python#600]
Thi is a suggestion to have a `BaseStore` class or ABC, that store implementations can inherit from to have basic functionality.

#### Problem description

Saying that stores are "just" `MutableMapping` may be insufficient, a number of places call methods on stores that are not available in `MutableMapping`, which:

  - Make static type Checking fails if one uses `MutableMapping` as a type annotation.
  - Would provide a default methods, like `close()` method that is no-op, and would avoid the need to check for method existence.
  - Avoid reimplementation of boilerplate :`def __len__(self): return len(self.keys())`, still allowing overwrite.

**Comment by jakirkham** [comment]
Also issue ( https://github.com/zarr-developers/zarr-python/issues/573 ) and issue ( https://github.com/zarr-developers/zarr-python/issues/349 ) are related.

**Comment by jakirkham** [comment]
One thing that might be nice is to have a store that wraps a minimal `MutableMapping` with the extra bits of this ABC. That way users still have a path for using a minimal `MutableMapping` in this new framework.

**Comment by joshmoore** [comment]
see https://github.com/manzt/napari-dzi-zarr/blob/master/napari_dzi_zarr/store.py from @manzt for a possible consumer of a base class.

**Comment by Carreau** [comment]
there seem to be a number of place where the test assumes that stores can do things quite differently than what I was expecting and where `dict`, pass the test, but `MemoryStore` does not.  

Typically things like

```

def test_getsize():
    ...

    store = # Put dict() or MemoryStore() here
    store['boo'] = None
    assert -1 == getsize(store)
```

Will pass for dict, but `MemoryStore` will refuse to store None. 


or 


```
from zarr.storage import MemoryStore, init_array
from zarr import Array

store = # Put dict() or MemoryStore() here
init_array(store, path="foo/bar", shape=100, chunks=10)
z =  Array(
    store,
    path="foo/bar"
)

z[:] = 42
z.store['foo'] = b'bar'
z[:] = 43
```


Where MemoryStore will be quite unhappy because `z.store['foo'] = b'bar'` will mess-up the hierarchy, but `dict` won't call "requires parent" so works fine. 

So i'm unsure which is the "correct" behavior.

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/zarr-developers/zarr-python/pull/789 ) and preceding work
