### ISSUE TITLE
End support for python 3.5

### ISSUE THREAD

**Issue by clbarnes** [zarr-developers/zarr-python#602]
[EOL 2020-09-13](https://devguide.python.org/#status-of-python-branches) (see also [PEP478](https://www.python.org/dev/peps/pep-0478/#id4)) so no need to merge this in the next couple of days.

This will make pathlib use easier (see #601), among other things.

**Comment by joshmoore** [comment]
see also: https://github.com/zarr-developers/governance/issues/11

**Comment by joshmoore** [comment]
Closing along with https://github.com/zarr-developers/zarr-python/pull/603 (in order to open the Python 3.6 version)
