### ISSUE TITLE
Expand efficient row iteration with possibility to start iterating anywhere

### ISSUE THREAD

**Issue by yetyetanotherusername** [zarr-developers/zarr-python#615]
As sort of a follow up to https://github.com/zarr-developers/zarr-python/issues/398, would it be possible to expand this useful feature with a way to set the start point for the iterator? This way, when one wants to efficiently iterate over only a subset of the array with a generator, you don't have to walk over the unneeded parts of the array.

**Comment by yetyetanotherusername** [comment]
If i'm not mistaken, this small modification to https://github.com/zarr-developers/zarr-python/issues/398 should already do the trick:

```python
    def islice(self, start=None, end=None):
        if len(self.shape) == 0:
            # Same error as numpy
            raise TypeError("iteration over a 0-d array")
        # Avoid repeatedly decompressing chunks by iterating over the chunks
        if start is None:
            start = 0
        if end is None:
            end = self.shape[0]
        # in the first dimension.
        chunk_size = self.chunks[0]
        for j in range(self.shape[0], start, end):
            if j % chunk_size == 0:
                chunk = self[j: j + chunk_size]
            yield chunk[j % chunk_size]
```

**Comment by yetyetanotherusername** [comment]
I've gone ahead and implemented this in a fork together with a test. I can still make a pull request, but would like some confirmation that it has a chance of getting accepted before I proceed.

**Comment by jeromekelleher** [comment]
It looks good to me @yetyetanotherusername, I'm happy to review the PR. Seems like a fairly uncontroversial addition, but I'm not one of the core devs (who may disagree).

**Comment by yetyetanotherusername** [comment]
Thanks @jeromekelleher! I've opened a [pull request](https://github.com/zarr-developers/zarr-python/pull/621). I still have some stuff to do regarding documentation and I'm a bit unhappy about the tests for `__iter__` and `islice` partially duplicating each other. For starters I left the original test unchanged since I wanted to make extra sure I don't break anything. 

I'm not intimately familiar with the rest of the `zarr` interface and its error handling, so if you feel that something should be caught that isn't right now, I'd be very happy about any input. For example, I don't support reverse iteration right now, so probably trying it should raise a `NotImplementedError`.

**Comment by yetyetanotherusername** [comment]
Closed by https://github.com/zarr-developers/zarr-python/pull/621
