### ISSUE TITLE
v2.5 release plan

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/zarr-python#617]
Raising this issue to surface the proposed release plan for v2.5.

v2.5 will be the last release to support Python 3.5 (xref #602, #603, https://github.com/zarr-developers/governance/issues/11).

Outstanding PRs to be merged prior to release:

* #611 Reduce number of store queries in open(mode='a').
* #606 Fs multiget (depends on upstream release of fsspec)
* #616 Misc release notes

@Carreau has kindly agreed to be release manager.

We also discussed the possibility to review the [release procedure](https://zarr.readthedocs.io/en/stable/contributing.html#release-procedure) and add automation of the PyPI release via CI, as is currently implemented for numcodecs. Whether to implement any automation for this release is at @Carreau's discretion.

**Comment by alimanfoo** [comment]
Just to add there were a couple of issues and a PR previously marked against the [v2.5 milestone](https://github.com/zarr-developers/zarr-python/milestone/10), which I have moved forward to a [v2.6 milestone](https://github.com/zarr-developers/zarr-python/milestone/11).

I've also added a [low-hanging-fruit label](https://github.com/zarr-developers/zarr-python/labels/low-hanging-fruit) to a couple of PRs which would be good candidates to prioritise for v2.6.

**Comment by Carreau** [comment]
Closing as 3.5 was released.
