### ISSUE TITLE
number of bytes on resize 

### ISSUE THREAD

**Issue by skgbanga** [zarr-developers/zarr-python#624]
Consider the following:

```py
>>> import zarr
>>> import numpy as np
>>> z = zarr.create((100, 2), chunks=(100, 2), dtype='float32')
>>> z[0:2] = np.arange(4).reshape(2, 2)
>>> z.resize(2, 2)
>>> z.info
Type               : zarr.core.Array
Data type          : float32
Shape              : (2, 2)
Chunk shape        : (100, 2)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : builtins.dict
No. bytes          : 16
No. bytes stored   : 431
Storage ratio      : 0.0
Chunks initialized : 1/1
```

As you can see, 'No. of bytes stored' > 'No. bytes'.

`resize` has this note:

```
Notes
-----
When resizing an array, the data are not rearranged in any way.

If one or more dimensions are shrunk, any chunks falling outside the
new array shape will be deleted from the underlying store
```

So this is most likely because there is only one chunk and that chunk is not changed at all (making resize efficient). 

Is there a way in which I can change the chunk size to my resized value?

**Comment by rabernat** [comment]
Hi @skgbanga -- sorry for the slow replies to you question.

Zarr will not change the chunk size on an existing array. Your only option is to copy the data from the old array to a new one. For very large arrays, the [rechunker](https://rechunker.readthedocs.io/) package can help you with that.
