### ISSUE TITLE
Move away from travis-ci ? 

### ISSUE THREAD

**Issue by Carreau** [zarr-developers/zarr-python#640]
I'm not sure this is completely possible; and it would be quite some work, but travis halved the number of OSS build machines available and some builds now take more than 24h to start. I'm unsure what the long term policy of travis-ci will be; but waiting several hours for a build to start is I believe conterproductive.

**Comment by Carreau** [comment]
Things seem back into a reasonable state, and appear to be a travis-ci.org vs travis-ci.com migration (.org is EOL dec 31 2020). Still if we could spread testing across many services that could make the time to feedback on a pull-request smaller.

**Comment by Carreau** [comment]
Pinning issue, we ran out of credits; builds and PRs are not running anymore....

**Comment by joshmoore** [comment]
@Carreau : I assume this can be closed now?

**Comment by jakirkham** [comment]
Yeah it's complete. Let's close. If there's something else to follow up on, let's open a new issue
