### ISSUE TITLE
release v2.6?

### ISSUE THREAD

**Issue by rabernat** [zarr-developers/zarr-python#656]
Now that #536 (async support) has been resolved. I'm quite eager to cut a release. I must admit to selfish motives--I want to use this in production asap. I have not been following development closely enough to really know what other features / bugs have been addressed recently.

How do @zarr-developers/core-devs feel about making a release? I assume this would be 2.6, since it includes new features.

**Comment by joshmoore** [comment]
This would have my vote as well for the s3 403/404 fix.

**Comment by jakirkham** [comment]
SGTM.

@Carreau, do you have any thoughts here? Are there any last minute bug fixes we would want to include?

**Comment by Carreau** [comment]
> @Carreau, do you have any thoughts here? Are there any last minute bug fixes we would want to include?

Maybe we want to fix #613 ? I did not had a look yet at why/how to fix though.

I think I can just update the docs with a changelog, and when tagged it will automatically make a release. I'll try to do that this week.

**Comment by Carreau** [comment]
Issues remaining are #262 (zarr.tree() on h5py File in notebook renders with wrong icon for root node and datasets) and  #253 (Zarr DirectoryStore: getsize is wrong); I don't think those two should block a 2.6. Once the fixes for the last remaining issues are merged I will do update the changelog one last time with the release number and tag to do a release. 

I've also create a 2.7 milestone; feel free to assign things to it.

**Comment by Carreau** [comment]
Ok, so apparently something went wrong with the detection of version nuber and what was pushed on PyPI is actually 0.0.0; which we can delete, but now I'm not sure why setuptools-scm did not find the  right version number. Anyone have an idea ?

**Comment by Carreau** [comment]
Ok, 2.6.1 released. Can someone yank/delete 0.0.0 on PyPI ? it would be confusing to see as it woudl technically be what 2.6.0 would have been.
