### ISSUE TITLE
Modify fill_value on existing arrays

### ISSUE THREAD

**Issue by rabernat** [zarr-developers/zarr-python#662]
There is currently no way to chance the fill_value on an existing array (without hacking the metadata). We allow existing arrays to be resized. Why not allow to change the fill_value?

**Comment by Carreau** [comment]
do you envisage to have a setter on fill_value property of arrays that update the metadata ?

**Comment by rabernat** [comment]
yes exactly

**Comment by jakirkham** [comment]
That seems reasonable. The one catch is we may have already used the existing fill value to populate any unused portions of chunks that were written out. IDK if that is something we want to worry about or not.

**Comment by Carreau** [comment]
A first test seem to show that it's relatively straightforward to make it work. 

```
In [1]: import zarr
   ...: a = zarr.create((10, 10), dtype=int)

In [2]: a[0]
Out[2]: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]: a.fill_value = 1

In [4]: a[0]
Out[4]: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
```

**Comment by jakirkham** [comment]
Would try writing into part of a chunk.

**Comment by rabernat** [comment]
Ah ok I misunderstood something then... I

> The one catch is we may have already used the existing fill value to populate any unused portions of chunks that were written out.

Ah I didn't realize that could happen, but now it makes sense. Ok maybe this is a bad idea.

**Comment by jakirkham** [comment]
Yeah this happens [here]( https://github.com/zarr-developers/zarr-python/blob/c0358a98148fb499a94115a854d2eae38de82d6a/zarr/core.py#L1774 ) for basic selections.

If we are wanting to update the fill value in existing chunks, we could go through and replace matches. Though if the fill value also shows up in the data (like `0`), then this might replace things we don't want to replace.

Maybe one could leverage a structured array to store the data along with a mask. This might work well if one is already using NumPy's masked arrays.

**Comment by rabernat** [comment]
> If we are wanting to update the fill value in existing chunks, we could go through and replace matches.

I am very hesitant to introduce anything new that implies eager evaluation over the entire array. My standard use case is a 10 TB array in cloud storage.

As a compromise, perhaps we could allow this *only* if no chunks are initialized on the array. That would actually have solved the problem that made me open this issue.

**Comment by Carreau** [comment]
We can also emit a warning when the value is changed; but like many thing I think that when someone modify the fill value, they really know what they are doing. And what we would do would not be worse than anybody reaching out into the metadata to change it...

**Comment by rabernat** [comment]
> We can also emit a warning when the value is changed

:+1:

> And what we would do would not be worse than anybody reaching out into the metadata to change it...

True

**Comment by jakirkham** [comment]
> I am very hesitant to introduce anything new that implies eager evaluation over the entire array. My standard use case is a 10 TB array in cloud storage.

Agreed. Just listing the options I can think of (regardless of their merit)

> As a compromise, perhaps we could allow this only if no chunks are initialized on the array. That would actually have solved the problem that made me open this issue.

Yeah this makes sense. +1

> I think that when someone modify the fill value, they really know what they are doing.

The only thing that gives me pause was Ryan (sorry to pick on you, Ryan) wasn't aware how fill value is used in existing chunks. So if Ryan doesn't know this, I'm less confident the average user does.

**Comment by rabernat** [comment]
🤣
