### ISSUE TITLE
Downstream repositories, on which we should test zarr/master

### ISSUE THREAD

**Issue by Carreau** [zarr-developers/zarr-python#668]
- [x] xarray
 - [x] ome-zarr https://github.com/ome/ome-zarr-py ? (https://github.com/ome/ome-zarr-py/pull/66)
 - [ ] https://github.com/constantinpape/zarr_implementations  (https://github.com/constantinpape/zarr_implementations/pull/15)
 - [ ] https://github.com/ome/omero-cli-zarr

**Comment by jakirkham** [comment]
cc @rabernat @joshmoore

**Comment by jakirkham** [comment]
cc @constantinpape

**Comment by jakirkham** [comment]
For context, we are considering changes like PR ( https://github.com/zarr-developers/zarr-python/pull/612 ), which wouldn't expect to cause issues for downstream, but it would be nice to confirm that somehow. Either by testing here or testing on the downstream repos themselves.

**Comment by jhamman** [comment]
FWIW, Xarray has recently added a nightly ci build that includes zarr-master ([example](https://github.com/pydata/xarray/runs/1487637678?check_suite_focus=true)).

**Comment by rabernat** [comment]
One idea would be to have a dedicated integration test repo for zarr, xarray, dask, and fsspec that would help cover the many edge cases that arise when these libraries all interact.

**Comment by jakirkham** [comment]
cc @martindurant

**Comment by martindurant** [comment]
*Some* downstreams (fsspec/s3fs) are tested directly in zarr's suite. Similarly, some combinations of dask/xarray are already tested in places, including their own repos.
It's fairly typical to see CI runs that install a variety of "dev" packages from the source repos.

Testing a workflow that touches *all* of the parts is tricky, and unlikely to catch the corner cases that arise in real work. For example, many s3 problems are around real cluster use and auth, which is very hard to test against. `rechunker` I suppose uses everything, but what range of likely usage patterns does it cover?

**Comment by Carreau** [comment]
> FWIW, Xarray has recently added a nightly ci build that includes zarr-master ([example](https://github.com/pydata/xarray/runs/1487637678?check_suite_focus=true)).

Good; so we are confident that if something break upstream, a bug will be fixed fast :-)

**Comment by joshmoore** [comment]
> https://github.com/zarr-developers/zarr-python/issues/668#issuecomment-737465521  One idea would be to have a dedicated integration test repo for zarr, xarray, dask, and fsspec...

I don't have an immediate driver for xarray, but I was certainly considering adding to @constantinpape's zarr_implementations for example different versions & at least a few different cloud backends. If such a test suite appears elsewhere, though, happy to adapt.

**Comment by jrbourbeau** [comment]
We added Zarr `master` to Dask's upstream CI build in https://github.com/dask/dask/pull/6932

**Comment by Carreau** [comment]
Awesome !
