### ISSUE TITLE
Timeout when writing data to zarr.storage.DBMStore multiple times which makes the whole zarr store unreadable

### ISSUE THREAD

**Issue by QINQINKONG** [zarr-developers/zarr-python#692]
Hi. I'm new to zarr, and trying to use Xarray to output files to zarr.storage.DBMStore. Since, the dataset is quite large, I calculate and output the results to one zarr.storage.DBMStore multiple times (append dim='time'). However, when the program failed because of timeout (I request 4hours from the queue every time), I seems to unable to access the data that have already been written to this zarr store during previous times. I wonder how to dealing with issues like this? 
More generally, what we should do if we encounter some error when writing to a zarr store multiple times along a dimension?

Below is my code to write and read files to and from zarr store, and also the error message after a timeout attempt:

#### code of writing data to zarr store

```python
import zarr
import xarray
store= zarr.DBMStore('/scratch/brown/kong97/WBGT/cmip6/GFDL_CM4_WBGT.bdb', open=bsddb3.btopen)
#doing some calculations and get the output: WBGT
WBGT.to_zarr(store,append_dim='time')
store.close()
```
After several times writing to this zarr store, the program fails because of timeout (the cluster may become very slow for some reason that I don't know). Then I found that I cannot read the data that have been written into this zarr store previously.
```python
store= zarr.DBMStore('/scratch/brown/kong97/WBGT/cmip6/GFDL_CM4_WBGT.bdb', open=bsddb3.btopen)
test=xr.open_zarr(store)
raise error: DBPageNotFoundError: (-30985, 'BDB0075 DB_PAGE_NOTFOUND: Requested page not found')
```

#### Problem description

It seems that the data written previously would be still accessible if I use the default directory storage. However, my cluster storage quota has a limit on the total number of files and using the default directory storage would create many small files and easily exceed limit.

#### Version and installation information

Please provide the following:

* Value of ``zarr.__version__``: '2.6.1'
* Value of ``numcodecs.__version__``: I didn't install that. Is that necessary?
* Version of Python interpreter: 3.7.9
* Operating system (Linux/Windows/Mac): Linux
* How Zarr was installed (e.g., "using pip into virtual environment", or "using conda"): using conda

Appreciate any help.
Thanks!

**Comment by jhamman** [comment]
@QINQINKONG -- sorry this issue never had a response. Unfortunately, we've decided to remove `DBMStore` so I don't expect a fix here. Hopefully you had more luck with another store interface.
