### ISSUE TITLE
Nested storage detection in Zarr V2

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#707]
see: https://github.com/ome/ngff/issues/29 and https://github.com/bcdev/jzarr/pull/17

In order to better handle Zarr arrays created with `NestedDirectoryStorage` or `FSStore(key_separator="/")`, SabineEmbacher  and I have been working on a "protocol heuristic" that can be used by V2 implementations to detect nested chunking rather than requiring the user to specify it correctly.

**tl;dr: This proposes a new key for `.zarray` which it would be good to have feedback on.**

----

### Proposal 

When creating a zarr array:

 * add to .zarray json: `{"dimension_separator": "/"}`
 * always write a 0-position chunk

When opening an array:

 * try to read the separator character from the .zarray json
 * if not available, try to find a 0-position chunk
 * if not available, at every read action try to find chunks with both standard variants until the situation is clarified. (Standard separator list `["/", "."]`)

----

### Points for discussion:
 * The name `dimension_separator` differs from the code implementation `key_separator` to reduce confusion about whether _every_ separator in the key name is effected.
 * There has been some discussion (community call, gitter) about whether or not "/" could become the default.
 * Is an addition to the .zarray metadata sufficiently low impact to be rolled into v2?

**Comment by SabineEmbacher** [comment]
Thoughts on the name of the separator:
What the separator separates is the respective chunk index per dimension.
See https://github.com/bcdev/jzarr/discussions/19 and https://github.com/bcdev/jzarr/pull/17#issuecomment-788730222 and

Therefore the following suggestions:

- chunk_index_separator
- chunk_index_sep
- chunk_idx_separator
- chunk_idx_sep

**Comment by jbms** [comment]
One issue with the detection protocol is that it does not work when writing.  While auto-detection is nice it might be better to just assume "." unless the metadata key is present --- any existing arrays could be fixed up, and hopefully all future arrays would have the metadata key.  That avoids the added complexity (and inefficiency) of auto-detection.

**Comment by joshmoore** [comment]
Hi @jbms. You mean a `mode="a"`-style writing? If so, I see the problem. I had initially intended the auto-detection only as a means of not needing to "standardize" a new key. Then I got greedy and went for both. Anyone else have thoughts?

In the case of a `mode="w"` situation I would assume the writer simply *asserts* where it will write.

> any existing arrays could be fixed up, and hopefully all future arrays would have the metadata key.

Guess there are some edge cases I worry about here. Maybe there are a number of strategies that can be enabled:
 * auto-detect
 * fail if missing metadata
 * set if missing metadata
 * ...

The real question is likely to be what should be the default.

**Comment by joshmoore** [comment]
> https://github.com/zarr-developers/zarr-python/issues/707#issuecomment-792338203 What the separator separates is the respective chunk index per dimension.

@SabineEmbacher, @axtimwalde suggests "dimension separator".

**Comment by axtimwalde** [comment]
I used `dimensionSeparator` https://github.com/saalfeldlab/n5-zarr/blob/master/src/main/java/org/janelia/saalfeldlab/n5/zarr/N5ZarrReader.java#L89 or https://github.com/saalfeldlab/n5-universe/blob/main/src/main/java/org/janelia/saalfeldlab/n5/universe/N5Factory.java#L109 but the other choices sound reasonable too.

**Comment by SabineEmbacher** [comment]
I did not make my suggestions regarding the name in order to enforce them.
They were simply suggestions.
I agree with any decision. Even if a decision does not correspond to my personal preferences.
That is perfectly fine with me.

Please make a decision and I will put it in asap according to the specification.

**Comment by joshmoore** [comment]
> I did not make my suggestions regarding the name in order to enforce them.

No worries, @SabineEmbacher. The suggestions were definitely useful. It's more just a matter of https://martinfowler.com/bliki/TwoHardThings.html ...

Since `key_separator` leads to confusion and `dimensionSeparator`/`dimension_separator` is at least used in *some* other implementation, I've updated the description with `dimension_separator`.

On the community call last night, there were no objections to moving forward with the .zarray addition, so I'll open a v2 spec PR now.

I'm a bit more hesitant about defining the heuristic as part of the specification (cf. @jbms comment) I'll leave this open for a discussion of where first-chunk writing falls on the MAY/SHOULD/MUST spectrum.

**Comment by joshmoore** [comment]
I consider the `dimension_separator` saga complete! _whew_
