### ISSUE TITLE
Access patterns / chunk creation order when copying and re-chunking an array

### ISSUE THREAD

**Issue by David-Baddeley** [zarr-developers/zarr-python#727]
This is probably more of an enhancement proposal, rather than a bug, but the access pattern when copying an array with one chunk size to one of another would seem to be far from optimal. For convenience I'm using x, y, and z to denote the 0th, 1st, and 2nd dimensions of the dataset.

#### My scenario:

I have an "array"* which has  `shape=(11697, 13184, 600, 1)` and is currently chunked with a `chunk_shape=(11697, 13184, 1,1)`, which I want to convert to a zarr array with `(256,256,128, 1)` chunks (z-slices).

To be able to do this conversion without loading the whole stack into RAM, I'd thought I'd do the conversion in two steps, first to a zarr array with (256,256,1, 1) chunks and then to the final chunk size. 

```python
>>> input.dtype
dtype('uint16')

>>> input.shape
(11697, 13184, 600, 1)

>>> z1 = zarr.array(input, chunks=(256,256,1,1), dtype='uint16', store=zarr.NestedDirectoryStore('tmp.zarr'))
>>> out = zarr.array(z1, chunks=(256,256,128,1), dtype='uint16', store=zarr.NestedDirectoryStore('out.zarr')
```
I'd somehow assumed that zarr would read one chunk from the input, and write all the output chunks at that z level, and then proceed to the next z level. Instead, it constructs the output along the z (3rd) dimension first, creating the (0,0,0), (0,0,1), ...(0,0,N) tiles before moving on to (0,1,0) etc ... With my given input chunking this creates an immense amount of disk thrash and is super slow, as every z-slice / chunk gets loaded and unloaded for every x, y position. Creating the output chunks in an x,y,z order rather than z,y,x would result in much better performance for my use case. 

I realise that there is no reason to expect a given chunk creation order, and can easily work around this by creating an empty output array and manually looping, manually chunking, and copying the data into the output array a chunk at a time. That said, I wonder if it might not be useful to either attempt to infer the best access order from input and output chunks, or to let the output chunk creation order be specified as an optional argument (which would probably be much easier to implement - chunk order inference sounds like a hard problem).

##### *Full disclosure

My input data was not actually a zarr array, but rather an array-like object (specifically a`PYME.IO.DataSources.ImageSeriesDataSource` pointing at a folder of .tif files), but looking at the code, `zarr.array()` does not check and do anything special in terms of indexing even if the input data is a zarr (or dask) array. I'd thus expect the same issue if the input data was zarr.

##### Version and installation information

``zarr.__version__== 2.8.1 (pip)``
``numcodecs.__version__ == 0.7.3 (pip)``
``python 3.7.9 on OSX``

**Comment by jakirkham** [comment]
Have you looked at using Dask?

It has [`to_zarr` and `from_zarr` functions]( https://docs.dask.org/en/latest/array-creation.html#zarr ) as well as [plethora of array operations]( https://docs.dask.org/en/latest/array.html ), which can be used to build various ETL pipelines of this sort

**Comment by David-Baddeley** [comment]
I have had a look at Dask, though can't see how it provides an easy solution to the problem (input data with poorly chosen chunk dimensions). `dask.array.to_zarr()` and `dask.array.rechunk()` also don't look like they have any smarts as to choosing ordering to make sure data loading is optimally aligned. 

For my immediate problem I'm using a simple hard-coded loop (below) but my rationale in raising the issue was that poorly chunked input data is a common problem (particularly for biological data sets). The naive usage of zarr in such cases triggers a pathological performance problem.

```python
z1 = zarr.empty(shape=tuple(ds.shape), chunks=(320,320,160,1), dtype='uint16', store=zarr.NestedDirectoryStore('sl640.zarr'))

for z in range(z1.shape[2]):
    print('z = ', z)
    d = ds[:,:,z, 0].squeeze()
    for y in range(0, z1.shape[1]-1, 320):
        for x in range(0, z1.shape[0]-1, 320):
            z1[x:(x+320), y:(y+320), z, 0] = d[x:(x+320), y:(y+320)]

```

**Comment by joshmoore** [comment]
see also:
 * https://github.com/pangeo-data/rechunker
 * https://medium.com/pangeo/rechunker-the-missing-link-for-chunked-array-analytics-5b2359e9dc11

> One existing solution is to use Dask’s rechunk function to create a new chunk structure lazily, on the fly, in memory. This works great for some problems. For others, particularly those involving a full rechunk (every source chunk goes into every target chunk), Dask’s algorithm can run out of memory, or produce an unmanageably large number of tasks. (More details can be found in the post linked above.)

**Comment by David-Baddeley** [comment]
Thanks! `rechunker` seems like it should solve the problem nicely. 

I wonder if it might be worth adding a sentence or two and a link to `rechunker` to the zarr docs, but I guess this should also now be searchable which might be enough.

**Comment by jakirkham** [comment]
Thanks Josh!

Glad to hear that works 😄

Sure I think that makes sense. Would you be interested in sending a PR? 🙂

**Comment by David-Baddeley** [comment]
I'd be happy to have a crack at a documentation PR. From a quick look, somewhere in either the 'Chunk Optimisations' or 'Usage Tips' section of the tutorial looks like it would make sense.
