### ISSUE TITLE
Drop "beta" status?

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#731]
https://github.com/zarr-developers/zarr-python/blob/ab5d91b62b83214d5a2b250d830d1996bb08cc56/setup.py#L41

Just saw the beta badge in the README and was a bit surprised.

**Comment by jakirkham** [comment]
It's worth noting that line is 4 yrs old (and come from when Numcodecs was refactored out of Zarr) 😉

The badge in the README is just using that same line IIUC
