### ISSUE TITLE
Fix RTFD/setuptools_scm bad interaction

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/zarr-python#76]
See https://github.com/rtfd/readthedocs.org/issues/2144#issuecomment-234711753

**Comment by jakirkham** [comment]
Is this still outstanding? If so, what do we need to do to address it?

**Comment by joshmoore** [comment]
Nothing is broken as far as I can tell.

**Comment by jakirkham** [comment]
If we find something broken, we can always revisit 🙂
