### ISSUE TITLE
Store refactor

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-python#764]
During the Zarr meeting today, we discussed splitting out the various `Store`s in `storage.py` into separate files (ideally in a Python `storage` package taking the place of `storage.py`). This should make it easier to identify relevant people to get feedback from when making changes to a specific `Store`. Would be good to hear others thoughts on this idea 🙂

**Comment by jakirkham** [comment]
@joshmoore please feel free to add anything else here I may have forgotten

**Comment by joshmoore** [comment]
Thanks, @jakirkham. I'll just add:

 * The motivation from my side was: https://github.com/zarr-developers/zarr-python/pull/759
 * I merged without knowing much (...*cough*... anything) about the implementation and/or PR.
 * With some research (or in this case, with John's help) the people who *did* know were identified.
 * But if we could do that using a GH mechanism, it would make maintenance much easier.

**Comment by jakirkham** [comment]
cc @zarr-developers/core-devs (in case anyone has thoughts on this)

**Comment by rabernat** [comment]
I think this is an excellent idea and I support it 💯 . The storage module is way too big / complicated. I would imaging something like this
```
storage/__init__.py
storage/base.py
storage/directory_store.py
storage/zip_store.py
etc.
```

**Comment by martindurant** [comment]
Sounds reasonable

**Comment by joshmoore** [comment]
So, looking at #759, who should be listed as a CODEOWNER in #781? @jhamman and @shikharsg?

Also: do we want to create a team ("`@zarr-developers/azure-team`") or list individually?

**Comment by jhamman** [comment]
Happy either way. If listing individually, @shikharsg, @tjcrone, @TomAugspurger, and myself are the likely candidates.

**Comment by joshmoore** [comment]
* A pro of a team is it lets people remove themselves
* A pro of individuals is better visibility of additions/removals

**Comment by shikharsg** [comment]
Although I'm happy to be listed as an individual, I would personally prefer a team. Having changed jobs a few months ago I no longer have access to a large azure subscription where I can test this stuff at scale, and have to make do with my laptop.

**Comment by joshmoore** [comment]
@zarr-developers/azure-team now setup.

**Comment by joshmoore** [comment]
https://github.com/zarr-developers/zarr-python/pull/781 is ready for review if someone wants to have a go.

**Comment by jhamman** [comment]
I think the developments in the v3 stream of work warrant closing this.
