### ISSUE TITLE
End support for python 3.6

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#765]
see also:
 * [python version support overview (governance repo)](https://github.com/zarr-developers/governance/issues/11)
 * [3.5 removal issue](https://github.com/zarr-developers/zarr-python/issues/602) and [and removal PR](https://github.com/zarr-developers/zarr-python/pull/603)

https://github.com/zarr-developers/governance/issues/11 currently states "On Jun 23, 2021 drop support for Python 3.6 (initially released on Dec 23, 2016)". Noting that:

 * a) that's coming soon
 * b) a number of dependabot bumps (https://github.com/zarr-developers/zarr-python/pull/760#issuecomment-847684261, https://github.com/zarr-developers/zarr-python/pull/749#issuecomment-842985119, etc.)
 * c) xarray, numpy, and others have dropped support

I'd propose dropping 3.6 (as discussed this evening during [the community call](https://github.com/zarr-developers/community/issues/1)).

Considering this a ["change to the API"](https://github.com/zarr-developers/governance/blob/master/GOVERNANCE.md#decision-making-process), then I'd propose:

👉🏽  Concerns and especially vetoes by June 11th. Even just expressing support (:+1:) or disagreement (:-1:) is appreciated.

**Comment by jakirkham** [comment]
@zarr-developers/core-devs, thoughts?

**Comment by martindurant** [comment]
I agree to drop, because numpy has. 
I don't believe it's a burden to keep maintaining py36, so happy to be persuaded to keep, if there is any good reason.

**Comment by joshmoore** [comment]
I'm currently taking that as a "Yes".

**Comment by joshmoore** [comment]
Please see https://github.com/zarr-developers/zarr-python/pull/774 to disable the builds.

**Comment by joshmoore** [comment]
Builds have been dropped. Only remaining question is when & as what to release.

**Comment by joshmoore** [comment]
Released as 2.9.0
