### ISSUE TITLE
Python multiprocessing writes get deadlocked on Linux systems

### ISSUE THREAD

**Issue by tasansal** [zarr-developers/zarr-python#766]
Hi everyone, 

Our team is trying to write to `zarr` arrays on AWS S3 using Python's built-in `multiprocessing` (`mp`) tools.

Once we start an `mp.Pool()` context, and try to write to a `zarr.Array` our tool deadlocks in certain environments.

Code sample and details below.

#### Code sample

Assuming S3 credentials are set up in your environment.

```python
from itertools import repeat
import multiprocessing as mp

import numpy as np
import zarr


def worker(zarr_array, idx):
    zarr_array[idx, ...] = np.random.randn(1024, 1024).astype('float32')


if __name__ == "__main__":
    zarr_root_path = 's3://XXXXX/benchmarks/debug/test.zarr'  # Sorry, have to blank out S3 buket.

    root = zarr.open_group(zarr_root_path, mode='w')

    dataset = root.create_dataset(
        shape=(5, 1024, 1024),
        chunks=(1, -1, -1),
        name='test1',
        overwrite=True,
        synchronizer=zarr.ProcessSynchronizer('.lock'),
    )

    # dataset[:] = np.random.randn(*dataset.shape)

    iterable = zip(
        repeat(dataset),
        range(5),
    )

    with mp.Pool() as pool:
        pool.starmap(worker, iterable)

```

#### Problem description

We ran into this issue when working with AWS EC2 instances and our on-prem Linux workstations. 
My Windows laptop (x86_64) to S3 works as expected without any issues.
The data is chunked by rows, and as you can see, our parallel writes are aligned with chunk boundaries. We are also using a `zarr.ProcessSynchronizer()` just in case. However, behavior is the same without one.

On a Windows to S3 environment, this code completes as expected. 
However, on the Linux tests, it doesn't complete.
- Does not create any files inside `.zarray` on S3
- When we kill the process, we see it is stuck on threading??

If you comment the iterable, mp.Pool, and code associated with them; and uncomment the `dataset[:] = np.random.randn(*dataset.shape)`, everything runs as expected on all systems. Issue persists with multiprocessing.

Things we have tried:
- Older `s3fs` and `fsspec` versions
- Different Python versions
- Add/remove `ProcessSynchronizer` and `ThreadSynchronizer`
- Tried `blosc.use_threads = False`, and turning off compression
- More things I can't remember..

Here is the traceback after we keyboard interrupt.
```python
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/ubuntu/develop/scratch/parallel_zarr.py", line 33, in <module>
    pool.starmap(worker, iterable)
  File "/home/ubuntu/miniconda3/envs/my_env/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/ubuntu/miniconda3/envs/my_env/lib/python3.9/multiprocessing/pool.py", line 765, in get
    self.wait(timeout)
  File "/home/ubuntu/miniconda3/envs/my_env/lib/python3.9/multiprocessing/pool.py", line 762, in wait
    self._event.wait(timeout)
  File "/home/ubuntu/miniconda3/envs/my_env/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/ubuntu/miniconda3/envs/my_env/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
```

#### Version and installation information

- AWS `c6gd.12xlarge` instance.
- ARM 48 core CPU (aarch64); however on-prem boxes are x86_64.
- Python 3.9.5 (also tested 3.7, and 3.8)
- `conda` environment with `conda` version `4.10.1`. Everything is installed via `conda` except 1 specialized package we built from source.
- `zarr` version `2.8.1`
- `s3fs` version `0.6.0`
- `fsspec` version `2021.05.0`
- `numcodecs` version `0.7.3`

**Comment by rabernat** [comment]
Sorry you're facing some issues! Speaking from experience, these sort of cloud i/o problems can be really hard to debug because there are so many layers to the stack...

As a way of sidestepping the problem, I noticed that you're using a synchronizer. But looking at your chunks and writes, no synchronization should be necessary. Your chunks are non-overlapping, so each process can just do its thing.

**Comment by rabernat** [comment]
My hunch is that it has to do with s3fs / fsspec threading / asyncio, and threads / async work very differently and windows.

**Comment by rabernat** [comment]
FWIW, I just tried to reproduce your problem on https://aws-uswest2.pangeo.io/ and **could not reproduce**. The script finished fine, both with and without a synchronizer. The only difference was that I used the Pangeo [scratch bucket](https://pangeo.io/cloud.html#scratch-bucket) for my s3 path.

```python
zarr_root_path = os.environ['PANGEO_SCRATCH'] + 'debug/test.zarr'
```

Versions:
- Zarr 2.6.1
- s3fs 0.5.2
- fsspec 0.8.5

**Comment by tasansal** [comment]
> FWIW, I just tried to reproduce your problem on https://aws-uswest2.pangeo.io/ and **could not reproduce**. The script finished fine, both with and without a synchronizer. The only difference was that I used the Pangeo [scratch bucket](https://pangeo.io/cloud.html#scratch-bucket) for my s3 path.
> 
> ```python
> zarr_root_path = os.environ['PANGEO_SCRATCH'] + 'debug/test.zarr'
> ```
> 
> Versions:
> 
> * Zarr 2.6.1
> * s3fs 0.5.2
> * fsspec 0.8.5
> * python 3.8.6

Thank you! This exact configuration work as expected. May I asked what made you choose these versions?

It appears on the latest version of s3fs, we are having this issue, can you try that as well if you don't mind?

**Comment by rabernat** [comment]
> May I asked what made you choose these versions?

This is just a version combination that was built automatically by https://github.com/pangeo-data/pangeo-docker-images

> It appears on the latest version of s3fs, we are having this issue, can you try that as well if you don't mind?

I pip installed `s3fs==2021.5.0` which brought along fsspec 2021.5.0. With these versions, I can reproduce your bug.

Pinging @martindurant, our fsspec 🦸 .

**Comment by martindurant** [comment]
Have you tried multiprocessing context -> "spawn"?
Does this work with dask-distributed and processes (which has a different serialisation model) instead of the pool?

**Comment by tasansal** [comment]
@rabernat thank you very much for the feedback and bringing this to @martindurant.

@martindurant using 'Spawn' context works with the latest version. What do you suggest next?

We haven't moved on to `dask` for this project yet, it is on our roadmap though.

**Comment by martindurant** [comment]
If the existing context was "fork", then you need do nothing more: *always* use spawn and be happy - fork should never be used in an application with event loops or threads. If it was "forkserver", then we need to fix this.

**Comment by tasansal** [comment]
@martindurant yes it was the default which is "fork". We changed our code to use "spawn". Is it more beneficial to use "forkserver" over "spawn" if performance is critical in a Unix environment?

**Comment by martindurant** [comment]
> Is it more beneficial to use "forkserver" over "spawn" if performance is critical in a Unix environment?

For long-lived processed, it won't matter, this is a one-time cost of starting the process (and happens to be the only option on Windows). Dask uses forkserver on linux by default, ought to be OK, but

**Comment by rabernat** [comment]
Where would be the right place to document these subtle issues?

**Comment by jakirkham** [comment]
In Dask we try do [spawn by default]( https://github.com/dask/dask/blob/d6bbbb08c92652eae2820e93edc2f3fe502391d3/dask/multiprocessing.py#L132-L134 ). I think if there are places where that is not true in Dask we should just change those (too many issues with fork-without-exec)

**Comment by martindurant** [comment]
There is an issue around trying to detect and noisily raise exceptions when a fork happens. This doesn't seem to be working.

**Comment by jrbourbeau** [comment]
> There is an issue around trying to detect and noisily raise exceptions when a fork happens

I think this is the issue @martindurant is referring to https://github.com/dask/distributed/issues/2520

**Comment by martindurant** [comment]
Also https://github.com/dask/s3fs/issues/464

**Comment by tasansal** [comment]
@martindurant @rabernat Thank you very much for your help. You can close the issue whenever you deem it necessary, we are OK on our side with 'spawn' method.
