### ISSUE TITLE
Dependabot sends PRs to forks

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/zarr-python#777]
Just ran into this personally ( https://github.com/jakirkham/zarr-python/pull/1 ). Looks like this is an open upstream issue ( https://github.com/dependabot/dependabot-core/issues/2804 )

**Comment by joshmoore** [comment]
@jakirkham : did this start following updating your main branch? Did you see any workaorunds that would could potentially work for you, or shall we just disable it until this passes?

**Comment by jakirkham** [comment]
Yeah. Not that I could see. I'm not sure

**Comment by jakirkham** [comment]
Actually I guess their recommendation is delete the fork and refork. Not ideal, but maybe worth trying

**Comment by jakirkham** [comment]
Ok took the plunge and deleted my fork and reforked. Hopefully I haven't broken things too badly on my end. Will see if that fixes it

**Comment by joshmoore** [comment]
Wow. Thanks for taking one for the team. Keep us posted.

**Comment by jakirkham** [comment]
IPython helped make it easier to sync everything locally 😄

No PRs yet 🍀

**Comment by jakirkham** [comment]
Haven't seen PRs in many months. So I think the answer is "delete and refork". Not ideal, but not much we can do about it either.  Users are also free to raise this problem upstream ( https://github.com/dependabot/dependabot-core/issues/2804 ). Going to close.

**Comment by jakirkham** [comment]
Unfortunately have started seeing this with Numcodecs. Tried deleting the fork and reforking, but the issue still occurs

https://github.com/jakirkham/numcodecs/pull/1

**Comment by jakirkham** [comment]
Ok tried deleting the fork again and reforking. It seems to be working. Will keep an eye on it.

Sadly this closed and orphaned existing PRs from my repo.

We may want to revisit dependabot support given this issue remains unaddressed (and may dissuade new contributors from engaging).

**Comment by joshmoore** [comment]
https://github.com/dependabot/dependabot-core/issues/2804#issuecomment-1287486447

> We're actively working on this and a permanent fix should land in the next couple of weeks. We'll share more around the time we''re ready to roll this out

🤞🏽

**Comment by jakirkham** [comment]
Yep saw that. Though that comment is from a couple weeks back

**Comment by joshmoore** [comment]
In the mean time, do we need to restore these?
- https://github.com/zarr-developers/numcodecs/pull/234
- https://github.com/zarr-developers/numcodecs/pull/246

**Comment by jakirkham** [comment]
Tried reopening, but they are orphaned. One can still [retrieve the code from them]( https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally )

**Comment by jhamman** [comment]
I have not been seeing this recently so I think this must be a thing of the past.
