### ISSUE TITLE
fsspec tests are not auto-skipped in test_dim_separator

### ISSUE THREAD

**Issue by QuLogic** [zarr-developers/zarr-python#817]
#### Problem description

Unlike other test files, the fsspec tests are not skipped in `test_dim_separator.py` automatically if it's not available.

#### Version and installation information

Please provide the following:

* Value of ``zarr.__version__`` 2.9.0
* Value of ``numcodecs.__version__`` 0.9.0
* Version of Python interpreter 3.10.0rc1
* Operating system (Linux/Windows/Mac) Fedora Rawhide
* How Zarr was installed (e.g., "using pip into virtual environment", or "using conda") from source

**Comment by joshmoore** [comment]
Thanks, @QuLogic. Good catch. The danger of _always_ relying on `fsspec` in my local environment. :wink:

**Comment by joshmoore** [comment]
Looks like this is also the cause of the failure in https://github.com/conda-forge/zarr-feedstock/pull/48

```
E       ModuleNotFoundError: No module named 'fsspec'
```
