### ISSUE TITLE
normalize_keys regression in version 2.10.0

### ISSUE THREAD

**Issue by d70-t** [zarr-developers/zarr-python#841]
In dca87fcb (#793), the `normalize_keys` parameter default of `FSStore` has been changed back to from `False` to `True` ([see here](https://github.com/zarr-developers/zarr-python/blob/dca87fcbe96ff3be5d74e662815ecb5e67ce9b28/zarr/storage.py#L1072)). This reverts #755 and recreates the issue of #739.

I didn't find a comment on this in the commit message and believe this was done by accident.

**Comment by joshmoore** [comment]
Thanks, @d70-t for all the sleuthing, and sorry if I let something slip through. @d-v-b: can you say if it was intentional or not?

**Comment by d-v-b** [comment]
see #842
