### ISSUE TITLE
v2 specs ambiguity

### ISSUE THREAD

**Issue by aaraney** [zarr-developers/zarr-python#862]
In the v2 zarr doc specs, the last sentence of the chunks section reads:

> The contents of any chunk region falling outside the array are undefined.

In content prior to this sentence, the only mention of a value that represents the absence of a value is `null`, in the context of the `fill_value`, `compressor`, and `filters`, keys. Having read the quoted sentence, I was a little puzzled on the meaning of _undefined_. Can someone clarify if _undefined_ is meant to be a new sentinel value (`undefined`), `null`, or something else? 

Thanks in advance! I would love to update the documentation and gain a better understanding, but I might need a little help first 😉.

**Comment by aaraney** [comment]
@d-v-b Yes, that answers my question! Thanks for the clarification. Cheers!

**Comment by joshmoore** [comment]
Thanks, both. Shall we try to capture any of that in the spec itself? Others may be wondering the same thing!
