### ISSUE TITLE
Single-Writer/Multiple-Readers support?

### ISSUE THREAD

**Issue by mike-lawrence** [zarr-developers/zarr-python#879]
I’ve been looking at zarr as a replacement for my current use of hdf5 in multiple projects, but one key feature I need is for one process to be writing data that other various parallel processes are able to read, called “SWMR” in the hdf5 world. Is that possible with zarr?

**Comment by d-v-b** [comment]
Yes, zarr is designed to support both parallel writing and reading of individual chunks from separate processes.

**Comment by mike-lawrence** [comment]
Oh, quick Q @d-v-b : In hdf5, readers have to wait for the store to be set in SWMR mode before reading anything, and while the writer can add to existing datasets at any time, the writer cannot add new datasets to the store once it has set the store to SWMR mode. Does zarr have any similar limitation?
