### ISSUE TITLE
copy string arrays

### ISSUE THREAD

**Issue by vladpopovici** [zarr-developers/zarr-python#887]
Hello,

When using zarr.copy(...) to copy string arrays, a warning is raised:
```
FutureWarning: missing object_codec for object array; this will raise a ValueError in version 3.0
```
What is the proper call for zarr.copy to avoid this warning and to write future-proof code?

Thanks a lot!
V.

* Value of ``zarr.__version__``: 2.10.1
* Value of ``numcodecs.__version__``: 0.9.1
* Version of Python interpreter: 3.9.7
* Operating system (Linux/Windows/Mac): Linux
* How Zarr was installed (e.g., "using pip into virtual environment", or "using conda"): conda

**Comment by joshmoore** [comment]
Hi @vladpopovici. It's a good point. @abergou also pointed it out in https://github.com/zarr-developers/zarr-python/issues/552. Still open to solutions.

**Comment by aliaksei-chareshneu** [comment]
@joshmoore, I have the same issue with object arrays (copying hdf5 to zarr), however it even does not allow to do it with current zarr version. Could you tell me if there is a workaround?

**Comment by joshmoore** [comment]
Not that I know of, sorry.

**Comment by jakirkham** [comment]
@aliaksei-chareshneu and I discussed their use case in issue ( https://github.com/zarr-developers/zarr-python/issues/954 ). Believe that resolved the issue

**Comment by joshmoore** [comment]
Closing in favor of the mentioned issues as well as #691.
