### ISSUE TITLE
Inconsistent `listdir()` and `rmdir()` method signature across class hierarchy

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [zarr-developers/zarr-python#890]
#### Problem description

The `listdir()` and `rmdir()` signatures are inconsistent across this class hierarchy:
```
BaseStore                             zarr/_storage/store.py
└── Store                             zarr/_storage/store.py
    ├── ABSStore                      zarr/_storage/absstore.py
    ├── MemoryStore                   zarr/storage.py
    ├── DirectoryStore                zarr/storage.py
    ├── FSStore                       zarr/storage.py
    ├── ZipStore                      zarr/storage.py
    ├── LRUStoreCache                 zarr/storage.py
    ├── SQLiteStore                   zarr/storage.py
    └── ConsolidatedMetadataStore     zarr/storage.py
```

```python
class Store(BaseStore):
    [...]
    def listdir(self, path: str = "") -> List[str]:
    [...]
    def rmdir(self, path: str = "") -> None:
    [...]

class ABSStore(Store):
    [...]
    def listdir(self, path=None):
    [...]
    def rmdir(self, path=None):
    [...]

class MemoryStore(Store):
    [...]
    def listdir(self, path: Path = None) -> List[str]:
    [...]
    def rmdir(self, path: Path = None):
    [...]

class DirectoryStore(Store):
    [...]
    def listdir(self, path=None):
    [...]
    def rmdir(self, path=None):
    [...]

class FSStore(Store):
    [...]
    def listdir(self, path=None):
    [...]
    def rmdir(self, path=None):
    [...]

class ZipStore(Store):
    [...]
    def listdir(self, path=None):
    [...]

class LRUStoreCache(Store):
    [...]
    def listdir(self, path: Path = None):
    [...]

class SQLiteStore(Store):
    [...]
    def listdir(self, path=None):
    [...]
    def rmdir(self, path=None):
    [...]

class ConsolidatedMetadataStore(Store):
    [...]
    def listdir(self, path):
    [...]
```

* Argument `path` should consistently be either a `str` or a `Path`
* The default value of `path` should consistently be either `""` or `None`.
* `ConsolidatedMetadataStore.listdir()` needs a default value.

**Comment by DimitriPapadopoulos** [comment]
One problem is that `BaseStore`/`Store` are defined in [`zarr/_storage/store.py`](https://github.com/zarr-developers/zarr-python/blob/master/zarr/_storage/store.py), where `Path` has not been defined so far, while most most the subclasses are defined in [`zarr/storage.py`](https://github.com/zarr-developers/zarr-python/blob/master/zarr/storage.py), which defines:
https://github.com/zarr-developers/zarr-python/blob/f0677c2e051cad672e781c6bf63b5edfe57aaca4/zarr/storage.py#L86

**Comment by DimitriPapadopoulos** [comment]
But then why `bytes`? All paths should be `str`, shouldn't they?

**Comment by joshmoore** [comment]
@jakirkham: did you ever get a chance to look at this one?

**Comment by DimitriPapadopoulos** [comment]
Can `Path` be replaced by [`pathlib.Path`](https://docs.python.org/fr/3/library/pathlib.html#pathlib.Path)? If not, re-using a well-known class name is confusing. Otherwise, switching should not be a problem for Python >= 3.8.

**Comment by jhamman** [comment]
Closing as stale.

**Comment by DimitriPapadopoulos** [comment]
This issue is probably obsolete in v3, superseded by https://github.com/zarr-developers/zarr-python/pull/2381.
