### ISSUE TITLE
Use litterals to create data structures?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [zarr-developers/zarr-python#902]
#### Minimal, reproducible code sample, a copy-pastable example if possible

Would you accept a patch to silence these DeepSource.io alerts?
https://deepsource.io/gh/DimitriPapadopoulos/zarr-python/issue/PTC-W0019/occurrences

In short, it would change code such as:
```python
        store = dict()
```
to:
```python
        store = {}
```

#### Problem description

This is debatable of course:
* I do find `dict()` easier to read than `{}` myself, at least for empty structures. Python is all about readability and maintainability.
* On the other hand, DeepSource.io views this as a "performance" issue, not a readability issue:
  > Using the literal syntax can give minor performance bumps compared to using function calls to create `dict`, `list` and `tuple`. 
  > 
  > This is because here, the name `dict` must be looked up in the global scope in case it has been rebound. Same goes for the other two types `list()` and `tuple()`.

**Comment by joshmoore** [comment]
Hi @DimitriPapadopoulos. We chatted about it at the regular community meeting yesterday, and general appreciation from everyone for all your work on this! A couple of questions/thoughts:
 * How hard would it be to bundle more of the changes with the goal of reducing the overall notification burden?
 * Do you have an idea of how many more you have coming?
 * For this on in particular, is there a configuration option that would silence it as well?

cc: @jakirkham

**Comment by DimitriPapadopoulos** [comment]
I think this is one of the last PRs. Most other DeepSource.io alerts do not seem very interesting. My suggestion would be to:
* create a single issue for future DeepSource.io / LGTM.com discussions,
* create a single associated PR for related changes,
* split changes into multiple commits, so that it's easy to discard those changes that you don't want and keep those that you find interesting.

**Comment by DimitriPapadopoulos** [comment]
Yes, there are configuration options:
* in file **`.lgtm.yml`** for [LGTM](https://lgtm.com/help/lgtm/lgtm.yml-configuration-file),
* in file **`.deepsource.toml`** for [DeepSource](https://deepsource.io/docs/setup-analysis/#activate-analysis).

I can add such files if you don't mind the clutter.

**Comment by shoyer** [comment]
My personal opinion is that these sorts of refactors are not worth the trouble. The "performance" cost of looking up the `dict` symbol is unlikely to ever make a measureable difference in real code.

**Comment by DimitriPapadopoulos** [comment]
Agreed, remains the question if silencing or not alerts. Some (few) alerts are useful, but the useful ones get lost in the noise generated by such "performance" alerts.

**Comment by joshmoore** [comment]
I have no objections to the configuration files, especially if that means it helps you detect problems, @DimitriPapadopoulos. I guess if there were a GHA workflow running these they'd be even more pertinent.

**Comment by DimitriPapadopoulos** [comment]
I suggest adding an LGTM.com configuration file in #909. I think it is not urgent to add LGTM.com as a GHA in the short term, as LGTM.com seems to be run periodically on repositories it has been run on once. In any case, I cannot do that myself, a repository owner must do that:
https://lgtm.com/help/lgtm/github-apps-integration

**Comment by DimitriPapadopoulos** [comment]
I'll see what I can do with DeepSource.io. It has more false positives, or debatable alerts, and no way to silence them through the configuration file as far as I can see. Again, I cannot activate DeepSource.io myself, a repository owner must do that:
https://deepsource.io/docs/setup-analysis#activate-analysis

For now, I have activated DeepSource.io on my own fork (not sure if you can see the results):
https://deepsource.io/gh/DimitriPapadopoulos/zarr-python

I'm not certain DeepSOurce.io can be configured to run on each PR, for example from GHA. Rather, it is run periodically if changes have been pushed to the monitored branch.

**Comment by jakirkham** [comment]
Was there anything more we wanted to do on this issue or is this good to close?

**Comment by DimitriPapadopoulos** [comment]
Good to close as far as I'm concerned.

**Comment by jakirkham** [comment]
Thanks again for all the hard work here Dimitri! 😄
