### ISSUE TITLE
bsddb3 is deprecated

### ISSUE THREAD

**Issue by QuLogic** [zarr-developers/zarr-python#904]
#### Problem description

It appears that it's really only used in tests, but `bsddb3` is deprecated according to https://www.jcea.es/programacion/pybsddb.htm It does not support Python >=3.10, and instead `berkeleydb` should be used.

**Comment by jakirkham** [comment]
Just to be clear this is proposing we move to this?

https://pypi.org/project/berkeleydb/

**Comment by QuLogic** [comment]
I believe so, yes.

**Comment by dstansby** [comment]
Support has been removed in upcoming v3, and in v2 we dropped testing (https://github.com/zarr-developers/zarr-python/pull/2344), so I think this can be closed.
