### ISSUE TITLE
Copying HDF5 to Zarr - missing object_codec for object array

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [zarr-developers/zarr-python#954]
Dear all,

I am trying to copy_all entire HDF5 file (or copy a group from it) to zarr structure. When it reaches an object array from HDF5, ValueError pops up: missing object_codec for object array. Could you tell me if there is a workaround?

Best regards,
Aliaksei

* Value of ``zarr.__version__``: 2.10.3
* Value of ``numcodecs.__version__``: 0.9.1
* Version of Python interpreter: 3.8.2
* Operating system (Linux/Windows/Mac): Windows 7
* How Zarr was installed (e.g., "using pip into virtual environment", or "using conda"): using pip into virtual environment

**Comment by jakirkham** [comment]
What if you preinitialize the relevant arrays with the needed `object_codec`s?

**Comment by aliaksei-chareshneu** [comment]
@jakirkham, thank you for your response. I am relatively new to HDF5 and Zarr, so I apologize for a potentially naive question. Do you mean doing something like:
`zarr.array(array_data, dtype=object, object_codec=numcodecs.MsgPack())`
for each object array, and copy all the arrays one by one using copy instead of copy_all?

**Comment by jakirkham** [comment]
Yeah doing something like that for initialization would work.

Personally would write a visitor pattern perhaps using [h5py's `Group.visititems`]( https://docs.h5py.org/en/stable/high/group.html#h5py.Group.visititems ) to visit everything in the HDF5 file. Then can use [Zarr's `Group.require_group`]( https://zarr.readthedocs.io/en/stable/api/hierarchy.html#zarr.hierarchy.Group.require_group ) to initialize all `Group`s and [Zarr's `Group.create_dataset`]( https://zarr.readthedocs.io/en/stable/api/hierarchy.html#zarr.hierarchy.Group.create_dataset ) to create `Array`'s with the requisite `object_codec`, `dtype`, and any other relevant values.

Then could follow up with a call to `copy`. Alternatively this could be part of the same visitor routine above.

**Comment by aliaksei-chareshneu** [comment]
Dear @jakirkham, many thanks!

**Comment by jakirkham** [comment]
Take it that means things worked for you? 🙂

**Comment by aliaksei-chareshneu** [comment]
@jakirkham, not exactly that approach, but a similar one. Thanks again for devoting your time to help me!
