### ISSUE TITLE
Updates for zarr.readthedocs.io/

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-python#956]
* [ ] Now that https://zarr.dev is no longer just a blog, we should link back from the documentation that's servered from readthedocs.
* [ ] Update the logo

cc: @msankeys963

**Comment by GbotemiB** [comment]
Hi @joshmoore, Can i take this?

if yes, where on the docs page can the link back to https://zarr.dev be?

**Comment by steph237** [comment]
Hi @joshmoore and @MSanKeys963 can I be assigned to this issue ?

**Comment by jakirkham** [comment]
Yep, go for it Stephanie! 😄

**Comment by steph237** [comment]
Hello @jakirkham and @joshmoore I just included in the documentations the link to the official Zarr website. Here is the link to the PR https://github.com/zarr-developers/zarr-python/pull/1212 . Please let me know of any feedback

**Comment by steph237** [comment]
Hello @jakirkham and @joshmoore I just included in the documentations the link to the official Zarr website. Here is the link to the PR https://github.com/zarr-developers/zarr-python/pull/1212 . Please let me know of any feedback

**Comment by steph237** [comment]
Hello @jakirkham and @joshmoore I just included in the documentations the link to the official Zarr website. Here is the link to the PR https://github.com/zarr-developers/zarr-python/pull/1212 . Please let me know of any feedback

**Comment by joshmoore** [comment]
Thanks for #1212, @steph237. I'm going to consider this done and we can continue the conversation on your PR.
